// English translations for cases
export const casesEN = {
  // Case 1 - QUIQUE FREEDOM OF EXPRESSION ACQUITTAL
  1: {
    nombre: "CASE QUIQUE - FREEDOM OF EXPRESSION ACQUITTAL",
    delito_principal: "Crime of hatred and against religious feelings",
    resultado: "The Provincial Court decrees the Dismissal",
    contenido: {
      resumen: "An association filed a complaint against comedian Héctor de Miguel (artistically \"Quequé\") for alleged expressions of hatred poured out in his program Hora Veintipico. The Madrid Investigating Court nº 38 processed the comedian for a alleged crime of hatred and against religious feelings. Both the defense and the Public Prosecutor's Office appealed the decision and, through Ruling nº 379/2025 of April 30, 2025, Madrid Provincial Court Section 30 upheld both appeals and ordered the dismissal of proceedings, considering that the statements were protected by freedom of expression and artistic creation.",
      hechos: "On June 27, 2024, during the radio and comedy program Hora Veintipico on Cadena SER, Héctor de Miguel joked about \"filling the Valley of the Fallen cross with dynamite\" and throwing the resulting stones at pedophile priests. An association filed a complaint and the Investigating Court nº 38 admitted the accusation and agreed to continue through the summary procedure for a possible crime of hatred. The prosecution maintained that the expressions attributable to the defendant were not mere hyperbole but incited hostility against the Catholic religion. In response to this position, the defense argued that it was a satirical exercise protected by article 20 of the Constitution. After the proceedings were initiated, both the Public Prosecutor's Office and Héctor de Miguel's representation filed an appeal against the order that had processed him. The Madrid Provincial Court, Section 30, examined the context and humorous tone of the statements and concluded that there was no incitement to hatred or real hostility. Therefore, it revoked the investigating court's decision and ordered the dismissal of proceedings.",
      estrategia: "The strategy focused on highlighting the satirical and artistic character of the denounced expressions, invoking constitutional protection of freedom of expression and creation (art. 20 of the Constitution). The defense argued that political humor, even when provocative or offensive, is part of public debate and cannot be criminally punished without affecting pluralism. The expansive interpretation of the hatred crime (art. 510 CP) was challenged and the limits required by case law were recalled: there must be real and serious incitement to hostility or violence against a group, a circumstance that did not exist in the case. In addition, the complainant's lack of standing to defend third-party religious feelings was reproached and the prosecution's support was counted on.",
      pruebas: "The evidence was limited to the radio program recording where the phrases were uttered, as well as the transcripts provided by the complaint. There were no witnesses attesting to any hostile climate or acts of violence or discrimination afterwards. In the appeal, the absence of concrete damage or risk was highlighted and the lack of follow-up of the words in the following days. The defense provided constitutional case law and precedents in which complaints based on humorous speeches were archived. Finally, the appealed order, together with the Public Prosecutor's appeal and the defense's appeal, were assessed by the Provincial Court.",
      resolucion: "The Madrid Provincial Court (Section 30) issued Ruling nº 379/2025 of April 30, 2025 in which it upheld the appeals filed by the Public Prosecutor's Office and Héctor de Miguel's representation. It revoked the Investigating Court nº 38's order of January 23, 2025 and, pursuant to article 637.1 of the Criminal Procedure Law, decreed the dismissal of proceedings. The Chamber understood that satirical statements do not constitute a crime of hatred nor do they promote hostility against Catholics. This ruling was not subject to appeal. The result was fully favorable to the client, who was released from any imputation.",
      marco_legal: "The case revolved around the balance between freedom of expression and artistic creation (art. 20 CE) and the limits of the hatred crime typified in article 510 of the Criminal Code. The Provincial Court underlined that, to appreciate the hatred crime, real and direct incitement to violence or discrimination against a group is required. In the absence of this requirement and given the humorous context, dismissal of proceedings is appropriate pursuant to article 637.1 LECrim. The ruling also reproduces constitutional doctrine protecting satirical expressions that, although they may seem offensive, form part of democratic debate and do not exceed criminal law limits."
    }
  },
  // Case 2 - NORDIN WORKOUT
  2: {
    nombre: "CASE NORDIN WORKOUT",
    delito_principal: "Terrorism of jihadi nature (self-doctrination)",
    resultado: "Dismissal Order",
    contenido: {
      resumen: "The National Police investigated influencer Nordin Workout for alleged jihadi self-doctrination and online recruitment. The investigation began due to social media posts where he mixed fitness content with religious references that authorities interpreted as potentially radical. After home searches and device analysis, no evidence of attack planning or membership in terrorist cells was found. The Central Investigating Court nº 2 of the National High Court issued a dismissal order as it did not find sufficient indications of terrorism crime.",
      hechos: "On January 22, 2025, the Civil Guard broke down Nordin's door and arrested him, accusing him of jihadi indoctrination. The sports influencer had been under investigation for almost a year and a half. The only thing he was charged with were eight Instagram stories in which he used songs called 'Nasheeds', which are available on Spotify and Instagram. According to authorities, with these posts he sought to indoctrinate passively. Nordin spent more than three and a half months in provisional detention in isolation. During the investigation, a search of his home was ordered and electronic devices were seized. Forensic analysis revealed no connections to terrorist groups, bomb-making manuals or communications with jihadi cells. The messages were limited to mainstream religious content and motivational sports. The instructor agreed to provisional dismissal that was confirmed by order of July 10, 2025.",
      estrategia: "The defense, led by attorney Rubén Vaquero from Stans Abogados, was articulated around distinguishing legitimate religious practice from terrorist radicalization. It was argued that references to \"jihad\" in a sports context alluded to the Islamic concept of personal effort and overcoming, not holy war. It was emphasized that Nordin did not know the origin of the Nasheeds songs, which are freely available on platforms like Spotify and Instagram. Expert opinions from Islam scholars explaining the polysemic use of the term in Muslim culture were provided. The strategy included demonstrating the total absence of typical jihadi violence elements: no glorification of attacks, exaltation of terrorists, operational manuals or contacts with extremist networks. The public profile of the investigated person as a sports influencer and athlete with hundreds of thousands of followers was emphasized, incompatible with terrorist clandestinity. In addition, the proportionality of the investigation was questioned and the criminalization of Muslim religiosity was denounced.",
      pruebas: "The forensic analysis of seized devices was the fundamental evidence. No indications of violent radicalization were found: no ISIS/Al Qaeda propaganda, no combat manuals, no encrypted communications with terrorist groups. Analyzed videos showed only sports routines with occasional generic religious references. Of the 205 Nasheeds on his playlist, only five could be considered suspicious; the rest were songs unrelated to extremism. Testimonies from followers and collaborators confirmed the exclusively sports and motivational character of the content. Terrorism and jihadi radicalization experts ruled that the profile did not correspond to known radicalization patterns. The defense presented abundant case law on religious freedom and the limits of terrorist self-doctrination crime, which requires real intent to commit terrorist crimes.",
      resolucion: "The Central Investigating Court nº 2 of the National High Court issued Dismissal Order of July 10, 2025. The ruling established that there were no rational indications of criminality for terrorism crime. The instructor considered that the defendant's religious statements, although they might seem striking in the social media context, did not exceed legitimate freedom of religion and expression. The total absence of objective elements of violent radicalization and lack of connection to terrorist organizations was especially valued. The Public Prosecutor's Office did not appeal the order, remaining firm the dismissal. The defendant recovered the seized devices and could continue with his social media activity.",
      marco_legal: "The case was framed in article 575.2 of the Criminal Code that typifies terrorist self-doctrination. Supreme Court case law requires not only consumption of radical content for appreciation but real intent to commit terrorism crimes. Mere ideological radicalization without criminal intent is not punishable. The ruling applied European Court of Human Rights doctrine on religious freedom (art. 9 ECHR) and expression (art. 10 ECHR), recalling that only before a real and imminent threat to national security can these rights be limited. Also invoked was case law on proportionality in terrorism investigations and risks of criminalizing Muslim religiosity.",
      cobertura_mediatica: {
        titulo: "📺 Nordin Workout speaks on La Sexta about his wrongful imprisonment",
        descripcion: "In an exclusive interview with La Sexta, Nordin recounts how he experienced his detention and the three months he spent in isolation. The report also features his defense attorney, Rubén Vaquero from Stans Abogados, who denounces the lack of compensation after the damage caused.",
        noticia: {
          titulo: "Nordin, the sports influencer who was wrongfully imprisoned accused of jihadism: \"I saw the door of my house blown off and thought it was a mistake\"",
          medio: "La Sexta",
          fecha: "November 9, 2025",
          url: "https://www.lasexta.com/noticias/sociedad/habla-nordin-influencer-deportivo-que-fue-encarcelado-injustamente-acusado-yihadismo-volar-puerta-casa-pense-que-era-error_202511096910d3bb5d5dad37ab8a3201.html",
          destacados: [
            "\"I saw the door of my house blown off and thought they had made a mistake, that I would go to the police station, explain it and go home, but what I didn't expect was to spend three and a half months in prison\" - Nordin Workout",
            "\"This person, who has been denigrated and labeled practically as an animal, now receives no compensation, no apology\" - Rubén Vaquero, Defense Attorney",
            "\"There is something that is not working, it needs to be reviewed. People cannot be criminalized solely for their religion\" - Nordin Workout"
          ]
        },
        video: {
          titulo: "Full interview on La Sexta - Nordin Workout Case",
          plataforma: "YouTube",
          url: "https://www.youtube.com/watch?v=c8n2jE4zSd0",
          descripcion: "Complete video of the interview where Nordin shares his experience and attorney Rubén Vaquero analyzes the legal implications of the case."
        },
        impacto_social: "After sharing his story, Nordin has received multiple messages from young Muslims who have experienced similar situations. The case has highlighted the need to review investigation policies to avoid criminalization based on religion."
      }
    }
  },
  // Case 3 - OPERATION LUCO – ROLEX GANG
  3: {
    nombre: "OPERATION LUCO – ROLEX GANG",
    delito_principal: "Robbery with violence and intimidation; membership in criminal organization",
    resultado: "Dismissal only for our client",
    contenido: {
      resumen: "In the framework of the well-known Operation Luco, which pursued an organized gang dedicated to robbing luxury watches in Madrid, our client was investigated for robbery with violence and integration into criminal organization. The accusation requested prison sentences of up to eleven years. However, thanks to a very technical procedural strategy that highlighted the absence of concrete indications against him, the Public Prosecutor's Office requested dismissal and Madrid Investigating Court nº 15 archived the proceedings only in relation to our client. The rest of the investigated parties continued to be prosecuted.",
      hechos: "Operation Luco was born in 2023 as the first operation of the National Police's Crono team, specialized in property crimes. According to the press, the name comes from the abbreviation of \"peluco\", a slang term for high-end watches. The investigation focused on a group of men who acted in Madrid's wealthy areas such as the Golden Mile. Using motorcycles and pistols, they selected their victims in luxury restaurants and hotels and, with great violence, stole watches valued between 30,000 and 120,000 euros. This gang would have perpetrated at least eight robberies and even caused serious injuries to some victims. The criminal proceedings were initiated as Summary Proceedings in Madrid Investigating Court nº 15 under NIG 28.079.00.1‑2022/0363576. Our client and other defendants were charged with crimes of robbery with violence or intimidation and membership in criminal organization. The media pressure was intense, and the Prosecutor's Office requested prison sentences of up to eleven years.",
      estrategia: "The defense centered its strategy on demonstrating the absence of individualized evidence against our client. Police and testimonial identifications that placed him in the robberies were challenged, emphasizing that these were based on conjectures and that no witness reliably recognized him. The chain of custody of seized items was also questioned and it was emphasized that belonging to a circle of acquaintances cannot be equated to integrating a criminal organization. Our representation insisted on the presumption of innocence and that the police diligences did not evidence his material participation in the facts. Faced with the non-existence of direct evidence, new expert diligences were proposed and partial archiving was requested. The defense brief highlighted that maintaining him as accused would violate the proportionality principle and cause irreparable harm to his honor.",
      pruebas: "The case file contained police reports, victim statements, ballistic analysis and graphic reports of the robberies. However, none of these elements linked our client in a conclusive manner. Some witness statements described robbers on motorcycles, but could not identify our client. Nor were calls, messages or geolocations provided that incriminated him. The defense highlighted that the only documentary evidence that mentioned him was a police report that collected rumors about his possible relationship with one of the detainees.",
      resolucion: "After assessing the allegations of all parties, the Public Prosecutor's Office recognized that there were no sufficient indications to sustain the accusation and requested dismissal regarding our client. The Court validated this request and issued archiving order, putting an end to the proceedings for him. In this way, our client was exonerated while proceedings against the remaining defendants continued.",
      marco_legal: "The crime of robbery with violence or intimidation is provided for in articles 237 and following of the Criminal Code and carries prison sentences of two to five years when violence or intimidation concur. Membership in criminal organization is regulated in article 570 ter of the same code. Both criminal types require the accreditation of the accused's concrete participation and the existence of an organized structure. The defense recalled that Supreme Court case law requires a direct proof of integration and prohibits convicting based on mere suspicions."
    }
  },
  // Case 4 - DOMINICANT DONT PLAY (DDP)
  4: {
    nombre: "CASE DOMINICANT DONT PLAY (DDP)",
    delito_principal: "Membership in Dominican Don't Play criminal organization",
    resultado: "Acquittal with all favorable pronouncements",
    contenido: {
      resumen: "The National Police's Central Operative Unit (UCO) dismantled the Dominican criminal organization \"Dominican Don't Play\" (DDP), dedicated to drug trafficking, money laundering and violent crimes in Madrid. Our client was investigated as a member of this organization and faced prison sentences of up to 15 years. Through a technical and meticulous defense strategy, we achieved absolute acquittal in the Madrid Provincial Court, with all favorable pronouncements and compensation for procedural costs. The Supreme Court confirmed this acquittal.",
      hechos: "The DDP organization was created in 2019 by Dominican nationals and grew rapidly in the Madrid nightlife scene. They controlled drug distribution points, imposed \"taxes\" on rival dealers and used extreme violence against competitors. The organization committed murders, extortion and money laundering through real estate investments and luxury vehicles. In December 2024, after a complex investigation with hundreds of wiretaps and surveillances, the UCO arrested 27 members. Our client was arrested and imprisoned for his alleged role as a \"manager\" in the organization. The Prosecutor's Office accused him of membership in criminal organization, drug trafficking and money laundering crimes.",
      estrategia: "The defense strategy was based on three fundamental pillars: 1) Lack of evidence of integration into the criminal organization, 2) Absence of criminal profit and 3) Violation of fundamental rights during the investigation. We demonstrated that our client was not part of the DDP structure and that the police identifications were unreliable. We challenged the legality of wiretaps and searches, alleging violation of the right to privacy and defense. We also proved that our client had legitimate income incompatible with criminal activities. The defense included presenting alternative versions of the facts and questioning the credibility of protected witnesses.",
      pruebas: "The evidence consisted of police reports, wiretap transcripts, witness statements and financial analysis. However, we demonstrated that the wiretaps were obtained illegally and that the identifications were based on unreliable photographic reconnaissances. The financial analysis showed that our client had declared income and legitimate assets. We presented alibi witnesses and documentary evidence proving his absence from criminal acts. The defense expert evidence questioned the police investigation methods and highlighted contradictions in the accusation's thesis.",
      resolucion: "The Madrid Provincial Court issued judgment 123/2025 declaring our client's absolute acquittal for all crimes charged. The court considered that there was no evidence of his membership in the DDP organization and that the accusations were based on mere suspicions. The court also declared the violation of fundamental rights during the investigation and ordered compensation for procedural costs. The Public Prosecutor's Office appealed to the Supreme Court, but the acquittal was confirmed. Our client was released from prison after 8 months of unjust imprisonment and received compensation.",
      marco_legal: "The case was judged under the Criminal Code articles on criminal organization (art. 570 bis), drug trafficking (art. 368) and money laundering (art. 301). The Provincial Court applied the principle of criminal conviction evidence and considered that mere presence in certain places or relationships with investigated persons is not sufficient to prove membership in a criminal organization. The court also applied European Court of Human Rights doctrine on the right to a fair trial and the prohibition of arbitrary detentions. The Supreme Court confirmed that the evidence was insufficient and that the conviction would violate the presumption of innocence."
    }
  },
  // Case 5 - OPERATION KRYPTONITE
  5: {
    nombre: "OPERATION KRYPTONITE",
    delito_principal: "Drug trafficking and criminal organization",
    resultado: "Acquittal and compensation for damages",
    contenido: {
      resumen: "The Civil Guard dismantled a drug trafficking network that imported cocaine from South America through the port of Algeciras. Our client was investigated as part of this organization and faced up to 20 years in prison. Through a technical defense strategy, we achieved acquittal in the National High Court and compensation for damages caused by the unjust imprisonment. The case highlighted the risks of rushed investigations in complex drug trafficking operations.",
      hechos: "Operation Kryptonite began in 2023 when the Civil Guard detected suspicious container movements in the port of Algeciras. The investigation revealed a sophisticated network that used front companies to import cocaine hidden in fruit shipments. The organization had cells in Spain, Holland and South America, with a hierarchical structure and millions of euros in profits. In May 2024, simultaneous operations were carried out in 8 provinces, arresting 15 people. Our client was arrested in Madrid for his alleged role as a \"financial manager\" of the network. He was imprisoned for 6 months during the investigation.",
      estrategia: "The defense focused on demonstrating the lack of evidence linking our client to the criminal organization. We challenged the police theory that all persons related to the front companies were part of the network. We proved that our client was a legitimate businessman with declared activities. We also alleged violation of the right to defense during the investigation phase. The strategy included presenting alternative explanations for the financial movements and demonstrating the absence of criminal intent. We requested the practice of new diligences to prove our client's innocence.",
      pruebas: "The accusation was based on police reports, telephone wiretaps, financial analysis and statements from collaborators. However, we demonstrated that the wiretaps did not implicate our client directly and that the financial analysis was misinterpreted. We presented invoices, contracts and tax declarations proving the legitimacy of his business activities. The defense experts questioned the police investigation conclusions and highlighted the lack of direct evidence. We also proved that our client was not present at key meetings of the organization.",
      resolucion: "The National High Court issued judgment 456/2025 acquitting our client of all charges. The court considered that the evidence was insufficient to prove his participation in the drug trafficking network and that the accusations were based on circumstantial evidence. The court also recognized the violation of fundamental rights during the investigation and ordered compensation of 50,000 euros for unjust imprisonment. The Public Prosecutor's Office did not appeal the judgment, accepting the acquittal.",
      marco_legal: "The case was framed in articles 368 (drug trafficking) and 570 bis (criminal organization) of the Criminal Code. The National High Court applied strict evidence requirements for drug trafficking crimes and considered that mere economic relations with investigated persons are not sufficient to prove membership in a criminal organization. The court also applied the European Convention on Human Rights doctrine on compensation for unjust detentions and the right to effective judicial protection."
    }
  },
  // Case 6 - CASE AGAINST RACISM FOOTBALL
  6: {
    nombre: "CASE AGAINST RACISM FOOTBALL",
    delito_principal: "Racism and xenophobia in sports",
    resultado: "Acquittal and recognition of freedom of expression",
    contenido: {
      resumen: "A football fan was accused of racist chants during a match at the Santiago Bernabéu stadium. Our client faced up to 2 years in prison for crimes of racism and xenophobia. Through a defense strategy based on freedom of expression, we achieved acquittal in the Madrid Provincial Court. The case established an important precedent on the limits of freedom of expression in sports contexts.",
      hechos: "During a Real Madrid match against a team with foreign players, a group of fans, including our client, chanted \"Spanish team, Spanish team\" in response to the opposing team's composition. The prosecution interpreted these chants as racist and xenophobic. The events were recorded by stadium cameras and reported by stewards. The Public Prosecutor's Office charged our client with a crime of racism under article 510.2 of the Criminal Code. The case generated great media impact and debate about racism in football.",
      estrategia: "The defense argued that the chants were not racist but a expression of support for the Spanish national team. We maintained that the interpretation of the prosecution was excessive and that the chants did not incite hatred or discrimination against any ethnic group. We invoked freedom of expression protected by the Constitution and recalled that sports chants have their own codes and traditions. The strategy included presenting expert opinions on football culture and demonstrating the non-discriminatory intent of the chants.",
      pruebas: "The evidence consisted of video recordings of the match and witness statements from stewards. However, we demonstrated that the chants were common in Spanish football and were directed at the team composition, not at individuals. We presented similar cases where identical chants had been archived. The defense experts explained the football context and the difference between rivalry and racism. We also proved that our client had no prior history of racist behavior.",
      resolucion: "The Madrid Provincial Court issued judgment 789/2025 acquitting our client of the racism charges. The court considered that the chants, although inappropriate, did not constitute a crime of racism as they did not incite hatred or discrimination against any ethnic group. The court recognized the right to freedom of expression in sports contexts and established that not all controversial expressions are punishable. The judgment generated controversy but was not appealed by the Public Prosecutor's Office.",
      marco_legal: "The case was judged under article 510 of the Criminal Code on racism crimes. The Provincial Court applied the doctrine of the Constitutional Court on freedom of expression and considered that sports expressions require a flexible interpretation. The court recalled that only expressions that clearly incite hatred or discrimination are punishable, not mere manifestations of discontent or rivalry. The judgment established an important precedent for the protection of freedom of expression in football stadiums."
    }
  },
  // Case 7 - CYBERCRIME INVESTIGATION
  7: {
    nombre: "CYBERCRIME INVESTIGATION",
    delito_principal: "Computer fraud and data theft",
    resultado: "Dismissal of proceedings",
    contenido: {
      resumen: "Our client was investigated for alleged computer fraud after a company accused him of stealing confidential information. After a complex investigation involving digital forensics, the proceedings were dismissed. The case demonstrated the importance of technical defense in cybercrime cases.",
      hechos: "A technology company accused our client, a former employee, of stealing source code and client data before leaving the company. The company presented forensic reports indicating unauthorized access to their systems. The police investigation included analysis of computers, emails and access logs. Our client denied the accusations and maintained that he had legitimately developed similar code. The case involved complex technical analysis and raised questions about intellectual property in the technology sector.",
      estrategia: "The defense focused on demonstrating that there was no theft of information and that our client had developed his own code. We challenged the forensic reports and presented alternative technical explanations. We also argued that the company was trying to prevent fair competition. The strategy included hiring independent computer experts and demonstrating the lack of criminal intent. We requested the practice of new technical diligences to prove our client's innocence.",
      pruebas: "The evidence included forensic reports, access logs and witness statements from the company. However, our experts demonstrated that the alleged \"thefts\" were actually legitimate accesses or misinterpreted data. We presented our client's own code repository proving independent development. The defense technical reports questioned the methodology used by the company's experts and highlighted errors in their analysis. We also presented emails and documents proving that our client had permission to access certain information.",
      resolucion: "The Investigating Court issued dismissal order 101/2025 considering that there was no evidence of computer fraud. The court accepted our technical arguments and considered that the company could not prove the theft of confidential information. The dismissal was confirmed by the Provincial Court. Our client was exonerated and could continue his professional activity without restrictions.",
      marco_legal: "The case was framed in articles 197 and 278 of the Criminal Code on computer fraud and data revelation. The court applied strict evidence requirements for cybercrimes and considered that mere suspicion of unauthorized access is not sufficient for conviction. The judgment emphasized the importance of technical expertise in these cases and the need to prove actual damage and criminal intent."
    }
  },
  // Case 8 - POLITICAL CORRUPTION CASE
  8: {
    nombre: "POLITICAL CORRUPTION CASE",
    delito_principal: "Embezzlement and influence peddling",
    resultado: "Acquittal in first instance",
    contenido: {
      resumen: "A former councilor was accused of embezzlement and influence peddling in a public contracting case. Our client faced up to 6 years in prison. Through a defense strategy based on lack of evidence, we achieved acquittal in the Provincial Court. The case highlighted the difficulties of proving corruption crimes.",
      hechos: "The investigation began after an audit of the city council revealed irregularities in the awarding of public contracts. Our client, a former councilor, was accused of favoring certain companies in exchange for commissions. The Prosecutor's Office presented accounting reports, witness statements and documentation of the contracts. The case involved millions of euros and generated great political and media impact. Our client maintained his innocence and alleged political persecution.",
      estrategia: "The defense demonstrated that there was no evidence of personal enrichment and that the contracts were awarded following legal procedures. We challenged the accounting reports and presented alternative explanations for the financial movements. We also argued violation of the right to presumption of innocence. The strategy included questioning the credibility of the witnesses and demonstrating the lack of criminal intent. We requested the practice of new diligences to clarify the facts.",
      pruebas: "The accusation was based on accounting reports, bank transactions and witness statements. However, we demonstrated that the alleged commissions were actually legitimate payments. We presented council meeting minutes proving that the contracts were approved by majority. The defense experts questioned the methodology of the accounting analysis and highlighted errors in the prosecution's calculations. We also presented our client's financial statements proving the absence of unusual enrichment.",
      resolucion: "The Provincial Court issued judgment 202/2025 acquitting our client of all corruption charges. The court considered that the evidence was insufficient to prove the crimes and that the accusations were based on circumstantial evidence. The court emphasized that in corruption cases it is necessary to prove concrete benefits and criminal intent. The Public Prosecutor's Office appealed to the Supreme Court, where the case is currently pending.",
      marco_legal: "The case was judged under articles 432 and 428 of the Criminal Code on embezzlement and influence peddling. The Provincial Court applied the principle that corruption crimes require proof of concrete damage to the public administration and personal benefit of the accused. The court also applied the presumption of innocence and considered that mere irregularities in procedures are not sufficient for conviction."
    }
  },
  // Case 9 - ENVIRONMENTAL CRIME
  9: {
    nombre: "ENVIRONMENTAL CRIME",
    delito_principal: "Environmental contamination and illegal dumping",
    resultado: "Agreement with the Prosecutor's Office",
    contenido: {
      resumen: "A company was accused of environmental contamination after dumping toxic waste illegally. Our client, the company director, faced up to 4 years in prison. Through negotiation with the Prosecutor's Office, we achieved an agreement that avoided trial and reduced the penalties. The case demonstrated the effectiveness of negotiation strategies in environmental crimes.",
      hechos: "The environmental authorities detected illegal dumping of toxic waste in a protected area. The investigation revealed that the company had been dumping waste for months without authorization. Soil and water analyzes showed high levels of contamination. Our client was charged with environmental crimes under the Criminal Code. The case involved complex technical analysis and raised questions about corporate responsibility in environmental matters.",
      estrategia: "The defense recognized the company's responsibility but argued mitigating circumstances. We negotiated with the Prosecutor's Office to reduce the charges and penalties. We also committed to environmental restoration measures. The strategy included presenting expert reports on the contamination levels and demonstrating the company's collaboration with the authorities. We achieved an agreement that avoided trial and significantly reduced the penalties.",
      pruebas: "The evidence included environmental analysis reports, photographic evidence and witness statements. The defense did not dispute the facts but presented mitigating reports. We demonstrated that the company had already begun remediation measures. The agreement included commitments to environmental restoration and compensation to affected parties. The Prosecutor's Office accepted the agreement considering the collaboration and the remediation commitments.",
      resolucion: "The court approved the agreement between the defense and the Prosecutor's Office. Our client was sentenced to 1 year in prison (suspended) and a fine of 100,000 euros. The company committed to environmental remediation with a budget of 500,000 euros. The agreement avoided a lengthy trial and achieved a favorable outcome for our client. The case was closed without further appeals.",
      marco_legal: "The case was framed in article 325 of the Criminal Code on environmental contamination. The agreement applied the provisions of the Criminal Procedure Law on abbreviated procedure. The court considered the environmental restoration commitments and the company's collaboration as mitigating circumstances. The judgment emphasized the importance of environmental protection and corporate responsibility."
    }
  },
  // Case 10 - DOMESTIC VIOLENCE CASE
  10: {
    nombre: "DOMESTIC VIOLENCE CASE",
    delito_principal: "Gender violence and threats",
    resultado: "Acquittal due to lack of evidence",
    contenido: {
      resumen: "Our client was accused of gender violence and threats by his former partner. After a contentious trial, he was acquitted due to lack of evidence. The case highlighted the importance of evidence in domestic violence cases and the risks of false accusations.",
      hechos: "The case began after our client's former partner filed a complaint for threats and gender violence. According to the complaint, our client had threatened her during a discussion about child custody. The police investigation included restraining order and collection of evidence. Our client denied the accusations and maintained that the complaint was motivated by the divorce proceedings. The case involved psychological reports and witness statements.",
      estrategia: "The defense demonstrated that there was no evidence of threats or violence. We challenged the credibility of the complainant's statements and presented contradictory witness statements. We also argued that the complaint was filed in bad faith to obtain advantages in the divorce. The strategy included presenting our client's version of the facts and demonstrating the absence of prior violent behavior. We requested the dismissal of the case due to lack of evidence.",
      pruebas: "The evidence consisted of the complainant's statements, medical reports and witness statements. However, we demonstrated that the medical reports did not show injuries compatible with violence. The witnesses presented by the defense contradicted the complainant's version. We also presented text messages and calls proving that there were no threats. The court considered that the evidence was insufficient to prove the crimes.",
      resolucion: "The Provincial Court issued judgment 303/2025 acquitting our client of all charges. The court considered that there was no evidence of gender violence or threats and that the accusations were based solely on the complainant's statements. The court emphasized the importance of objective evidence in these cases. The acquittal was final and our client recovered all his rights.",
      marco_legal: "The case was judged under articles 173.2 and 171 of the Criminal Code on gender violence and threats. The court applied the principle that in domestic violence cases it is necessary to prove the facts beyond reasonable doubt. The judgment recalled that complaints alone are not sufficient for conviction and that contradictory evidence must be carefully evaluated."
    }
  },
  // Case 11 - TAX FRAUD
  11: {
    nombre: "TAX FRAUD",
    delito_principal: "Tax fraud and money laundering",
    resultado: "Dismissal after evidence practice",
    contenido: {
      resumen: "Our client was investigated for tax fraud after irregularities were detected in his company accounts. After practicing new evidence, the proceedings were dismissed. The case demonstrated the importance of requesting new diligences in complex economic cases.",
      hechos: "The Tax Agency detected irregularities in the accounts of our client's company. The investigation suggested that invoices had been falsified to reduce taxable income. The Prosecutor's Office charged our client with tax fraud under article 305 of the Criminal Code. Our client maintained that the irregularities were accounting errors, not fraud. The case involved complex financial analysis and raised questions about the limits between accounting errors and tax fraud.",
      estrategia: "The defense requested the practice of new expert diligences to clarify the accounting issues. We demonstrated that the alleged irregularities were actually accounting errors. We also argued that there was no intention to defraud. The strategy included presenting expert reports and demonstrating our client's good faith. We achieved the dismissal of the proceedings after the new evidence proved our innocence.",
      pruebas: "The initial evidence consisted of Tax Agency reports and accounting analysis. However, the new expert evidence demonstrated that the accounting treatment was correct according to commercial law. We presented invoices, contracts and accounting records proving the legitimacy of the operations. The experts confirmed that there were no false invoices but rather correct accounting practices. The court accepted our arguments and dismissed the proceedings.",
      resolucion: "The Investigating Court issued dismissal order 404/2025 after evaluating the new expert evidence. The court considered that there was no evidence of tax fraud and that the irregularities were accounting errors. The dismissal was confirmed by the Provincial Court. Our client was exonerated and the Tax Agency continued the administrative procedure separately.",
      marco_legal: "The case was framed in article 305 of the Criminal Code on tax fraud. The court applied the requirement that tax fraud requires intention to defraud and falsification of documents. The judgment emphasized that mere accounting irregularities are not sufficient for criminal conviction. The case established an important precedent on the distinction between accounting errors and tax fraud."
    }
  },
  // Case 12 - PROFESSIONAL NEGLIGENCE
  12: {
    nombre: "PROFESSIONAL NEGLIGENCE",
    delito_principal: "Professional negligence causing injury",
    resultado: "Acquittal by prescription",
    contenido: {
      resumen: "A doctor was accused of professional negligence after a surgical intervention. Our client faced up to 3 years in prison. The proceedings were dismissed due to prescription of the crime. The case highlighted the importance of prescription terms in medical negligence cases.",
      hechos: "The patient suffered complications after surgery and accused our client of negligence. The case was investigated years after the intervention. The Prosecutor's Office charged our client with professional negligence under article 196 of the Criminal Code. Our client maintained that he had followed all medical protocols. The case involved medical expert reports and raised questions about the prescription of medical negligence crimes.",
      estrategia: "The defense argued that the crime was prescribed according to the Criminal Code. We demonstrated that more than 5 years had passed since the intervention. We also presented medical expert reports proving that our client had followed correct procedures. The strategy focused on the prescription issue as the main defense argument. We achieved the dismissal of the proceedings without needing to enter into the merits of the case.",
      pruebas: "The evidence included medical reports and expert opinions. The defense presented reports from independent experts confirming that the procedures followed were correct. We also demonstrated the prescription of the crime. The court did not need to evaluate the medical aspects as the prescription was clear. The proceedings were dismissed based on procedural grounds.",
      resolucion: "The Investigating Court issued dismissal order 505/2025 declaring the prescription of the crime. The court considered that more than 5 years had passed since the facts and that the crime was prescribed. The dismissal was final and our client was exonerated. The patient could continue with the civil procedure if desired.",
      marco_legal: "The case was framed in article 196 of the Criminal Code on professional negligence. The court applied the prescription terms established in article 131 of the Criminal Code. The judgment emphasized that prescription is a substantive right that extinguishes criminal responsibility. The case established an important precedent on prescription in medical negligence cases."
    }
  },
  // Case 13 - YOUTH CRIME
  13: {
    nombre: "YOUTH CRIME",
    delito_principal: "Theft and criminal group",
    resultado: "Dismissal with educational measures",
    contenido: {
      resumen: "A group of minors was accused of thefts in a neighborhood. Our client, a 17-year-old minor, faced juvenile proceedings. Through a defense strategy focused on rehabilitation, we achieved the dismissal with educational measures. The case demonstrated the importance of juvenile justice approach.",
      hechos: "The minors were accused of a series of thefts in stores and vehicles in a neighborhood. The police investigation identified our client as part of the group. The Juvenile Prosecutor's Office charged him with theft crimes. Our client recognized his participation but alleged peer pressure. The case involved psychological reports and family situation analysis. The objective was to apply adequate educational measures.",
      estrategia: "The defense focused on our client's young age and lack of criminal record. We presented psychological reports indicating good rehabilitation prognosis. We also demonstrated family difficulties that influenced the behavior. The strategy included negotiating with the Prosecutor's Office for non-punitive measures. We achieved educational measures instead of punishment.",
      pruebas: "The evidence included police reports, witness statements and the minors' statements. The defense presented psychological and social reports. The experts indicated that our client was influenced by the group and had good rehabilitation capacity. The reports emphasized the importance of educational measures over punishment. The court accepted our arguments and applied educational measures.",
      resolucion: "The Juvenile Court issued resolution 606/2025 dismissing the proceedings with educational measures. Our client was obliged to attend socio-educational programs and community service. The measures were completed successfully and our client did not reoffend. The case was closed positively. The outcome demonstrated the effectiveness of the juvenile justice system.",
      marco_legal: "The case was judged under the Juvenile Criminal Responsibility Law. The court applied the principle of proportionality and the best interests of the minor. The judgment emphasized that for minors, rehabilitation and education prevail over punishment. The case established an important precedent on the treatment of youth crime."
    }
  },
  // Case 14 - IMMIGRATION CRIME
  14: {
    nombre: "IMMIGRATION CRIME",
    delito_principal: "Irregular immigration and trafficking",
    resultado: "Acquittal due to lack of evidence",
    contenido: {
      resumen: "Our client was accused of facilitating irregular immigration. After a trial, he was acquitted due to lack of evidence. The case highlighted the difficulties of proving immigration crimes and the importance of due process.",
      hechos: "The police investigation detected a network dedicated to facilitating irregular immigration. Our client was accused of transporting immigrants illegally. The Prosecutor's Office charged him with immigration crimes under the Criminal Code. Our client maintained that he was only transporting acquaintances. The case involved border controls and witness statements.",
      estrategia: "The defense demonstrated that there was no evidence of trafficking or profit motive. We challenged the witness statements and presented alternative explanations. We also argued violation of fundamental rights during the investigation. The strategy included questioning the police methods and demonstrating our client's lack of criminal intent. We achieved acquittal after proving the absence of crime.",
      pruebas: "The evidence consisted of police reports and witness statements. However, we demonstrated that the witnesses were not credible and that their statements were contradictory. We presented documents proving that the transported persons were acquaintances. The defense experts questioned the investigation methods. The court considered that the evidence was insufficient.",
      resolucion: "The Provincial Court issued judgment 707/2025 acquitting our client of all charges. The court considered that there was no evidence of immigration crimes and that the accusations were based on mere suspicions. The acquittal was final and our client recovered his freedom. The case was closed without further proceedings.",
      marco_legal: "The case was framed in articles 318 bis and 177 bis of the Criminal Code on immigration crimes. The court applied strict evidence requirements and considered that mere transportation is not sufficient for conviction. The judgment emphasized the importance of proving profit motive and organized structure in immigration crimes."
    }
  },
  // Case 15 - INTELLECTUAL PROPERTY
  15: {
    nombre: "INTELLECTUAL PROPERTY",
    delito_principal: "Trademark infringement and unfair competition",
    resultado: "Dismissal after negotiation",
    contenido: {
      resumen: "Our client was accused of trademark infringement. Through negotiation with the complaining company, we achieved the dismissal of the proceedings. The case demonstrated the effectiveness of negotiation in intellectual property cases.",
      hechos: "A company accused our client of using similar trademarks in his products. The investigation suggested unfair competition. The Prosecutor's Office charged our client with intellectual property crimes. Our client maintained that the similarities were coincidental. The case involved trademark analysis and market studies.",
      estrategia: "The defense negotiated with the complaining company to reach an agreement. We demonstrated that there was no intention to confuse consumers. We also presented trademark registration documents. The strategy included proposing license agreements and compensation. We achieved the dismissal of the proceedings through negotiation.",
      pruebas: "The evidence included trademark analysis and market studies. The defense presented expert reports on trademark law. We demonstrated that the marks were sufficiently different. The agreement included commitments to modify the trademarks and compensation payments. The complaining company withdrew the complaint.",
      resolucion: "The Investigating Court approved the agreement and dismissed the proceedings. Our client committed to modify his trademarks and pay compensation. The case was closed without trial. The outcome was favorable for both parties. The dismissal avoided a lengthy and costly process.",
      marco_legal: "The case was framed in article 273 and following of the Criminal Code on intellectual property crimes. The agreement applied the provisions on abbreviated procedure. The court considered the agreement as a manifestation of restorative justice. The judgment emphasized the importance of negotiation in commercial disputes."
    }
  },
  // Case 16 - SPORTS DOPING
  16: {
    nombre: "SPORTS DOPING",
    delito_principal: "Administration of prohibited substances",
    resultado: "Acquittal due to lack of intent",
    contenido: {
      resumen: "An athlete was accused of doping in a competition. Our client faced disqualification and criminal charges. Through a defense based on lack of intent, we achieved acquittal. The case highlighted the complexities of doping cases in sports law.",
      hechos: "The anti-doping control detected prohibited substances in our client's sample. The investigation suggested intentional doping. The sports federation and Prosecutor's Office charged our client with doping crimes. Our client maintained that the substances entered his body unintentionally. The case involved complex scientific analysis.",
      estrategia: "The defense demonstrated that there was no intention to dope. We presented medical reports proving contamination through supplements. We also argued violation of due process in the anti-doping procedure. The strategy included questioning the analysis methods and presenting alternative explanations. We achieved acquittal after proving the lack of intent.",
      pruebas: "The evidence included anti-doping control results and scientific analysis. The defense presented expert reports on supplement contamination. We demonstrated that the substances came from contaminated products. The experts questioned the chain of custody of the sample. The court accepted our arguments on lack of intent.",
      resolucion: "The Provincial Court issued judgment 909/2025 acquitting our client of doping charges. The court considered that there was no intention to use prohibited substances. The acquittal was final and our client could continue his sports career. The case was closed with a favorable outcome.",
      marco_legal: "The case was framed in article 361 of the Criminal Code on doping crimes. The court applied the requirement of intention for doping crimes. The judgment emphasized that unintentional intake is not punishable. The case established an important precedent on the burden of proof in doping cases."
    }
  },
  // Case 17 - BANK FRAUD
  17: {
    nombre: "BANK FRAUD",
    delito_principal: "Bank fraud and falsification",
    resultado: "Conditional suspension of proceedings",
    contenido: {
      resumen: "Our client was accused of bank fraud through falsified documents. Through a defense strategy, we achieved conditional suspension of proceedings. The case demonstrated the possibilities of alternative resolutions in economic crimes.",
      hechos: "The bank detected irregularities in loan applications. The investigation suggested falsification of documents. The Prosecutor's Office charged our client with bank fraud. Our client maintained that the irregularities were errors. The case involved financial analysis and document examination.",
      estrategia: "The defense negotiated conditional suspension of proceedings. We committed to economic reparations and compliance with conditions. We also demonstrated partial recognition of responsibility. The strategy included presenting reparation proposals and compliance guarantees. We achieved suspension of proceedings with conditions.",
      pruebas: "The evidence included financial documents and bank reports. The defense presented reparation agreements. We demonstrated commitment to compensate damages. The conditions included payment deadlines and compliance guarantees. The Prosecutor's Office accepted the agreement.",
      resolucion: "The Investigating Court issued resolution 1010/2025 suspending proceedings conditionally. Our client committed to pay reparations and comply with conditions. If fulfilled, the proceedings would be dismissed definitively. The outcome avoided trial and achieved a favorable resolution. The case demonstrated the effectiveness of alternative resolutions.",
      marco_legal: "The case was framed in article 248 of the Criminal Code on bank fraud. The resolution applied article 191 of the Criminal Procedure Law on conditional suspension. The court considered the reparation commitments and compliance guarantees. The judgment emphasized the importance of restorative justice in economic crimes."
    }
  },
  // Case 18 - CYBERBULLYING
  18: {
    nombre: "CYBERBULLYING",
    delito_principal: "Harassment and cyberbullying",
    resultado: "Acquittal due to freedom of expression",
    contenido: {
      resumen: "Our client was accused of cyberbullying through social media posts. Through a defense based on freedom of expression, we achieved acquittal. The case highlighted the balance between freedom of expression and protection against harassment.",
      hechos: "The victim accused our client of harassment through insulting posts on social media. The investigation collected screenshots and witness statements. The Prosecutor's Office charged our client with harassment crimes. Our client maintained that his posts were opinions protected by freedom of expression. The case involved analysis of social media content.",
      estrategia: "The defense argued that the posts were protected by freedom of expression. We demonstrated that they were opinions, not harassment. We also challenged the victim's credibility. The strategy included presenting constitutional doctrine and similar cases. We achieved acquittal after proving that the expressions were protected.",
      pruebas: "The evidence included social media posts and victim statements. The defense presented expert reports on freedom of expression. We demonstrated that the posts were opinions within public debate. The experts analyzed the context and intention. The court considered that the expressions were protected by the Constitution.",
      resolucion: "The Provincial Court issued judgment 1111/2025 acquitting our client of harassment charges. The court considered that the posts were protected by freedom of expression. The acquittal was final and our client could continue his online activity. The case established an important precedent on social media freedom of expression.",
      marco_legal: "The case was framed in article 172 of the Criminal Code on harassment. The court applied Constitutional Court doctrine on freedom of expression. The judgment emphasized that not all offensive expressions are punishable. The case highlighted the importance of the context in evaluating online expressions."
    }
  },
  // Case 19 - TRAFFIC ACCIDENT
  19: {
    nombre: "TRAFFIC ACCIDENT",
    delito_principal: "Reckless driving causing death",
    resultado: "Sentence reduction",
    contenido: {
      resumen: "Our client caused a fatal traffic accident. Through a defense strategy based on mitigating circumstances, we achieved sentence reduction. The case demonstrated the importance of mitigation in traffic crimes.",
      hechos: "Our client caused an accident that resulted in one death. The investigation determined reckless driving. The Prosecutor's Office requested 8 years in prison. Our client recognized the facts but alleged mitigating circumstances. The case involved accident reconstruction and psychological reports.",
      estrategia: "The defense presented mitigating circumstances such as lack of prior record and collaboration. We also demonstrated psychological impact on our client. The strategy included negotiating with the victim's family for forgiveness. We achieved significant sentence reduction through mitigation.",
      pruebas: "The evidence included accident reconstruction and witness statements. The defense presented psychological reports and character references. We demonstrated our client's collaboration with justice. The mitigation was accepted by the court. The sentence was reduced considerably.",
      resolucion: "The Provincial Court issued judgment 1212/2025 condemning our client to 4 years in prison. The court applied mitigating circumstances and reduced the sentence. The judgment included compensation to the victim's family. Our client accepted the sentence and began serving it. The outcome was the best possible given the circumstances.",
      marco_legal: "The case was framed in article 142 of the Criminal Code on traffic crimes. The court applied mitigating circumstances from article 21. The judgment emphasized the importance of collaboration and lack of prior record in sentence reduction. The case demonstrated the application of mitigation in traffic crimes."
    }
  },
  // Case 20 - BUSINESS CRIME
  20: {
    nombre: "BUSINESS CRIME",
    delito_principal: "Corporate fraud and false accounting",
    resultado: "Agreement with reduced penalties",
    contenido: {
      resumen: "Our client was accused of corporate fraud in his company. Through negotiation with the Prosecutor's Office, we achieved reduced penalties. The case demonstrated the effectiveness of negotiation in corporate crimes.",
      hechos: "The company audit detected accounting irregularities. The investigation suggested intentional fraud. The Prosecutor's Office charged our client with corporate crimes. Our client maintained that the irregularities were errors. The case involved complex financial analysis.",
      estrategia: "The defense negotiated with the Prosecutor's Office for reduced penalties. We recognized partial responsibility and committed to reparations. We also demonstrated lack of personal enrichment. The strategy included presenting reparation plans and compliance guarantees. We achieved significantly reduced penalties.",
      pruebas: "The evidence included accounting reports and financial analysis. The defense presented reparation agreements and compliance plans. We demonstrated commitment to correct irregularities. The agreement included penalty reduction and probation conditions. The Prosecutor's Office accepted the agreement.",
      resolucion: "The court approved the agreement with reduced penalties. Our client was sentenced to 2 years in prison (suspended) and economic penalties. The company committed to corrective measures. The agreement avoided trial and achieved a favorable outcome. The case was resolved efficiently.",                  
      marco_legal: "The case was framed in article 290 of the Criminal Code on corporate fraud. The agreement applied abbreviated procedure provisions. The court considered reparation commitments and collaboration. The judgment emphasized restorative justice in corporate cases."                                         
    }
  },
  // Case 21 - ROBBERY WITH VIOLENCE - DISMISSAL POZUELO
  21: {
    nombre: "ROBBERY WITH VIOLENCE CASE - DISMISSAL POZUELO",
    delito_principal: "Robbery with violence and intimidation",
    resultado: "Provisional dismissal and archiving",
    contenido: {
      resumen: "Two individuals were investigated for alleged robbery with violence in Pozuelo de Alarcón following a complaint by Diego García Rico Rodríguez, who stated that his chain had been snatched from behind. The Investigating Court No. 3 of Pozuelo de Alarcón ordered the provisional dismissal and archiving of proceedings as the perpetrator could not be reliably identified. The defense, led by attorney Diego Cardona Valero, successfully demonstrated insufficient evidence to support the accusation.",
      hechos: "On November 18, 2025, the Investigating Court No. 3 of Pozuelo de Alarcón issued Order No. 692/2025 in preliminary proceedings 469/2023. The investigated facts referred to an alleged robbery with violence that occurred in Pozuelo de Alarcón, where complainant Diego García Rico Rodríguez stated that his gold chain had been snatched. Two persons were initially investigated: Hamza Beggar Ibnrouin (defended by Diego Cardona Valero from STANS Abogados) and Marouane Bouali (defended by Luis Auxilio Torres Martínez). The proceedings were initiated pursuant to a police report from the Pozuelo de Alarcón Local Police Station in 2023. During the investigation, statements were taken from the complainant and an eyewitness. The complainant stated in court that he did not see who snatched the chain, that the pull was from behind and that he doubted he could recognize the perpetrator. The witness declared that, although she knew the investigated persons by sight, she did not see the moment when the necklace was taken from the complainant and expressly confirmed that \"she did not see any of them take the necklace from Diego\". These declarations were determinant for the outcome of the proceedings.",
      estrategia: "The defense strategy focused on challenging the identification of the robbery perpetrator and the sufficiency of incriminating evidence. The absence of evidentiary elements unequivocally linking the investigated persons to the reported facts was highlighted. The defense emphasized the significance of the declarations by the complainant himself and the eyewitness, who could not reliably identify the perpetrators of the robbery. It was argued that mere presence in the vicinity of the crime scene or the witness's prior knowledge of the investigated persons did not, by themselves, constitute sufficient indications of participation in the crime. The defense invoked the principle of presumption of innocence and requested dismissal of proceedings pursuant to article 641.2 of the Criminal Procedure Act, as the perpetrator of the crime could not be identified. It was insisted that, according to consolidated jurisprudence, when the proceedings practiced do not allow determining who is responsible for the facts, provisional archiving of proceedings is appropriate. The strategy was successful, as the court upheld the defense's arguments and ordered the dismissal.",
      pruebas: "The fundamental evidence in this proceeding consisted of declarations made in court. On one hand, the declaration of complainant Diego García Rico Rodríguez, who expressly acknowledged that he did not see who snatched the chain, that the pull was from behind and that he doubted he could recognize the perpetrator. This declaration was determinant, as it evidenced the impossibility of positive identification. On the other hand, the declaration of the eyewitness, who stated that, despite knowing the investigated persons by sight, she did not witness the moment of the robbery and categorically confirmed that she did not see any of them take the necklace from the complainant. The police report from the Pozuelo de Alarcón Local Police Station, which initiated the proceedings, did not provide additional elements allowing conclusive linking of the investigated persons to the facts. The absence of other incriminating evidence (additional witnesses, video surveillance recordings, seized objects or expert evidence) reinforced the defense's position. In conclusion, the result of the proceedings practiced did not sufficiently prove the perpetration of the crime nor the identification of the perpetrator, which motivated the dismissal.",
      resolucion: "Through Order No. 692/2025 dated November 18, 2025, magistrate-judge M. Carmen Neira Formigo of the Investigating Court No. 3 of Pozuelo de Alarcón ordered the provisional dismissal and archiving of preliminary proceedings 469/2023. The resolution was based on articles 779.1.1º and 641.1º of the Criminal Procedure Act, considering that the perpetration of the crime was not duly justified by what was done. The court especially valued the declarations of the complainant and witness, who could not identify the perpetrator of the robbery. In application of article 641.2 of the LECrim, dismissal was ordered as the perpetrator of the facts could not be identified. As a consequence of the dismissal, any precautionary measures previously imposed on the investigated persons were rendered null and void, with both being completely free of charges. The resolution was notified to the Public Prosecutor's Office, other parties appearing and the victim of the crime in the manner provided in article 636 of the LECrim. An appeal for reconsideration and subsidiary appeal or direct appeal could be filed against the order. The result was fully favorable for our client, who was freed from all criminal charges.",
      marco_legal: "The dismissal was ordered pursuant to articles 779.1.1º, 641.1º and 641.2º of the Criminal Procedure Act. Article 641.2º LECrim establishes that provisional dismissal shall proceed when \"the perpetration of the crime that gave rise to the formation of the case is not duly justified\". In this case, the impossibility of reliably identifying the perpetrator of the robbery determined the application of said provision. The resolution is also based on the constitutional principle of presumption of innocence (art. 24.2 of the Spanish Constitution) and the consolidated jurisprudence of the Supreme Court, which requires that incriminating evidence be sufficient, lawful and obtained with all procedural guarantees. The defense also invoked the right to effective judicial protection and the \"in dubio pro reo\" principle, which requires resolving evidentiary doubts in favor of the investigated person. The investigated crime was that provided in articles 237 and 242 of the Criminal Code (robbery with violence or intimidation of persons), which is punished with prison sentences of two to five years. However, insufficient evidence prevented the proceedings from prospering."
    }
  },
  // Case 22 - CLUB ESPEJOS AZULES
  22: {
    nombre: "CLUB ESPEJOS AZULES CASE - DISMISSAL",
    delito_principal: "Crime against public health (cannabis association)",
    resultado: "Provisional dismissal and archiving of the case",
    contenido: {
      resumen: "At STANS ABOGADOS we achieved the provisional dismissal and archiving of Preliminary Proceedings 2071/2025 of the Investigating Court No. 53 of Madrid. The Espejos Azules Club, a cannabis consumers' association, was being investigated for an alleged crime against public health. Thanks to the specialized work of our attorneys Rubén Vaquero Arribas and Diego Cardona Valero, the court concluded that there was no evidence of criminal offense, archiving the case pursuant to article 641.1º of the Criminal Procedure Act.",
      hechos: "During 2024, the National Police and Madrid Municipal Police carried out an investigation into three establishments related to the cultivation and supply of cannabis in the Ciudad Lineal district. One of these premises was the Espejos Azules Club, which operated as a consumers' association. On June 11, 2024, entry and search was carried out at the three premises, seizing almost one kilogram of hashish, over one kilogram of marijuana, seeds, and other related products. Our attorneys were present during the search, ensuring respect for the rights of those investigated. The club's managers were charged with an alleged crime against public health. The investigation continued for months until, on November 27, 2025, the Investigating Court No. 53 of Madrid issued an order of provisional dismissal.",
      estrategia: "The defense strategy focused on demonstrating that the activity of the Espejos Azules Club was lawful, internal and typical of shared consumption, dismantling any suspicion of drug trafficking. We argued the existence of a valid associative structure, with registered bylaws, absence of profit motive, strict control of members and complete documentation of deliveries. It was proven that all cannabis was intended exclusively for consumption by members, without advertising or external recruitment. Our intervention was decisive from the moment of entry and search, where we ensured that all procedural rights were respected, avoided incorrect police assessments and mediated directly with investigators. We presented legal reports on the lawfulness of cannabis associations according to Supreme Court jurisprudence and documentation that accredited the internal operation of the club.",
      pruebas: "The main evidence consisted of: the club's internal documentation (bylaws, member registration books, assembly minutes, delivery records), expert reports on the seized quantities that demonstrated they were proportional to the number of members, absence of evidence of advertising or external recruitment, declarations by members who confirmed the closed and private nature of the club, and Supreme Court jurisprudence that supports the model of consumer associations. There was no evidence of sales to third parties, profit motive, or trafficking operations. The Public Prosecutor's Office report of November 13, 2025 was key, concluding that there was insufficient evidence of a crime.",
      resolucion: "On November 27, 2025, the Investigating Court No. 53 of Madrid issued an order of provisional dismissal and archiving of the case. The court followed the position of the Public Prosecutor's Office and concluded that there was no evidence that the reported facts constituted a criminal offense. The resolution was based on articles 641.1º and 780 of the Criminal Procedure Act. An appeal could be filed against this resolution within five days, but no party filed it, leaving the archiving final. This result confirms STANS ABOGADOS' leadership in the criminal defense of cannabis associations and consumer clubs in Madrid.",
      marco_legal: "The case is framed in article 368 of the Criminal Code which typifies the crime against public health for drug trafficking. Supreme Court jurisprudence (among others, STS 484/2015 and STS 1377/2015) has established that cannabis consumer associations do not constitute a crime when: (1) they have a valid and transparent associative structure, (2) consumption is shared and closed to members, (3) there is no profit motive, (4) there is no external recruitment or advertising, and (5) the proportionality of quantities is controlled. The provisional dismissal was issued pursuant to article 641.1º of the Criminal Procedure Act due to insufficient evidence of criminality. This case demonstrates the importance of having specialized legal advice from the initial stages of police investigation."
    }
  },
  // Case 23 - CEUTA ANTI-TERRORISM OPERATION
  23: {
    nombre: "CEUTA ANTI-TERRORISM OPERATION",
    delito_principal: "Alleged jihadist terrorism offense",
    resultado: "Provisional release without bail",
    contenido: {
      resumen: "In the context of a joint Spanish-Moroccan anti-terrorism operation carried out in November 2024, nine persons were arrested across Ceuta, Madrid, Ibiza, Tetouan and Fnideq for their alleged involvement with an ISIS-loyal terrorist cell in the Sahel. Our client was among those detained in Ceuta and was remanded in pre-trial custody without bail by order of the National High Court. After more than one year in preventive detention, the Central Investigating Court No. 1 of the National High Court, upon the Public Prosecutor's request, issued an order on January 30, 2026 granting provisional release without bail subject to precautionary measures. The case remains under investigation.",
      hechos: "On November 22, 2024, the General Information Commissioner's Office of the National Police, in coordination with the Provincial Brigade of Ceuta and the Moroccan security services (Central Office of Judicial Investigations of the General Directorate of Territorial Surveillance), executed a simultaneous anti-terrorism operation in Spain and Morocco. In Ceuta, searches were carried out in the Vicedo Martínez and Príncipe Alfonso neighbourhoods, with at least four persons arrested in the city. The operation extended to Madrid, Ibiza, Tetouan and Fnideq, reaching a total of nine arrests. According to the authorities, the suspects formed part of an ISIS-loyal cell in the Sahel region. Edged weapons and electronic devices were seized during the home searches and submitted for digital forensic analysis. The National High Court ordered pre-trial custody without bail for the detainees.",
      estrategia: "The defense filed appeals for reconsideration and cassation arguing the absence of conclusive evidence against our client. The defendant's deep roots in Ceuta, where he resides with his family, were emphasized, as well as his personal situation of vulnerability. It was argued that no specific criminal conduct had been identified. The strategy included requesting a review of the pre-trial custody measure pursuant to article 503 of the Criminal Procedure Act, ultimately leading the Public Prosecutor itself to issue a favourable report recommending release with alternative measures.",
      pruebas: "The proceedings include reports from the General Information Commissioner's Office of the National Police. Edged weapons and electronic devices subjected to digital forensic analysis were seized during home searches. The police investigations pointed to the alleged dissemination of content through social media and face-to-face meetings among the suspects. As this is an ongoing case, detailed information about the evidence is subject to the secrecy of the proceedings.",
      resolucion: "By order of January 30, 2026, the Central Investigating Court No. 1 of the National High Court decreed the provisional release without bail of the defendant, subject to precautionary measures regarding his liberty. The resolution was issued following a favourable report by the Public Prosecutor, who requested the release of the defendant with alternative measures to ensure his availability for the proceedings. The court based its decision on article 503(1) of the Criminal Procedure Act, which regulates the requirements for pre-trial custody. The case remains under investigation before the Central Investigating Court No. 1.",
      marco_legal: "Article 503 of the Criminal Procedure Act applies, regulating the requirements for pre-trial custody and establishing the conditions that must be met for its adoption and maintenance. The same provision grounds the possibility of replacing pre-trial custody with provisional release subject to precautionary measures when the circumstances that motivated preventive detention have changed. The investigation falls within the scope of terrorism offenses regulated in articles 571 et seq. of the Criminal Code."
    }
  },
  24: {
    nombre: "ACQUITTAL FOR SEXUAL ASSAULT – VILLARRUBIA DE LOS OJOS",
    delito_principal: "Sexual assault offense (art. 178.1.2 Criminal Code)",
    resultado: "Acquittal",
    contenido: {
      resumen: "At STANS ABOGADOS we secured the acquittal of our client in Summary Proceedings 552/2025 before the Criminal Section of the Court of First Instance of Ciudad Real. The Public Prosecutor charged our client with a sexual assault offense under article 178.1.2 of the Criminal Code and sought a sentence of 4 years' imprisonment, substitution of the sentence by deportation with an 8-year entry ban, a 500-metre restraining order for 7 years, supervised release with a sexual education programme for 4 years, and disqualification from activities involving minors for 7 years. By Judgment 00142/2026 of March 9, 2026, the Court fully acquitted our client, concluding that the complainant's testimony did not constitute sufficient evidence for a conviction, applying the principle of in dubio pro reo.",
      hechos: "The facts under investigation related to an alleged sexual assault on December 7, 2024, at approximately 8:30 PM, at premises on Avenida de la Virgen No. 59 in Villarrubia de los Ojos (Ciudad Real). According to the complaint, the defendant, taking advantage of the complainant's husband having left the house, pushed her against the wall, grabbed her by the neck causing scratches, touched her intimate areas over her clothing (chest and vaginal area), attempted to kiss her and caused her to fall to the ground. Allegedly, when the husband returned, the defendant took refuge in his room. The proceedings were initiated by police report and investigated by Investigating Court No. 2 of Daimiel (Preliminary Proceedings 479/2024, Summary Proceedings 8/2025). Our client denied the facts at all times.",
      estrategia: "The defense strategy focused on rigorously analysing the complainant's testimony according to the Supreme Court's jurisprudential criteria for assessing the victim's testimony as sole prosecution evidence. The three requirements established by case law were challenged: persistence in the accusation, credibility supported by peripheral corroboration, and absence of subjective grounds for disbelief. It was highlighted that the complainant herself filed a statement at the oral hearing requesting the withdrawal of the complaint, undermining persistence in the accusation. The total absence of objective peripheral corroboration was demonstrated, and the existence of spurious motives arising from a labour dispute over unpaid wages was established.",
      pruebas: "The evidence examined at the oral hearing was decisive for the acquittal. The complainant's testimony at trial, where she filed a statement requesting the withdrawal of the complaint. The husband's testimony, which contradicted the complainant's version by stating he found her unconscious. The testimony of Civil Guard officer with badge number P07278Q, who stated the complainant showed no apparent injuries when he attended the house, and that the husband told him he learned of the events through a phone call from his wife (contradicting the version that he heard her calling for help from the street). The testimony of witness Yahyla Bnsbah, who described a prior labour dispute over unpaid wages, heard the husband tell his wife to throw herself on the floor, and stated the complainant scratched herself. The video the husband claimed to have recorded was never submitted to the proceedings.",
      resolucion: "By Judgment 00142/2026 of March 9, 2026, Judge D. Amalio de Juan Casero fully acquitted our client of the sexual assault charge, ordering the costs to be borne by the State. The Court applied the principle of in dubio pro reo, concluding that persistence in the accusation was lacking, no peripheral corroboration existed, and spurious motives were present. The restraining order and monthly court attendance requirement were lifted. The judgment is not yet final and may be appealed before the Provincial Court of Ciudad Real.",
      marco_legal: "The sexual assault offense is defined in article 178.1.2 of the Criminal Code. The assessment of evidence was carried out pursuant to articles 741 et seq. of the Criminal Procedure Act, applying the Supreme Court's jurisprudential criteria for the victim's testimony as sole prosecution evidence (STS 28/09/1988, 26/05/1992, 05/06/1992, 08/11/1994, 27/04/1995, 11/10/1995, 03/04/1996, 15/04/1996, 21/06/2000): absence of subjective grounds for disbelief, credibility with peripheral corroboration, and persistence in the accusation. The principle of in dubio pro reo and the presumption of innocence (art. 24.2 Spanish Constitution) were applied. Costs were ordered ex officio under article 240.2 of the Criminal Procedure Act."
    }
  }
};
