// Traducciones de casos en español
export const casesES = {
  // Caso 1 - QUEQUE ABOGADOS CRISTIANOS SOBRESEIMIENTO
  1: {
    nombre: "CASO- QUEQUE ABOGADOS CRISTIANOS SOBRESEIMIENTO",
    delito_principal: "Delito de odio y contra los sentimientos religiosos",
    resultado: "La Audiencia Provincial decreta el Sobreseimiento",
    contenido: {
      resumen: "La asociación ultracatólica Abogados Cristianos interpuso querella contra el humorista Héctor de Miguel (artísticamente \"Quequé\") por supuestas expresiones de odio vertidas en su programa Hora Veintipico. El Juzgado de Instrucción nº 38 de Madrid procesó al cómico por un presunto delito de odio y contra los sentimientos religiosos. Tanto la defensa como el Ministerio Fiscal recurrieron la decisión y, mediante Auto nº 379/2025 de 30 de abril de 2025, la Sección 30 de la Audiencia Provincial de Madrid estimó ambos recursos y ordenó el sobreseimiento libre de las actuaciones al considerar que las manifestaciones se encontraban amparadas por la libertad de expresión y de creación artística.",
      hechos: "El 27 de junio de 2024, durante el programa radiofónico y de humor Hora Veintipico de la Cadena SER, Héctor de Miguel bromeó con \"llenar de dinamita la cruz del Valle de los Caídos\" y arrojar las piedras resultantes contra sacerdotes pederastas. La asociación Abogados Cristianos presentó una querella y el Juzgado de Instrucción nº 38 admitió a trámite la acusación y acordó la continuación por el trámite del procedimiento abreviado por un posible delito de odio. La acusación sostuvo que las expresiones atribuibles al investigado no eran una mera hipérbole sino que incitaban a la hostilidad contra la religión católica. Frente a esa postura, la defensa alegó que se trataba de un ejercicio satírico protegido por el artículo 20 de la Constitución. Tras la incoación, tanto el Ministerio Fiscal como la representación de Héctor de Miguel interpusieron recurso de apelación contra el auto que le había procesado. La Audiencia Provincial de Madrid, Sección 30, examinó el contexto y el tono humorístico de las manifestaciones y concluyó que no existía incitación al odio ni hostilidad real. Por ello revocó la decisión instructora y ordenó el sobreseimiento libre de la causa.",
      estrategia: "La estrategia se centró en resaltar el carácter satírico y artístico de las expresiones denunciadas, invocando la protección constitucional de la libertad de expresión y de creación (art. 20 de la Constitución Española). La defensa argumentó que el humor político, incluso cuando resulta provocador u ofensivo, forma parte del debate público y no puede castigarse penalmente sin afectar al pluralismo. Se impugnó la interpretación expansiva del delito de odio (art. 510 CP) y se recordaron los límites exigidos por la jurisprudencia: debe existir una incitación real y grave a la hostilidad o violencia contra un colectivo, circunstancia inexistente en el caso. Además se reprochó al querellante utilizar el proceso penal para coartar la crítica y se sostuvo la falta de legitimación de una asociación privada para defender sentimientos religiosos ajenos. La defensa contó con el respaldo del Ministerio Fiscal, que también recurrió el procesamiento.",
      pruebas: "Las pruebas se limitaron a la grabación del programa de radio en el que se pronunciaron las frases, así como a las transcripciones aportadas por la querellante. No existían testigos que acreditasen un clima hostil posterior ni actos de violencia o discriminación. En el recurso se destacó la inexistencia de daño o riesgo concreto y la ausencia de seguimiento de las palabras en los días posteriores. La defensa aportó jurisprudencia constitucional y europea sobre libertad de expresión y precedentes en los que se archivaron denuncias basadas en discursos humorísticos. Finalmente, el auto apelado, junto con el recurso del Ministerio Fiscal y el de la defensa, fueron valorados por la Audiencia Provincial.",
      resolucion: "La Audiencia Provincial de Madrid (Sección 30) dictó el Auto nº 379/2025 de 30 de abril de 2025 en el que estimó los recursos de apelación interpuestos por el Ministerio Fiscal y la representación de Héctor de Miguel. Revocó el auto del Juzgado de Instrucción nº 38 de Madrid de 23 de enero de 2025 y, conforme al artículo 637.1 de la Ley de Enjuiciamiento Criminal, decretó el sobreseimiento libre de la causa. La Sala entendió que las manifestaciones satíricas no constituyen delito de odio ni fomentan la hostilidad contra los católicos. Contra esta resolución no cabía recurso. El resultado fue plenamente favorable para el cliente, que quedó liberado de cualquier imputación.",
      marco_legal: "El caso giró en torno al equilibrio entre la libertad de expresión y creación artística (art. 20 CE) y los límites del delito de odio tipificado en el artículo 510 del Código Penal. La Audiencia Provincial subrayó que, para apreciar el delito de odio, se exige una incitación real y directa a la violencia o discriminación contra un colectivo. En ausencia de tal requisito y ante el contexto humorístico, procede el sobreseimiento libre con apoyo en el artículo 637.1 LECrim. La resolución también reproduce doctrina constitucional que protege expresiones satíricas que, aunque puedan resultar ofensivas, forman parte del debate democrático y no sobrepasan los límites del derecho penal."
    }
  },
  // Caso 2 - NORDIN WORKOUT
  2: {
    nombre: "CASO NORDIN WORKOUT",
    delito_principal: "Terrorismo de índole yihadista (autoadoctrinamiento)",
    resultado: "Auto de Sobreseimiento",
    contenido: {
      resumen: "La Policía Nacional investigó a un influencer del mundo del fitness conocido como Nordin Workout por supuesto autoadoctrinamiento yihadista y captación online. La investigación se inició por publicaciones en redes sociales donde mezclaba contenido deportivo con referencias religiosas que las autoridades interpretaron como potencialmente radicales. Tras registros domiciliarios y análisis de dispositivos, no se encontraron pruebas de planificación de atentados ni pertenencia a células terroristas. El Juzgado Central de Instrucción nº 2 de la Audiencia Nacional dictó auto de sobreseimiento al no apreciar indicios suficientes de delito de terrorismo.",
      hechos: "En marzo de 2025, la Comisaría General de Información de la Policía Nacional inició una investigación sobre el influencer conocido como Nordin Workout tras detectar publicaciones en Instagram y TikTok que combinaban rutinas de ejercicio con mensajes religiosos islámicos. Las autoridades interpretaron que algunos contenidos podrían constituir indicios de radicalización yihadista, especialmente vídeos donde hablaba de \"preparación física para la yihad\" que él defendía como referencias espirituales al esfuerzo personal. Se ordenó la entrada y registro en su domicilio donde se incautaron dispositivos electrónicos. El análisis forense no reveló conexiones con grupos terroristas, manuales de fabricación de explosivos ni comunicaciones con células yihadistas. Los mensajes se limitaban a contenido religioso mainstream y motivación deportiva. El instructor acordó el sobreseimiento provisional que fue confirmado por auto del 10 de julio de 2025.",
      estrategia: "La defensa se articuló en torno a la diferenciación entre práctica religiosa legítima y radicalización terrorista. Se argumentó que las referencias a la \"yihad\" en el contexto deportivo aludían al concepto islámico de esfuerzo personal y superación, no a la guerra santa. Se aportaron dictámenes de expertos en islam que explicaban el uso polisémico del término en la cultura musulmana. La estrategia incluyó demostrar la ausencia total de elementos típicos del yihadismo violento: no había exaltación de atentados, glorificación de terroristas, manuales operativos ni contactos con redes extremistas. Se enfatizó el perfil público del investigado como deportista e influencer con miles de seguidores, incompatible con la clandestinidad terrorista. Además, se cuestionó la proporcionalidad de la investigación y se denunció la criminalización de la religiosidad musulmana.",
      pruebas: "El análisis pericial de los dispositivos incautados fue la prueba fundamental. No se encontraron indicios de radicalización violenta: ni propaganda del ISIS/Al Qaeda, ni manuales de combate, ni comunicaciones cifradas con grupos terroristas. Los vídeos analizados mostraban únicamente rutinas deportivas con ocasionales referencias religiosas genéricas. Se aportaron testimonios de seguidores y colaboradores que confirmaban el carácter exclusivamente deportivo y motivacional del contenido. Peritos en terrorismo yihadista dictaminaron que el perfil no correspondía con los patrones de radicalización conocidos. La defensa presentó abundante jurisprudencia sobre libertad religiosa y los límites del delito de autoadoctrinamiento terrorista, que exige una vocación real de cometer atentados.",
      resolucion: "El Juzgado Central de Instrucción nº 2 de la Audiencia Nacional dictó Auto de sobreseimiento provisional el 10 de julio de 2025. La resolución estableció que no existían indicios racionales de criminalidad por delito de terrorismo. El instructor consideró que las manifestaciones religiosas del investigado, aunque pudieran resultar llamativas en el contexto de las redes sociales, no sobrepasaban el ejercicio legítimo de la libertad religiosa y de expresión. Se valoró especialmente la ausencia total de elementos objetivos de radicalización violenta y la falta de conexión con organizaciones terroristas. El Ministerio Fiscal no recurrió el auto, quedando firme el sobreseimiento. El investigado recuperó los dispositivos incautados y pudo continuar con su actividad en redes sociales.",
      marco_legal: "El caso se enmarcó en el artículo 575.2 del Código Penal que tipifica el autoadoctrinamiento terrorista. La jurisprudencia del Tribunal Supremo exige para su apreciación no solo el consumo de contenido radical sino la finalidad real de cometer delitos de terrorismo. La mera radicalización ideológica sin vocación delictiva no es punible. La resolución aplicó doctrina del TEDH sobre libertad religiosa (art. 9 CEDH) y expresión (art. 10 CEDH), recordando que solo cabe limitar estos derechos ante un peligro real e inminente para la seguridad nacional. También se invocó jurisprudencia sobre el principio de proporcionalidad en las investigaciones por terrorismo y los riesgos de criminalizar la religiosidad musulmana."
    }
  },
  // Caso 3 - OPERACIÓN LUCO – BANDA DEL ROLEX
  3: {
    nombre: "OPERACIÓN LUCO – BANDA DEL ROLEX",
    delito_principal: "Robo con violencia e intimidación; pertenencia a grupo criminal",
    resultado: "Sobreseimiento sólo para nuestro cliente",
    contenido: {
      resumen: "En el marco de la conocida Operación Luco, que persiguió una banda organizada dedicada a robar relojes de lujo en Madrid, nuestro defendido fue investigado por robo con violencia e integración en grupo criminal. La acusación solicitaba penas de hasta once años de prisión. Sin embargo, gracias a una estrategia procesal muy técnica que destacó la ausencia de indicios concretos contra él, el Ministerio Fiscal solicitó el sobreseimiento y el Juzgado de Instrucción nº 15 de Madrid archivó la causa únicamente en relación con nuestro cliente. El resto de investigados continuaron encausados.",
      hechos: "La Operación Luco nació en 2023 como el primer operativo del Grupo Crono, un equipo de la Policía Nacional especializado en delitos patrimoniales. Según la prensa, el nombre procede de la abreviatura de «peluco», un argot para referirse a los relojes de alta gama. La investigación se centró en un grupo de varones que actuaban en barrios adinerados de Madrid como la Milla de Oro. Utilizando motocicletas y pistolas, seleccionaban a sus víctimas en restaurantes y hoteles de lujo y, con gran violencia, les sustraían relojes valorados entre 30.000 y 120.000 euros. Esta banda habría perpetrado al menos ocho atracos e incluso causó lesiones graves a algunas víctimas. La causa judicial se incoó como Procedimiento abreviado en el Juzgado de Instrucción nº 15 de Madrid bajo el NIG 28.079.00.1‑2022/0363576. Se imputó a nuestro defendido y a otros investigados por delitos de robo con violencia o intimidación y pertenencia a grupo criminal. La presión mediática fue intensa, y la Fiscalía solicitaba penas de hasta once años de prisión.",
      estrategia: "La defensa centró su estrategia en demostrar la ausencia de evidencias individualizadas contra nuestro cliente. Se impugnaron las identificaciones policiales y testificales que lo situaban en los atracos, subrayando que estas se basaban en conjeturas y que ningún testigo lo reconoció de manera fiable. Asimismo, se cuestionó la cadena de custodia de los efectos incautados y se recalcó que el pertenecer a un círculo de amistades no puede equipararse a integrar un grupo criminal. Nuestra representación insistió en la presunción de inocencia y en que las diligencias policiales no evidenciaban su participación material en los hechos. Frente a la inexistencia de pruebas directas, se propuso la práctica de nuevas diligencias periciales y se interesó el archivo parcial. El escrito de defensa resaltó que mantenerlo como acusado vulneraría el principio de proporcionalidad y causaría un perjuicio irreparable a su honor.",
      pruebas: "El sumario contenía atestados policiales, declaraciones de víctimas, análisis balísticos y reportajes gráficos de los asaltos. Sin embargo, ninguno de esos elementos vinculaba de manera concluyente a nuestro defendido. Las manifestaciones de algunos testigos describían a atracadores en motocicleta, pero no podían identificar a nuestro cliente. Tampoco se aportaron llamadas, mensajes o geolocalizaciones que lo incriminasen. La defensa destacó que la única prueba documental que lo mencionaba era un parte policial que recogía rumores sobre su posible relación con uno de los detenidos.",
      resolucion: "Tras valorar las alegaciones de todas las partes, el Ministerio Fiscal reconoció que no existían indicios suficientes para sostener la acusación y solicitó el sobreseimiento respecto de nuestro defendido. El Juzgado validó dicha petición y dictó auto de archivo, poniendo fin al procedimiento para él. De esta forma, nuestro cliente quedó exonerado mientras que las actuaciones continuaron contra los restantes encausados.",
      marco_legal: "El delito de robo con violencia o intimidación está previsto en los artículos 237 y siguientes del Código Penal y conlleva penas de prisión de dos a cinco años cuando concurren violencia o intimidación. La pertenencia a grupo criminal se regula en el artículo 570 ter del mismo código. Ambos tipos penales exigen la acreditación de la participación concreta del acusado y la existencia de una estructura organizada. La defensa recordó que la jurisprudencia del Tribunal Supremo exige una prueba directa de la integración y prohibe condenar basándose en meras sospechas."
    }
  },
  // Caso 4 - DOMINICANT DONT PLAY (DDP)
  4: {
    nombre: "CASO DOMINICANT DONT PLAY (DDP)",
    delito_principal: "Pertenencia a organización criminal (Dominican Don't Play)",
    resultado: "Absolución con todos los pronunciamientos favorables",
    contenido: {
      resumen: "La Sección 30 de la Audiencia Provincial de Madrid enjuició a nuestro cliente por un presunto delito de pertenencia a la banda latina Dominican Don't Play (DDP). El Ministerio Fiscal solicitaba una pena privativa de libertad, apoyándose principalmente en atestados policiales y en la supuesta vinculación del acusado con otros jóvenes del barrio. Tras el juicio, la Sala consideró que no existían pruebas concluyentes de su integración en una organización criminal y, mediante la Sentencia 590/2024 de 20 de noviembre de 2024, acordó absolverlo. La resolución subraya la presunción de inocencia y la necesidad de acreditar la participación activa en la banda para poder condenar.",
      hechos: "Los Dominican Don't Play (DDP) son una banda juvenil de origen latino considerada violenta y asociada a delitos graves. Las autoridades y los medios han advertido que se trata de una 'tribu urbana' peligrosa cuyas actividades han sido declaradas ilícitas por el Tribunal Supremo. En este caso, nuestro cliente fue investigado tras una serie de operativos policiales en los que se detuvo a varios jóvenes del barrio por su supuesta pertenencia a la organización. La acusación se basaba en la frecuentación de determinados lugares y en la amistad con otros investigados, sin aportar pruebas directas de participación en actividades delictivas.",
      estrategia: "La defensa se centró en demostrar que la mera relación social con otros jóvenes del barrio no constituye prueba de pertenencia a una organización criminal. Se destacó la ausencia de elementos objetivos que vincularan a nuestro cliente con la estructura, jerarquía o actividades de la banda. Se subrayó que no existían interceptaciones telefónicas, vigilancias específicas, identificación en actos violentos ni posesión de símbolos o distintivos de la organización. La estrategia procesal incluyó la impugnación de los informes policiales genéricos y la exigencia de pruebas individualizadas.",
      pruebas: "En el sumario constaban atestados policiales, declaraciones testificales y algún informe pericial. Ninguno de estos documentos vinculaba de forma directa a nuestro cliente con delitos específicos ni con la organización. Los agentes de policía admitieron que no habían realizado ruedas de reconocimiento ni vigilancias personalizadas y que se basaban en datos obtenidos de otras investigaciones. La defensa subrayó que no existía evidencia de llamadas, mensajes, armas ni símbolos que demostraran la integración de nuestro cliente en la banda. La única prueba era un parte policial que recogía rumores sobre su amistad con otros jóvenes.",
      resolucion: "El 20 de noviembre de 2024 la Sección 30 de la Audiencia Provincial de Madrid dictó la Sentencia 590/2024. En ella los magistrados Rosa M.ª Quintana San Martín (ponente), Ignacio José Fernández Soto y Juan José Toscano Tinoco valoraron las pruebas y concluyeron que no se había acreditado la pertenencia del acusado a la organización. La Sala absolvió a nuestro cliente y a otro coacusado del delito de pertenencia a organización criminal. Se destacó que la mera existencia de bandas latinas declaradas ilícitas no exime de probar la integración de cada investigado y que las conjeturas no pueden sustituir a la prueba de cargo.",
      marco_legal: "El delito de pertenencia a organización criminal está regulado en los artículos 570 bis y 570 ter del Código Penal. Exige la existencia de una estructura estable, concertada para cometer delitos, y la participación activa del acusado. La jurisprudencia del Tribunal Supremo señala que la condición de miembro debe acreditarse mediante actos externos que evidencien una implicación real y no por meras sospechas. En nuestro caso, la Audiencia Provincial aplicó estos criterios para absolver."
    }
  },
  // Caso 5 - ACADEMIA YIHAD
  5: {
    nombre: "CASO ACADEMIA YIHAD",
    delito_principal: "Adoctrinamiento terrorista y pertenencia a organización criminal",
    resultado: "Modificación de prisión provisional a libertad provisional sin fianza",
    contenido: {
      resumen: "El Juzgado Central de Instrucción n.º 6 investigaba desde 2024 a dos hermanas de Alcorcón por crear una \"academia yihadista\" en redes sociales en la que captaban a centenares de mujeres. La operación, dirigida por la Audiencia Nacional, culminó con su detención el 30 de mayo de 2025. Tras una primera orden de prisión provisional para una de ellas, el auto de 24 de julio de 2025 modificó la medida y acordó su libertad provisional sin fianza con fuertes cautelares. El procedimiento continúa en fase de instrucción.",
      hechos: "La investigación se inició tras detectar perfiles en redes sociales que difundían contenido yihadista dirigido específicamente a mujeres. Las dos hermanas investigadas habrían creado lo que las autoridades denominaron una \"academia yihadista online\" donde compartían material ideológico, consejos sobre la vida bajo el califato y mensajes de apoyo a organizaciones terroristas. La Policía Nacional estimó que cientos de mujeres seguían estos perfiles y participaban en grupos cerrados donde se intercambiaban mensajes de naturaleza radical. La operación policial culminó con la detención de ambas hermanas y el registro de sus domicilios, donde se incautaron dispositivos electrónicos y documentación.",
      estrategia: "La estrategia se centró en impugnar la tipicidad de los hechos. Se destacó que la clienta no había proporcionado instrucciones concretas para perpetrar atentados y que la legislación penal exige actos de adoctrinamiento idóneos para incitar a la comisión de delitos graves. Se solicitó la libertad provisional argumentando arraigo familiar, ausencia de antecedentes y colaboración con la instrucción. También se aportaron informes periciales sobre la intencionalidad de los mensajes difundidos, que evidenciaban un contexto discursivo y no operativo.",
      pruebas: "Las diligencias incluían atestados de la Policía Nacional con análisis de perfiles en redes sociales, capturas de pantalla y periciales de inteligencia digital. No se practicaron testificales directas de terceras personas radicalizadas. La defensa aportó informes de un perito lingüista que concluían que los mensajes eran expresiones ideológicas sin instrucciones para cometer actos terroristas.",
      resolucion: "Mediante auto de 24 de julio de 2025, el Juzgado Central de Instrucción n.º 6 acordó modificar la prisión preventiva comunicada y sin fianza dictada el 29 de mayo de 2025. La resolución dispuso la libertad provisional sin fianza con prohibición de abandonar el territorio nacional, retirada del pasaporte y comparecencia semanal. El juzgado entendió que se habían mitigado los riesgos procesales y que no existían indicios suficientes para mantener la prisión preventiva. La causa continúa en fase instructoria.",
      marco_legal: "Se aplican los artículos 575 y 576 del Código Penal relativos al adoctrinamiento y enaltecimiento terrorista, así como los artículos 503 y 504 de la Ley de Enjuiciamiento Criminal sobre la prisión provisional y sus presupuestos. La jurisprudencia del Tribunal Supremo exige que las publicaciones vayan acompañadas de una llamada efectiva a cometer delitos graves para apreciar adoctrinamiento."
    }
  },
  // Caso 6 - LESIONES
  6: {
    nombre: "CASO LESIONES",
    delito_principal: "Lesiones",
    resultado: "Auto de sobreseimiento provisional",
    contenido: {
      resumen: "El Juzgado de 1ª Instancia e Instrucción nº 6 de Getafe investigó a nuestro cliente por un presunto delito de lesiones. Tras analizar las pruebas y alegaciones presentadas por la defensa, el juzgado dictó auto de sobreseimiento provisional, archivando las actuaciones sin necesidad de celebrar juicio oral.",
      hechos: "Se imputó a nuestro cliente un delito de lesiones tras una denuncia presentada por hechos ocurridos en el municipio de Getafe. La acusación particular alegaba que el investigado había causado lesiones que requirieron asistencia médica. Sin embargo, las circunstancias del incidente presentaban importantes contradicciones y lagunas probatorias.",
      estrategia: "La defensa se centró en evidenciar las inconsistencias en la versión de los hechos presentada por la parte denunciante. Se cuestionó la credibilidad de los testimonios aportados y se destacó la ausencia de pruebas objetivas que corroboraran la versión acusatoria. Se solicitó el sobreseimiento provisional argumentando la insuficiencia de indicios racionales de criminalidad.",
      pruebas: "El expediente incluía el atestado policial inicial, partes médicos y declaraciones testificales. Sin embargo, los informes médicos no eran concluyentes sobre el origen de las lesiones y los testimonios presentaban contradicciones significativas. No existían pruebas documentales ni grabaciones que permitieran esclarecer los hechos de manera objetiva.",
      resolucion: "El Juzgado de 1ª Instancia e Instrucción nº 6 de Getafe dictó auto de sobreseimiento provisional en 2024. La resolución consideró que no existían indicios suficientes para continuar con el procedimiento penal contra nuestro cliente. El archivo de las actuaciones fue definitivo al no presentarse nuevas pruebas por la acusación.",
      marco_legal: "El delito de lesiones se encuentra tipificado en los artículos 147 y siguientes del Código Penal. El sobreseimiento provisional está regulado en el artículo 641 de la Ley de Enjuiciamiento Criminal, que permite el archivo cuando no resulte debidamente justificada la perpetración del delito o cuando no haya motivos suficientes para acusar a determinada persona."
    }
  }
};
