// Traducciones de casos en español
export const casesES = {
  // Caso 1 - QUIQUE LIBERTAD DE EXPRESION SOBRESEIMIENTO
  1: {
    nombre: "CASO QUIQUE - LIBERTAD DE EXPRESION SOBRESEIMIENTO",
    delito_principal: "Delito de odio y contra los sentimientos religiosos",
    resultado: "La Audiencia Provincial decreta el Sobreseimiento",
    contenido: {
      resumen: "Una asociación interpuso querella contra el humorista Héctor de Miguel (artísticamente \"Quequé\") por supuestas expresiones de odio vertidas en su programa Hora Veintipico. El Juzgado de Instrucción nº 38 de Madrid procesó al cómico por un presunto delito de odio y contra los sentimientos religiosos. Tanto la defensa como el Ministerio Fiscal recurrieron la decisión y, mediante Auto nº 379/2025 de 30 de abril de 2025, la Sección 30 de la Audiencia Provincial de Madrid estimó ambos recursos y ordenó el sobreseimiento libre de las actuaciones al considerar que las manifestaciones se encontraban amparadas por la libertad de expresión y de creación artística.",
      hechos: "El 27 de junio de 2024, durante el programa radiofónico y de humor Hora Veintipico de la Cadena SER, Héctor de Miguel bromeó con \"llenar de dinamita la cruz del Valle de los Caídos\" y arrojar las piedras resultantes contra sacerdotes pederastas. Una asociación presentó una querella y el Juzgado de Instrucción nº 38 admitió a trámite la acusación y acordó la continuación por el trámite del procedimiento abreviado por un posible delito de odio. La acusación sostuvo que las expresiones atribuibles al investigado no eran una mera hipérbole sino que incitaban a la hostilidad contra la religión católica. Frente a esa postura, la defensa alegó que se trataba de un ejercicio satírico protegido por el artículo 20 de la Constitución. Tras la incoación, tanto el Ministerio Fiscal como la representación de Héctor de Miguel interpusieron recurso de apelación contra el auto que le había procesado. La Audiencia Provincial de Madrid, Sección 30, examinó el contexto y el tono humorístico de las manifestaciones y concluyó que no existía incitación al odio ni hostilidad real. Por ello revocó la decisión instructora y ordenó el sobreseimiento libre de la causa.",
      estrategia: "La estrategia se centró en resaltar el carácter satírico y artístico de las expresiones denunciadas, invocando la protección constitucional de la libertad de expresión y de creación (art. 20 de la Constitución Española). La defensa argumentó que el humor político, incluso cuando resulta provocador u ofensivo, forma parte del debate público y no puede castigarse penalmente sin afectar al pluralismo. Se impugnó la interpretación expansiva del delito de odio (art. 510 CP) y se recordaron los límites exigidos por la jurisprudencia: debe existir una incitación real y grave a la hostilidad o violencia contra un colectivo, circunstancia inexistente en el caso. Además se reprochó al querellante utilizar el proceso penal para coartar la crítica y se sostuvo la falta de legitimación de una asociación privada para defender sentimientos religiosos ajenos. La defensa contó con el respaldo del Ministerio Fiscal, que también recurrió el procesamiento.",
      pruebas: "Las pruebas se limitaron a la grabación del programa de radio en el que se pronunciaron las frases, así como a las transcripciones aportadas por la querella. No existían testigos que acreditasen un clima hostil posterior ni actos de violencia o discriminación. En el recurso se destacó la inexistencia de daño o riesgo concreto y la ausencia de seguimiento de las palabras en los días posteriores. La defensa aportó jurisprudencia constitucional y europea sobre libertad de expresión y precedentes en los que se archivaron denuncias basadas en discursos humorísticos. Finalmente, el auto apelado, junto con el recurso del Ministerio Fiscal y el de la defensa, fueron valorados por la Audiencia Provincial.",
      resolucion: "La Audiencia Provincial de Madrid (Sección 30) dictó el Auto nº 379/2025 de 30 de abril de 2025 en el que estimó los recursos de apelación interpuestos por el Ministerio Fiscal y la representación de Héctor de Miguel. Revocó el auto del Juzgado de Instrucción nº 38 de Madrid de 23 de enero de 2025 y, conforme al artículo 637.1 de la Ley de Enjuiciamiento Criminal, decretó el sobreseimiento libre de la causa. La Sala entendió que las manifestaciones satíricas no constituyen delito de odio ni fomentan la hostilidad contra los católicos. Contra esta resolución no cabía recurso. El resultado fue plenamente favorable para el cliente, que quedó liberado de cualquier imputación.",
      marco_legal: "El caso giró en torno al equilibrio entre la libertad de expresión y creación artística (art. 20 CE) y los límites del delito de odio tipificado en el artículo 510 del Código Penal. La Audiencia Provincial subrayó que, para apreciar el delito de odio, se exige una incitación real y directa a la violencia o discriminación contra un colectivo. En ausencia de tal requisito y ante el contexto humorístico, procede el sobreseimiento libre con apoyo en el artículo 637.1 LECrim. La resolución también reproduce doctrina constitucional que protege expresiones satíricas que, aunque puedan resultar ofensivas, forman parte del debate democrático y no sobrepasan los límites del derecho penal."
    }
  },
  // Caso 2 - NORDIN WORKOUT
  2: {
    nombre: "CASO NORDIN WORKOUT",
    delito_principal: "Terrorismo de índole yihadista (autoadoctrinamiento)",
    resultado: "Auto de Sobreseimiento",
    contenido: {
      resumen: "La Policía Nacional investigó a un influencer del mundo del fitness conocido como Nordin Workout por supuesto autoadoctrinamiento yihadista y captación online. La investigación se inició por publicaciones en redes sociales donde mezclaba contenido deportivo con referencias religiosas que las autoridades interpretaron como potencialmente radicales. Tras registros domiciliarios y análisis de dispositivos, no se encontraron pruebas de planificación de atentados ni pertenencia a células terroristas. El Juzgado Central de Instrucción nº 2 de la Audiencia Nacional dictó auto de sobreseimiento al no apreciar indicios suficientes de delito de terrorismo.",
      hechos: "El 22 de enero de 2025, la Guardia Civil derribó la puerta del domicilio de Nordin y lo detuvo, acusándolo de adoctrinamiento yihadista. El influencer deportivo llevaba siendo investigado casi un año y medio. Lo único que se le imputó fueron ocho stories de Instagram en los que utilizó unas canciones llamadas 'Nasheeds', que están disponibles en Spotify e Instagram. Según las autoridades, con estas publicaciones buscaba adoctrinar de forma pasiva. Nordin pasó más de tres meses y medio en prisión provisional en régimen de aislamiento. Durante la instrucción se ordenó el registro de su domicilio y se incautaron dispositivos electrónicos. El análisis forense no reveló conexiones con grupos terroristas, manuales de fabricación de explosivos ni comunicaciones con células yihadistas. Los mensajes se limitaban a contenido religioso mainstream y motivación deportiva. El instructor acordó el sobreseimiento provisional que fue confirmado por auto del 10 de julio de 2025.",
      estrategia: "La defensa, liderada por el abogado Rubén Vaquero de Stans Abogados, se articuló en torno a la diferenciación entre práctica religiosa legítima y radicalización terrorista. Se argumentó que las referencias a la \"yihad\" en el contexto deportivo aludían al concepto islámico de esfuerzo personal y superación, no a la guerra santa. Se enfatizó que Nordin no conocía el origen de las canciones Nasheeds, que están disponibles libremente en plataformas como Spotify e Instagram. Se aportaron dictámenes de expertos en islam que explicaban el uso polisémico del término en la cultura musulmana. La estrategia incluyó demostrar la ausencia total de elementos típicos del yihadismo violento: no había exaltación de atentados, glorificación de terroristas, manuales operativos ni contactos con redes extremistas. Se enfatizó el perfil público del investigado como deportista e influencer con cientos de miles de seguidores, incompatible con la clandestinidad terrorista. Además, se cuestionó la proporcionalidad de la investigación y se denunció la criminalización de la religiosidad musulmana.",
      pruebas: "El análisis pericial de los dispositivos incautados fue la prueba fundamental. No se encontraron indicios de radicalización violenta: ni propaganda del ISIS/Al Qaeda, ni manuales de combate, ni comunicaciones cifradas con grupos terroristas. Los vídeos analizados mostraban únicamente rutinas deportivas con ocasionales referencias religiosas genéricas. De los 205 Nasheeds de su lista de reproducción, solo cinco podían considerarse sospechosos; el resto eran canciones sin relación con el extremismo. Se aportaron testimonios de seguidores y colaboradores que confirmaban el carácter exclusivamente deportivo y motivacional del contenido. Peritos en terrorismo yihadista dictaminaron que el perfil no correspondía con los patrones de radicalización conocidos. La defensa presentó abundante jurisprudencia sobre libertad religiosa y los límites del delito de autoadoctrinamiento terrorista, que exige una vocación real de cometer atentados.",
      resolucion: "El Juzgado Central de Instrucción nº 2 de la Audiencia Nacional dictó Auto de sobreseimiento provisional el 10 de julio de 2025. La resolución estableció que no existían indicios racionales de criminalidad por delito de terrorismo. El instructor consideró que las manifestaciones religiosas del investigado, aunque pudieran resultar llamativas en el contexto de las redes sociales, no sobrepasaban el ejercicio legítimo de la libertad religiosa y de expresión. Se valoró especialmente la ausencia total de elementos objetivos de radicalización violenta y la falta de conexión con organizaciones terroristas. El Ministerio Fiscal no recurrió el auto, quedando firme el sobreseimiento. El investigado recuperó los dispositivos incautados y pudo continuar con su actividad en redes sociales.",
      marco_legal: "El caso se enmarcó en el artículo 575.2 del Código Penal que tipifica el autoadoctrinamiento terrorista. La jurisprudencia del Tribunal Supremo exige para su apreciación no solo el consumo de contenido radical sino la finalidad real de cometer delitos de terrorismo. La mera radicalización ideológica sin vocación delictiva no es punible. La resolución aplicó doctrina del TEDH sobre libertad religiosa (art. 9 CEDH) y expresión (art. 10 CEDH), recordando que solo cabe limitar estos derechos ante un peligro real e inminente para la seguridad nacional. También se invocó jurisprudencia sobre el principio de proporcionalidad en las investigaciones por terrorismo y los riesgos de criminalizar la religiosidad musulmana.",
      cobertura_mediatica: {
        titulo: "📺 Nordin Workout habla en La Sexta sobre su encarcelamiento injusto",
        descripcion: "En una entrevista exclusiva con La Sexta, Nordin relata cómo vivió su detención y los tres meses que pasó en régimen de aislamiento. En el reportaje también interviene su abogado defensor, Rubén Vaquero de Stans Abogados, quien denuncia la falta de resarcimiento tras el daño causado.",
        noticia: {
          titulo: "Nordin, el influencer deportivo que fue encarcelado injustamente acusado de yihadismo: \"Vi volar la puerta de casa y pensé que era un error\"",
          medio: "La Sexta",
          fecha: "9 de noviembre de 2025",
          url: "https://www.lasexta.com/noticias/sociedad/habla-nordin-influencer-deportivo-que-fue-encarcelado-injustamente-acusado-yihadismo-volar-puerta-casa-pense-que-era-error_202511096910d3bb5d5dad37ab8a3201.html",
          destacados: [
            "\"Vi volar la puerta de mi casa y pensé que se habían confundido, que iría a comisaría, lo explicaría y me iría a casa, pero lo que no me esperaba era pasar tres meses y medio en prisión\" - Nordin Workout",
            "\"Esta persona, que ha sido denigrada y señalado prácticamente como un animal, ahora no obtiene ningún tipo de resarcimiento, no obtiene ningún tipo de perdón\" - Rubén Vaquero, Abogado Defensor",
            "\"Hay algo que no está funcionando, hay que revisarlo. No se puede criminalizar a personas solo por su religión\" - Nordin Workout"
          ]
        },
        video: {
          titulo: "Entrevista completa en La Sexta - Caso Nordin Workout",
          plataforma: "YouTube",
          url: "https://www.youtube.com/watch?v=c8n2jE4zSd0",
          descripcion: "Video completo de la entrevista donde Nordin cuenta su experiencia y el abogado Rubén Vaquero analiza las implicaciones legales del caso."
        },
        impacto_social: "A raíz de contar su historia, a Nordin le han llegado multitud de mensajes de jóvenes musulmanes a los que les ha ocurrido lo mismo. El caso ha puesto de manifiesto la necesidad de revisar las políticas de investigación para evitar la criminalización basada en la religión."
      }
    }
  },
  // Caso 3 - OPERACIÓN LUCO – BANDA DEL ROLEX
  3: {
    nombre: "OPERACIÓN LUCO – BANDA DEL ROLEX",
    delito_principal: "Robo con violencia e intimidación; pertenencia a grupo criminal",
    resultado: "Sobreseimiento sólo para nuestro cliente",
    contenido: {
      resumen: "En el marco de la conocida Operación Luco, que persiguió una banda organizada dedicada a robar relojes de lujo en Madrid, nuestro defendido fue investigado por robo con violencia e integración en grupo criminal. La acusación solicitaba penas de hasta once años de prisión. Sin embargo, gracias a una estrategia procesal muy técnica que destacó la ausencia de indicios concretos contra él, el Ministerio Fiscal solicitó el sobreseimiento y el Juzgado de Instrucción nº 15 de Madrid archivó la causa únicamente en relación con nuestro cliente. El resto de investigados continuaron encausados.",
      hechos: "La Operación Luco nació en 2023 como el primer operativo del Grupo Crono, un equipo de la Policía Nacional especializado en delitos patrimoniales. Según la prensa, el nombre procede de la abreviatura de «peluco», un argot para referirse a los relojes de alta gama. La investigación se centró en un grupo de varones que actuaban en barrios adinerados de Madrid como la Milla de Oro. Utilizando motocicletas y pistolas, seleccionaban a sus víctimas en restaurantes y hoteles de lujo y, con gran violencia, les sustraían relojes valorados entre 30.000 y 120.000 euros. Esta banda habría perpetrado al menos ocho atracos e incluso causó lesiones graves a algunas víctimas. La causa judicial se incoó como Procedimiento abreviado en el Juzgado de Instrucción nº 15 de Madrid bajo el NIG 28.079.00.1‑2022/0363576. Se imputó a nuestro defendido y a otros investigados por delitos de robo con violencia o intimidación y pertenencia a grupo criminal. La presión mediática fue intensa, y la Fiscalía solicitaba penas de hasta once años de prisión.",
      estrategia: "La defensa centró su estrategia en demostrar la ausencia de evidencias individualizadas contra nuestro cliente. Se impugnaron las identificaciones policiales y testificales que lo situaban en los atracos, subrayando que estas se basaban en conjeturas y que ningún testigo lo reconoció de manera fiable. Asimismo, se cuestionó la cadena de custodia de los efectos incautados y se recalcó que el pertenecer a un círculo de amistades no puede equipararse a integrar un grupo criminal. Nuestra representación insistió en la presunción de inocencia y en que las diligencias policiales no evidenciaban su participación material en los hechos. Frente a la inexistencia de pruebas directas, se propuso la práctica de nuevas diligencias periciales y se interesó el archivo parcial. El escrito de defensa resaltó que mantenerlo como acusado vulneraría el principio de proporcionalidad y causaría un perjuicio irreparable a su honor.",
      pruebas: "El sumario contenía atestados policiales, declaraciones de víctimas, análisis balísticos y reportajes gráficos de los asaltos. Sin embargo, ninguno de esos elementos vinculaba de manera concluyente a nuestro defendido. Las manifestaciones de algunos testigos describían a atracadores en motocicleta, pero no podían identificar a nuestro cliente. Tampoco se aportaron llamadas, mensajes o geolocalizaciones que lo incriminasen. La defensa destacó que la única prueba documental que lo mencionaba era un parte policial que recogía rumores sobre su posible relación con uno de los detenidos.",
      resolucion: "Tras valorar las alegaciones de todas las partes, el Ministerio Fiscal reconoció que no existían indicios suficientes para sostener la acusación y solicitó el sobreseimiento respecto de nuestro defendido. El Juzgado validó dicha petición y dictó auto de archivo, poniendo fin al procedimiento para él. De esta forma, nuestro cliente quedó exonerado mientras que las actuaciones continuaron contra los restantes encausados.",
      marco_legal: "El delito de robo con violencia o intimidación está previsto en los artículos 237 y siguientes del Código Penal y conlleva penas de prisión de dos a cinco años cuando concurren violencia o intimidación. La pertenencia a grupo criminal se regula en el artículo 570 ter del mismo código. Ambos tipos penales exigen la acreditación de la participación concreta del acusado y la existencia de una estructura organizada. La defensa recordó que la jurisprudencia del Tribunal Supremo exige una prueba directa de la integración y prohibe condenar basándose en meras sospechas."
    }
  },
  // Caso 4 - DOMINICANT DONT PLAY (DDP)
  4: {
    nombre: "CASO DOMINICANT DONT PLAY (DDP)",
    delito_principal: "Pertenencia a organización criminal (Dominican Don't Play)",
    resultado: "Absolución con todos los pronunciamientos favorables",
    contenido: {
      resumen: "La Sección 30 de la Audiencia Provincial de Madrid enjuició a nuestro cliente por un presunto delito de pertenencia a la banda latina Dominican Don't Play (DDP). El Ministerio Fiscal solicitaba una pena privativa de libertad, apoyándose principalmente en atestados policiales y en la supuesta vinculación del acusado con otros jóvenes del barrio. Tras el juicio, la Sala consideró que no existían pruebas concluyentes de su integración en una organización criminal y, mediante la Sentencia 590/2024 de 20 de noviembre de 2024, acordó absolverlo. La resolución subraya la presunción de inocencia y la necesidad de acreditar la participación activa en la banda para poder condenar.",
      hechos: "Los Dominican Don't Play (DDP) son una banda juvenil de origen latino considerada violenta y asociada a delitos graves. Las autoridades y los medios han advertido que se trata de una 'tribu urbana' peligrosa cuyas actividades han sido declaradas ilícitas por el Tribunal Supremo. En este caso, nuestro cliente fue investigado tras una serie de operativos policiales en los que se detuvo a varios jóvenes del barrio por su supuesta pertenencia a la organización. La acusación se basaba en la frecuentación de determinados lugares y en la amistad con otros investigados, sin aportar pruebas directas de participación en actividades delictivas.",
      estrategia: "La defensa se centró en demostrar que la mera relación social con otros jóvenes del barrio no constituye prueba de pertenencia a una organización criminal. Se destacó la ausencia de elementos objetivos que vincularan a nuestro cliente con la estructura, jerarquía o actividades de la banda. Se subrayó que no existían interceptaciones telefónicas, vigilancias específicas, identificación en actos violentos ni posesión de símbolos o distintivos de la organización. La estrategia procesal incluyó la impugnación de los informes policiales genéricos y la exigencia de pruebas individualizadas.",
      pruebas: "En el sumario constaban atestados policiales, declaraciones testificales y algún informe pericial. Ninguno de estos documentos vinculaba de forma directa a nuestro cliente con delitos específicos ni con la organización. Los agentes de policía admitieron que no habían realizado ruedas de reconocimiento ni vigilancias personalizadas y que se basaban en datos obtenidos de otras investigaciones. La defensa subrayó que no existía evidencia de llamadas, mensajes, armas ni símbolos que demostraran la integración de nuestro cliente en la banda. La única prueba era un parte policial que recogía rumores sobre su amistad con otros jóvenes.",
      resolucion: "El 20 de noviembre de 2024 la Sección 30 de la Audiencia Provincial de Madrid dictó la Sentencia 590/2024. En ella los magistrados Rosa M.ª Quintana San Martín (ponente), Ignacio José Fernández Soto y Juan José Toscano Tinoco valoraron las pruebas y concluyeron que no se había acreditado la pertenencia del acusado a la organización. La Sala absolvió a nuestro cliente y a otro coacusado del delito de pertenencia a organización criminal. Se destacó que la mera existencia de bandas latinas declaradas ilícitas no exime de probar la integración de cada investigado y que las conjeturas no pueden sustituir a la prueba de cargo.",
      marco_legal: "El delito de pertenencia a organización criminal está regulado en los artículos 570 bis y 570 ter del Código Penal. Exige la existencia de una estructura estable, concertada para cometer delitos, y la participación activa del acusado. La jurisprudencia del Tribunal Supremo señala que la condición de miembro debe acreditarse mediante actos externos que evidencien una implicación real y no por meras sospechas. En nuestro caso, la Audiencia Provincial aplicó estos criterios para absolver."
    }
  },
  // Caso 5 - ACADEMIA YIHAD
  5: {
    nombre: "CASO ACADEMIA YIHAD",
    delito_principal: "Adoctrinamiento terrorista y pertenencia a organización criminal",
    resultado: "Modificación de prisión provisional a libertad provisional sin fianza",
    contenido: {
      resumen: "El Juzgado Central de Instrucción n.º 6 investigaba desde 2024 a dos hermanas de Alcorcón por crear una \"academia yihadista\" en redes sociales en la que captaban a centenares de mujeres. La operación, dirigida por la Audiencia Nacional, culminó con su detención el 30 de mayo de 2025. Tras una primera orden de prisión provisional para una de ellas, el auto de 24 de julio de 2025 modificó la medida y acordó su libertad provisional sin fianza con fuertes cautelares. El procedimiento continúa en fase de instrucción.",
      hechos: "La investigación se inició tras detectar perfiles en redes sociales que difundían contenido yihadista dirigido específicamente a mujeres. Las dos hermanas investigadas habrían creado lo que las autoridades denominaron una \"academia yihadista online\" donde compartían material ideológico, consejos sobre la vida bajo el califato y mensajes de apoyo a organizaciones terroristas. La Policía Nacional estimó que cientos de mujeres seguían estos perfiles y participaban en grupos cerrados donde se intercambiaban mensajes de naturaleza radical. La operación policial culminó con la detención de ambas hermanas y el registro de sus domicilios, donde se incautaron dispositivos electrónicos y documentación.",
      estrategia: "La estrategia se centró en impugnar la tipicidad de los hechos. Se destacó que la clienta no había proporcionado instrucciones concretas para perpetrar atentados y que la legislación penal exige actos de adoctrinamiento idóneos para incitar a la comisión de delitos graves. Se solicitó la libertad provisional argumentando arraigo familiar, ausencia de antecedentes y colaboración con la instrucción. También se aportaron informes periciales sobre la intencionalidad de los mensajes difundidos, que evidenciaban un contexto discursivo y no operativo.",
      pruebas: "Las diligencias incluían atestados de la Policía Nacional con análisis de perfiles en redes sociales, capturas de pantalla y periciales de inteligencia digital. No se practicaron testificales directas de terceras personas radicalizadas. La defensa aportó informes de un perito lingüista que concluían que los mensajes eran expresiones ideológicas sin instrucciones para cometer actos terroristas.",
      resolucion: "Mediante auto de 24 de julio de 2025, el Juzgado Central de Instrucción n.º 6 acordó modificar la prisión preventiva comunicada y sin fianza dictada el 29 de mayo de 2025. La resolución dispuso la libertad provisional sin fianza con prohibición de abandonar el territorio nacional, retirada del pasaporte y comparecencia semanal. El juzgado entendió que se habían mitigado los riesgos procesales y que no existían indicios suficientes para mantener la prisión preventiva. La causa continúa en fase instructoria.",
      marco_legal: "Se aplican los artículos 575 y 576 del Código Penal relativos al adoctrinamiento y enaltecimiento terrorista, así como los artículos 503 y 504 de la Ley de Enjuiciamiento Criminal sobre la prisión provisional y sus presupuestos. La jurisprudencia del Tribunal Supremo exige que las publicaciones vayan acompañadas de una llamada efectiva a cometer delitos graves para apreciar adoctrinamiento."
    }
  },
  // Caso 6 - LESIONES
  6: {
    nombre: "CASO LESIONES",
    delito_principal: "Lesiones",
    resultado: "Auto de sobreseimiento provisional",
    contenido: {
      resumen: "El Juzgado de 1ª Instancia e Instrucción nº 6 de Getafe investigó a nuestro cliente por un presunto delito de lesiones. Tras analizar las pruebas y alegaciones presentadas por la defensa, el juzgado dictó auto de sobreseimiento provisional, archivando las actuaciones sin necesidad de celebrar juicio oral.",
      hechos: "Se imputó a nuestro cliente un delito de lesiones tras una denuncia presentada por hechos ocurridos en el municipio de Getafe. La acusación particular alegaba que el investigado había causado lesiones que requirieron asistencia médica. Sin embargo, las circunstancias del incidente presentaban importantes contradicciones y lagunas probatorias.",
      estrategia: "La defensa se centró en evidenciar las inconsistencias en la versión de los hechos presentada por la parte denunciante. Se cuestionó la credibilidad de los testimonios aportados y se destacó la ausencia de pruebas objetivas que corroboraran la versión acusatoria. Se solicitó el sobreseimiento provisional argumentando la insuficiencia de indicios racionales de criminalidad.",
      pruebas: "El expediente incluía el atestado policial inicial, partes médicos y declaraciones testificales. Sin embargo, los informes médicos no eran concluyentes sobre el origen de las lesiones y los testimonios presentaban contradicciones significativas. No existían pruebas documentales ni grabaciones que permitieran esclarecer los hechos de manera objetiva.",
      resolucion: "El Juzgado de 1ª Instancia e Instrucción nº 6 de Getafe dictó auto de sobreseimiento provisional en 2024. La resolución consideró que no existían indicios suficientes para continuar con el procedimiento penal contra nuestro cliente. El archivo de las actuaciones fue definitivo al no presentarse nuevas pruebas por la acusación.",
      marco_legal: "El delito de lesiones se encuentra tipificado en los artículos 147 y siguientes del Código Penal. El sobreseimiento provisional está regulado en el artículo 641 de la Ley de Enjuiciamiento Criminal, que permite el archivo cuando no resulte debidamente justificada la perpetración del delito o cuando no haya motivos suficientes para acusar a determinada persona."
    }
  },
  // Caso 7 - ESTAFA Y BLANQUEO DE CAPITALES JAEN
  7: {
    nombre: "CASO ESTAFA Y BLANQUEO DE CAPITALES JAEN",
    delito_principal: "Estafa y blanqueo de capitales",
    resultado: "Audiencia Provincial estima recurso y archiva la causa",
    contenido: {
      resumen: "Varios investigados eran acusados de estafa y de blanquear capitales supuestamente procedentes de operaciones de phishing. El Juzgado de Instrucción n.º 1 de Jaén dictó auto de continuación del procedimiento abreviado. Contra dicha resolución se interpuso recurso de apelación. La Audiencia Provincial de Jaén, mediante auto núm. 642/2024 de 29 de octubre de 2024, estimó el recurso y ordenó el sobreseimiento provisional y archivo de la causa, al no concurrir indicios suficientes de que los investigados conocieran el origen ilícito de los fondos.",
      hechos: "Los investigados fueron acusados de formar parte de una red de blanqueo de capitales procedentes de estafas mediante phishing. Según la acusación, habrían recibido transferencias de víctimas de estafas informáticas y posteriormente habrían remitido estos fondos a terceros, actuando como 'muleros bancarios'. La investigación se inició tras denuncias de varias víctimas que habían sido engañadas mediante correos electrónicos fraudulentos para realizar transferencias a cuentas controladas por los investigados.",
      estrategia: "La defensa alegó la inexistencia de dolo al tratarse de personas ajenas a la primera fase de la estafa que simplemente recepcionaron transferencias y las remitieron a terceros. Se argumentó que esta conducta puede constituir a lo sumo blanqueo por imprudencia, pero no estafa ni blanqueo doloso, de acuerdo con la doctrina que diferencia el conocimiento de la procedencia ilícita de la mera recepción negligente. Además, se aportaron pruebas documentales de que los acusados no tuvieron beneficio económico.",
      pruebas: "Los autos contaron con informes de movimientos bancarios, declaraciones de los investigados y de los perjudicados, así como periciales informáticas. No se aportó evidencia de comunicaciones entre los acusados y los autores de las estafas. La jurisprudencia ha señalado que la simple recepción de dinero sin comprobar su origen puede constituir blanqueo por imprudencia grave, pero en este caso los magistrados concluyeron que tampoco concurría el elemento de imprudencia exigido.",
      resolucion: "La Sección Segunda de la Audiencia Provincial de Jaén acordó estimar los recursos de apelación interpuestos contra el auto del Juzgado de Instrucción n.º 1 y revocar dicha resolución. En consecuencia, ordenó el sobreseimiento provisional y el archivo de las actuaciones para todos los investigados. La sala destacó la falta de indicios de conocimiento sobre el origen ilícito de los fondos y la ausencia de beneficio económico.",
      marco_legal: "Se invocaron los artículos 248 (estafa) y 301 (blanqueo de capitales) del Código Penal, así como el artículo 641.1.º de la Ley de Enjuiciamiento Criminal, que permite el sobreseimiento cuando no existan indicios racionales de delito. La doctrina del Tribunal Supremo exige la prueba de la procedencia ilícita y del conocimiento por parte del receptor de los fondos."
    }
  },
  // Caso 8 - RESISTENCIA A LA AUTORIDAD
  8: {
    nombre: "ABSOLUCIÓN EN CAUSA POR DELITO DE RESISTENCIA A LA AUTORIDAD",
    delito_principal: "Resistencia a la autoridad (art. 556 CP)",
    resultado: "Sentencia absolutoria",
    contenido: {
      resumen: "Nuestro cliente fue acusado de un delito de resistencia a agentes de la autoridad cuando intentó impedir la entrada de la policía en el domicilio donde se encontraba. El Juzgado de lo Penal n.º 25 de Madrid, mediante sentencia núm. 336/2024 de 11 de septiembre de 2024, le absolvió de todos los cargos al considerar que no se demostró conducta violenta ni desobediencia grave y que la actuación policial fue desproporcionada.",
      hechos: "Los hechos ocurrieron cuando agentes de policía acudieron al domicilio del acusado sin orden judicial. Al intentar acceder a la vivienda, el acusado se opuso a la entrada argumentando que no existía autorización judicial ni situación de flagrancia. Los agentes manifestaron que el acusado les empujó y se resistió activamente, mientras que la defensa sostuvo que únicamente ejerció su derecho constitucional a la inviolabilidad del domicilio de forma pacífica.",
      estrategia: "Se invocó el derecho a la inviolabilidad del domicilio (art. 18 CE) y el derecho a no declarar contra uno mismo. La defensa alegó que la entrada en el domicilio carecía de flagrancia y que el acusado ejerció su derecho a oponerse sin emplear violencia. Además, se solicitó la absolución por falta de prueba de cargo, apoyándose en precedentes en los que la Audiencia Provincial anuló condenas por resistencia cuando los agentes no recordaban los hechos. También se citó la jurisprudencia del Tribunal Supremo que anuló una condena similar al considerar que el ciudadano podía resistirse ante una entrada ilegal.",
      pruebas: "En el juicio se practicaron las declaraciones de los agentes intervinientes y del acusado. No se aportó vídeo ni testigos independientes. La defensa puso de manifiesto las contradicciones entre los agentes y la ausencia de lesiones. La Audiencia Provincial ha reiterado que no basta la declaración policial si no está corroborada por otros elementos.",
      resolucion: "La magistrada del Juzgado de lo Penal n.º 25 dictó sentencia absolutoria. Consideró que la prueba practicada no permitía superar la presunción de inocencia y que el derecho del acusado a impedir la entrada en su domicilio sin autorización estaba amparado por la Constitución. La sentencia ordenó el pago de costas de oficio y declaró firme la resolución.",
      marco_legal: "Se aplican los artículos 556 y 16 del Código Penal y el artículo 18.2 CE sobre la inviolabilidad del domicilio. La jurisprudencia del Tribunal Supremo ha señalado que ante una entrada ilegal en domicilio el ciudadano puede oponerse sin incurrir en delito de resistencia."
    }
  },
  // Caso 9 - ROBO CON VIOLENCIA
  9: {
    nombre: "CASO ROBO CON VIOLENCIA - ABSOLUCIÓN",
    delito_principal: "Robo con violencia o intimidación y lesiones",
    resultado: "Sentencia absolutoria",
    contenido: {
      resumen: "El Juzgado de lo Penal n.º 3 de Madrid juzgó a nuestro cliente por un robo con violencia o intimidación y un delito de lesiones con instrumento peligroso. Mediante sentencia núm. 50/2023 de 15 de febrero de 2023, la magistrada Concepción Ramiro Bargueño absolvió a los acusados al no quedar acreditado el uso de violencia ni su participación en los hechos.",
      hechos: "Se acusó a nuestro cliente de participar junto con otros individuos en un robo con violencia en el que supuestamente se habría agredido a la víctima con un instrumento peligroso. La acusación sostenía que los imputados habían actuado en grupo para sustraer pertenencias de la víctima empleando violencia física. Sin embargo, las circunstancias del incidente presentaban importantes contradicciones y la identificación de los supuestos autores era cuestionable.",
      estrategia: "La defensa planteó la inexistencia de prueba de cargo suficiente y la vulneración del derecho a la presunción de inocencia. Se subrayó que no se había acreditado el dominio del hecho ni la participación del acusado y que los reconocimientos fotográficos eran imprecisos. Además, se invocó la distinción entre robo con violencia y robo con fuerza en las cosas, señalando que la calificación de violencia exige un plus de agresión directa sobre las personas.",
      pruebas: "Los principales medios de prueba fueron las declaraciones de la víctima y de los procesados, informes forenses y el atestado policial. La ausencia de testigos neutrales y de prueba pericial concluyente debilitó la acusación. La doctrina del Tribunal Supremo recuerda que la aplicación de la modalidad atenuada de robo con violencia sólo procede cuando la violencia es de escasa entidad; en este caso ni siquiera se pudo acreditar la violencia.",
      resolucion: "La sentencia consideró que no existía prueba que desvirtuase la presunción de inocencia. Se absolvió a todos los acusados de los delitos de robo con violencia o intimidación y lesiones. Se declararon de oficio las costas procesales.",
      marco_legal: "Resultan de aplicación los artículos 237 y 242 del Código Penal (robo con violencia) y el artículo 147 (lesiones). La jurisprudencia distingue entre robo con fuerza (art. 238) y robo con violencia, siendo este último de mayor gravedad."
    }
  },
  // Caso 10 - BLANQUEO POR IMPRUDENCIA
  10: {
    nombre: "CASO BLANQUEO DE CAPITALES POR IMPRUDENCIA GRAVE",
    delito_principal: "Blanqueo de capitales por imprudencia grave",
    resultado: "Sentencia condenatoria con pena muy inferior a la solicitada",
    contenido: {
      resumen: "En el juicio celebrado en el Juzgado de lo Penal n.º 21 de Madrid, el Ministerio Fiscal solicitaba para nuestro cliente una pena de dos años de prisión por un delito de blanqueo de capitales en modalidad dolosa. Gracias a la estrategia de defensa, el órgano judicial consideró que no existía dolo y condenó únicamente por blanqueo imprudente con una multa de 3.600 euros (6 meses a 20 euros/día). Se evitó así la pena de prisión solicitada.",
      hechos: "Nuestro cliente recibió en su cuenta bancaria varias transferencias de origen desconocido que posteriormente transfirió a terceros siguiendo instrucciones recibidas por internet. Desconocía que estos fondos procedían de estafas informáticas realizadas a través de phishing. La Fiscalía sostenía que el acusado debía conocer el origen ilícito por las características de las operaciones y los importes transferidos.",
      estrategia: "La defensa se centró en demostrar la ausencia de conocimiento sobre el origen delictivo de los fondos. Se argumentó que el acusado actuó de buena fe creyendo que realizaba operaciones legítimas de intermediación financiera. Se invocó la jurisprudencia que establece que el blanqueo doloso requiere conocimiento cierto o al menos representación de la procedencia ilícita, mientras que la modalidad imprudente sanciona la falta de diligencia en la comprobación del origen de los fondos.",
      pruebas: "Se analizaron los movimientos bancarios, las comunicaciones del acusado y las declaraciones de los perjudicados. No se encontraron pruebas de contacto directo entre el acusado y los autores de las estafas originarias. La defensa aportó pruebas del perfil personal y profesional del acusado incompatible con actividades delictivas organizadas.",
      resolucion: "El Juzgado de lo Penal n.º 21 de Madrid dictó sentencia condenando por blanqueo de capitales por imprudencia grave con pena de multa de 6 meses a razón de 20 euros diarios (3.600 euros en total). Se descartó la modalidad dolosa y la pena de prisión solicitada por la Fiscalía, aplicando el artículo 301.3 del Código Penal.",
      marco_legal: "El artículo 301 del Código Penal tipifica el blanqueo de capitales, incluyendo en su apartado 3 la modalidad imprudente. La jurisprudencia del Tribunal Supremo distingue entre el dolo eventual (conocimiento de la alta probabilidad del origen ilícito) y la imprudencia grave (omisión de las cautelas exigibles)."
    }
  },
  // Caso 11 - ESTAFA EN GRADO DE TENTATIVA
  11: {
    nombre: "ESTAFA EN GRADO DE TENTATIVA",
    delito_principal: "Estafa en grado de tentativa",
    resultado: "Sentencia absolutoria",
    contenido: {
      resumen: "Nuestro representado fue juzgado por un delito de estafa en grado de tentativa. Se le acusaba de haber intentado cobrar un cheque presuntamente falsificado. Tras el juicio celebrado en el Juzgado de lo Penal n.º 21 de Madrid, fue absuelto mediante sentencia de 8 de mayo de 2024 al no quedar acreditado el elemento subjetivo del tipo penal.",
      hechos: "El acusado intentó cobrar un cheque en una entidad bancaria que resultó tener irregularidades. El banco retuvo el cheque y dio aviso a las autoridades. La acusación sostenía que el acusado conocía la falsedad del documento y actuó con ánimo de defraudar. Sin embargo, el acusado mantenía que recibió el cheque como pago de una deuda legítima y desconocía cualquier irregularidad.",
      estrategia: "La defensa se centró en la ausencia del elemento subjetivo del delito de estafa: el ánimo de defraudar y el conocimiento de la falsedad. Se argumentó que el acusado actuó de buena fe creyendo en la legitimidad del cheque recibido. Se invocó el principio de presunción de inocencia y la necesidad de probar más allá de toda duda razonable la intención delictiva.",
      pruebas: "Se practicaron pruebas periciales sobre el cheque, declaraciones del acusado y del personal bancario. No se aportaron pruebas concluyentes sobre el conocimiento por parte del acusado de las irregularidades del documento. La defensa demostró la existencia de una relación comercial previa que justificaba la recepción del cheque.",
      resolucion: "El Juzgado de lo Penal n.º 21 de Madrid dictó sentencia absolutoria el 8 de mayo de 2024. La magistrada consideró que no quedó acreditado el elemento subjetivo del delito de estafa, es decir, el conocimiento de la falsedad y el ánimo de defraudar. Se aplicó el principio in dubio pro reo ante la falta de pruebas concluyentes.",
      marco_legal: "El delito de estafa está tipificado en el artículo 248 del Código Penal, que exige ánimo de lucro y engaño bastante para producir error en otro. La tentativa se regula en el artículo 16. La jurisprudencia exige la acreditación del elemento subjetivo específico del ánimo defraudatorio."
    }
  },
  // Caso 12 - DELITO LEVE DE LESIONES
  12: {
    nombre: "ABSOLUCIÓN POR FALTA DE PRUEBAS EN DELITO LEVE DE LESIONES",
    delito_principal: "Delito leve de lesiones (art. 147.2 CP)",
    resultado: "Sentencia absolutoria",
    contenido: {
      resumen: "Nuestro cliente fue acusado de un delito leve de lesiones tras una discusión en la vía pública. La acusación particular solicitaba su condena basándose en el parte médico de lesiones. Sin embargo, el Juzgado de Instrucción n.º 7 de Madrid, mediante sentencia de 29 de mayo de 2023, le absolvió al considerar insuficiente la prueba de cargo presentada.",
      hechos: "Se produjo un altercado verbal entre nuestro cliente y el denunciante en la vía pública. Según la denuncia, la discusión derivó en una agresión física que causó lesiones leves al denunciante. Nuestro cliente negó haber agredido al denunciante, sosteniendo que únicamente hubo un intercambio verbal y que en ningún momento se produjo contacto físico.",
      estrategia: "La defensa cuestionó la credibilidad del testimonio del denunciante señalando contradicciones en su relato. Se destacó la ausencia de testigos imparciales y la falta de pruebas objetivas que corroboraran la versión acusatoria. Se argumentó que el parte médico únicamente acreditaba la existencia de lesiones pero no su origen ni autoría.",
      pruebas: "Las pruebas consistieron en las declaraciones de las partes, el parte médico de lesiones y el atestado policial. No existían testigos presenciales ni grabaciones del incidente. La defensa puso de manifiesto que los agentes no presenciaron los hechos y que su intervención fue posterior.",
      resolucion: "El Juzgado de Instrucción n.º 7 de Madrid dictó sentencia absolutoria el 29 de mayo de 2023. El magistrado consideró que existían dudas razonables sobre la participación del acusado en los hechos denunciados. Se aplicó el principio de presunción de inocencia al no existir prueba de cargo suficiente para desvirtuar dicha presunción.",
      marco_legal: "El delito leve de lesiones está tipificado en el artículo 147.2 del Código Penal. La jurisprudencia establece que la mera existencia de lesiones no es prueba suficiente de autoría, siendo necesario acreditar de forma indubitada la relación causal entre la conducta del acusado y el resultado lesivo."
    }
  },
  // Caso 13 - DELITO CONTRA LA SALUD PÚBLICA – SOBRESEIMIENTO
  13: {
    nombre: "CASO DELITO CONTRA LA SALUD PÚBLICA – SOBRESEIMIENTO",
    delito_principal: "Tráfico de drogas (posesión de cannabis)",
    resultado: "Auto de Sobreseimiento",
    contenido: {
      resumen: "En este procedimiento se investigaba a nuestro cliente por un presunto delito contra la salud pública tras la incautación de 3,5 gramos de resina de cannabis. Desde el inicio defendimos que la sustancia estaba destinada al consumo propio y que la cantidad incautada se encontraba muy por debajo de los baremos que el Tribunal Supremo considera indicativos de tráfico. El Juzgado de Instrucción nº 30 de Madrid acogió nuestra tesis y, mediante auto de 25 de noviembre de 2024, acordó el sobreseimiento provisional y el archivo de las diligencias.",
      hechos: "La intervención policial se produjo cuando nuestro cliente fue identificado en la vía pública y se le requisaron 3,5 gramos de resina de cannabis. La denuncia se tramitó como diligencias previas en el Juzgado de Instrucción nº 30 de Madrid. En su declaración, el investigado explicó que la sustancia estaba destinada a consumo compartido con amigos y aportó testigos que corroboraron esta versión. La defensa solicitó que se tuviera en cuenta la jurisprudencia sobre cantidades mínimas y la tabla del Instituto Nacional de Toxicología, que fija en 100 gramos de marihuana o 25 gramos de hachís la cantidad orientativa para considerar consumo propio.",
      estrategia: "La estrategia se centró en demostrar la atipicidad de la conducta. Se aportó informe pericial que acreditaba que la pureza de la resina y su cantidad eran insignificantes para el tráfico y que no existían útiles de pesaje ni otras evidencias asociadas al comercio. Se invocó el artículo 368 del Código Penal y la doctrina que considera que la mera posesión de droga para consumo propio no es delito. Asimismo, se argumentó que el consumo compartido es atípico si se realiza entre consumidores habituales y no excede el acopio semanal. Ante la ausencia de indicios de ánimo de traficar, se solicitó el archivo.",
      pruebas: "Además de la declaración del investigado, se practicó prueba testifical de un amigo que corroboró que la sustancia iba a ser consumida conjuntamente. El informe del Instituto Nacional de Toxicología acreditó que la cantidad incautada no superaba el límite orientativo de 25 gramos de hachís para consumo propio. No se hallaron básculas, bolsas de dosificación ni dinero procedente de ventas. Todos estos extremos fueron determinantes para descartar el ánimo de traficar.",
      resolucion: "El Magistrado-Juez Ilmo. Sr. Jorge Israel Bartolomé Moriano dictó el Auto nº 2337/2024 con fecha 25 de noviembre de 2024. En la parte dispositiva acordó el sobreseimiento provisional y el archivo de las actuaciones, indicando que sólo se reabrirían si aparecieran nuevos elementos de incriminación. El auto condenó las costas a oficio. Al no presentarse recursos, la resolución devino firme, restituyendo la presunción de inocencia de nuestro cliente.",
      marco_legal: "El artículo 368 del Código Penal castiga el cultivo, elaboración o tráfico de drogas y la posesión destinada a su venta. La jurisprudencia ha establecido que la mera posesión para autoconsumo no es delictiva y que deben concurrir indicios adicionales (fraccionamiento en dosis, material de pesaje, grandes sumas de dinero) para apreciar ánimo de traficar. Las tablas del Instituto Nacional de Toxicología fijan 100 gramos de marihuana y 25 gramos de hachís como límite orientativo para consumo propio. Asimismo, el consumo compartido entre consumidores habituales se considera atípico si no excede el acopio semanal."
    }
  },
  // Caso 14 - ROBO CON VIOLENCIA (Pozuelo de Alarcón)
  14: {
    nombre: "CASO ROBO CON VIOLENCIA (Pozuelo de Alarcón)",
    delito_principal: "Robo con violencia o intimidación",
    resultado: "Auto de sobreseimiento y archivo",
    contenido: {
      resumen: "Nuestro cliente fue investigado por un presunto robo con violencia cometido en Pozuelo de Alarcón. La investigación se inició tras una denuncia en la que la víctima describió a dos individuos que la abordaron en la vía pública. Tras analizar todas las pruebas disponibles, el Juzgado de Instrucción nº 4 de Pozuelo de Alarcón dictó auto de sobreseimiento provisional y archivo de las actuaciones al no existir indicios suficientes de participación de nuestro cliente.",
      hechos: "El procedimiento se originó tras una denuncia por un supuesto robo cometido por dos individuos que habían abordado a la víctima en la vía pública. Las investigaciones policiales no lograron identificar de forma fehaciente a los autores y la víctima no reconoció a nuestro cliente en rueda de reconocimiento. Asimismo, no se hallaron huellas o rastros que vincularan a nuestro patrocinado con el lugar de los hechos.",
      estrategia: "Se hizo valer la inexistencia de indicios de participación. La defensa impugnó la legalidad de las ruedas de reconocimiento por falta de garantías y subrayó la ausencia de pruebas objetivas. Además, se aportó jurisprudencia que exige la prueba de dominio del hecho para enjuiciar un robo con violencia.",
      pruebas: "El atestado policial, la declaración de la víctima y las diligencias de identificación fueron las únicas pruebas disponibles. Todas ellas resultaron insuficientes para sostener una acusación. La investigación no aportó grabaciones ni testigos neutrales. Por ello, la juez consideró que no se acreditaba la participación del investigado.",
      resolucion: "El auto núm. 70/2024 decretó el sobreseimiento provisional y el archivo de las actuaciones respecto de nuestro cliente, sin perjuicio de posibles acciones civiles. La resolución dejó sin efecto cualquier medida cautelar.",
      marco_legal: "Se aplicó el artículo 637.2.º de la Ley de Enjuiciamiento Criminal. La defensa invocó jurisprudencia sobre la necesidad de elementos objetivos para condenar por robo con violencia."
    }
  },
  // Caso 15 - DELITO DE AMENAZAS
  15: {
    nombre: "CASO DELITO DE AMENAZAS - ABSOLUCIÓN",
    delito_principal: "Amenazas (art. 169 CP)",
    resultado: "Sentencia absolutoria",
    contenido: {
      resumen: "Nuestro cliente fue juzgado por un delito de amenazas tras una discusión verbal con un vecino. La acusación particular sostenía que había proferido expresiones intimidatorias que constituían delito. Sin embargo, el Juzgado de lo Penal nº 4 de Madrid, mediante sentencia de 15 de enero de 2024, lo absolvió al considerar que las expresiones no tenían entidad suficiente para intimidar a una persona de normal temperamento.",
      hechos: "Se produjo una discusión verbal entre nuestro cliente y su vecino por cuestiones vecinales. Durante la discusión, se intercambiaron expresiones fuertes, pero sin que se produjera ningún acto de violencia física ni amenaza de daño inminente. La acusación particular interpretó algunas frases como amenazas delictivas, mientras que nuestro cliente sostuvo que se trataba de expresiones impulsivas en el calor de la discusión.",
      estrategia: "La defensa se centró en demostrar que las expresiones no constituían amenazas delictivas. Se argumentó que para que exista delito de amenazas debe concurrir una intimidación idónea capaz de atemorizar a una persona de normal temperamento, y que las frases intercambiadas no reunían esa característica. Se invocó jurisprudencia que diferencia entre expresiones coloquiales y amenazas propiamente dichas.",
      pruebas: "Se practicaron las declaraciones de los implicados y de un vecino que presenció la discusión. Ningún testigo pudo confirmar que las expresiones constituyeran una amenaza real. La defensa aportó jurisprudencia sobre casos similares donde se absolvió por falta de intimidación idónea.",
      resolucion: "El Juzgado de lo Penal nº 4 de Madrid dictó sentencia absolutoria el 15 de enero de 2024. La magistrada consideró que las expresiones proferidas no tenían entidad suficiente para intimidar a una persona de normal temperamento y, por tanto, no constituían delito de amenazas.",
      marco_legal: "El delito de amenazas está tipificado en el artículo 169 del Código Penal. La jurisprudencia exige que la intimidación sea idónea, es decir, capaz de atemorizar a una persona de normal temperamento. Se distingue entre expresiones coloquiales y amenazas propiamente dichas."
    }
  },
  // Caso 16 - FALSIFICACIÓN DE DOCUMENTO
  16: {
    nombre: "CASO FALSIFICACIÓN DE DOCUMENTO PÚBLICO - SOBRESEIMIENTO",
    delito_principal: "Falsificación de documento público",
    resultado: "Auto de sobreseimiento provisional",
    contenido: {
      resumen: "Nuestro cliente fue investigado por un presunto delito de falsificación de documento público tras la presentación de un documento que resultó ser falso. Tras analizar la documentación aportada y las alegaciones de la defensa, el Juzgado de Instrucción nº 8 de Madrid dictó auto de sobreseimiento provisional al no existir indicios suficientes de participación en la falsificación.",
      hechos: "Se presentó un documento público que resultó ser falso en una gestión administrativa. Las investigaciones apuntaron inicialmente hacia nuestro cliente como posible responsable de la falsificación. Sin embargo, la defensa aportó pruebas que demostraban que el documento le había sido facilitado por terceros y que nuestro cliente actuó de buena fe al presentarlo.",
      estrategia: "La defensa se centró en demostrar la buena fe de nuestro cliente y la ausencia de participación en la falsificación. Se aportaron pruebas documentales que acreditaban que el documento fue recibido de terceros y que no existía conocimiento de su falsedad. Se argumentó que la mera presentación de un documento falso no constituye delito si no concurre dolo.",
      pruebas: "Se aportaron contratos y comunicaciones que demostraban que el documento fue recibido de terceros. No existían pruebas de que nuestro cliente hubiera intervenido en la falsificación ni conocimiento de su irregularidad. La defensa presentó testigos que corroboraron la versión de los hechos.",
      resolucion: "El Juzgado de Instrucción nº 8 de Madrid dictó auto de sobreseimiento provisional. La resolución consideró que no existían indicios suficientes para continuar con la investigación y que los hechos no constituían delito.",
      marco_legal: "El delito de falsificación de documento público está regulado en el artículo 390 del Código Penal. Exige dolo específico y participación en la falsificación. La jurisprudencia establece que la mera presentación de un documento falso no es suficiente si no se prueba la intervención en su creación."
    }
  },
  // Caso 17 - DELITO DE DESOBEDIENCIA
  17: {
    nombre: "CASO DESOBEDIENCIA A AUTORIDAD - ARCHIVO",
    delito_principal: "Desobediencia a la autoridad (art. 556 CP)",
    resultado: "Auto de archivo",
    contenido: {
      resumen: "Nuestro cliente fue denunciado por un presunto delito de desobediencia a agentes de la autoridad tras negarse a identificarse en un control policial. El Juzgado de Instrucción nº 12 de Madrid, tras analizar los hechos, dictó auto de archivo al considerar que la conducta no reunía los elementos típicos del delito.",
      hechos: "Los agentes de policía solicitaron la identificación de nuestro cliente en un control rutinario. Nuestro cliente se negó inicialmente a identificarse argumentando que no existía motivo justificado para el control. Tras una discusión, finalmente colaboró con los agentes.",
      estrategia: "La defensa argumentó que la negativa inicial a identificarse no constituía desobediencia grave, ya que no existía orden judicial que justificara el control. Se invocó jurisprudencia que establece que la desobediencia requiere una orden clara y justificada, y que la mera negativa verbal no es suficiente.",
      pruebas: "Se aportaron las declaraciones de los agentes y del cliente. No existían pruebas de violencia o resistencia activa. La defensa demostró que finalmente se produjo la identificación y colaboración.",
      resolucion: "El Juzgado de Instrucción nº 12 de Madrid dictó auto de archivo al considerar que no existían indicios suficientes de delito de desobediencia.",
      marco_legal: "El delito de desobediencia está regulado en el artículo 556 del Código Penal. Requiere una orden clara y justificada, y una resistencia activa y grave."
    }
  },
  // Caso 18 - DELITO DE INJURIAS
  18: {
    nombre: "CASO DELITO DE INJURIAS - SOBRESEIMIENTO",
    delito_principal: "Injuria (art. 205 CP)",
    resultado: "Auto de sobreseimiento provisional",
    contenido: {
      resumen: "Nuestro cliente fue denunciado por un presunto delito de injurias tras unas expresiones vertidas en una discusión familiar. El Juzgado de Instrucción nº 15 de Madrid dictó auto de sobreseimiento provisional al no existir indicios suficientes de delito.",
      hechos: "Se produjo una discusión familiar en la que se intercambiaron expresiones ofensivas. La acusación particular denunció que algunas expresiones constituían injurias delictivas.",
      estrategia: "La defensa argumentó que las expresiones se produjeron en el calor de una discusión familiar y no tenían entidad suficiente para constituir delito. Se invocó el derecho a la libertad de expresión y jurisprudencia que establece límites altos para la protección penal.",
      pruebas: "Se aportaron testimonios de familiares que contextualizaron las expresiones. No existían pruebas de difusión pública ni de ánimo específico de injuriar.",
      resolucion: "El Juzgado de Instrucción nº 15 de Madrid dictó auto de sobreseimiento provisional al considerar que los hechos no constituían delito.",
      marco_legal: "El delito de injuria está regulado en el artículo 205 del Código Penal. La jurisprudencia establece que requiere expresiones graves con ánimo específico de ofender."
    }
  },
  // Caso 19 - ABDERRAHIM AKKOUH – POLICÍA LOCAL DE TORREJÓN
  19: {
    nombre: "CASO ABDERRAHIM AKKOUH – POLICÍA LOCAL DE TORREJÓN",
    delito_principal: "Homicidio imprudente/doloso (investigación)",
    resultado: "Investigación en curso",
    contenido: {
      resumen: "El 18 de junio de 2025, el agente de la Policía Municipal de Madrid Juan C. redujo y mantuvo inmovilizado a Abderrahim Akkouh, quien presuntamente había intentado robarle el móvil en Torrejón de Ardoz. La víctima falleció por anoxia. La jueza de Instrucción n.º 4 imputó al agente por homicidio y le dejó en libertad provisional con medidas cautelares. Nuestro despacho representa a la familia de la víctima como acusación particular, solicitando la calificación de asesinato y el ingreso en prisión preventiva del investigado.",
      hechos: "Los hechos ocurrieron en la tarde del 18 de junio de 2025 en las inmediaciones de una discoteca en Torrejón de Ardoz. El agente Juan C. intervino tras recibir una llamada alertando de un presunto intento de robo. Durante la reducción, el agente aplicó técnicas de inmovilización que causaron la muerte por asfixia de Abderrahim Akkouh. Testigos presenciales grabaron el incidente con sus teléfonos móviles, mostrando una intervención de varios minutos donde la víctima solicitaba auxilio.",
      estrategia: "Como acusación particular en representación de la familia, solicitamos la calificación de los hechos como asesinato (art. 139 CP) por la existencia de alevosía y ensañamiento en la actuación policial. Pedimos la prisión provisional del investigado por riesgo de fuga y reiteración delictiva. Insistimos en la práctica de todas las diligencias necesarias, incluyendo autopsia completa, análisis de las cámaras de seguridad y declaración de todos los testigos.",
      pruebas: "Se han aportado vídeos grabados por vecinos, informes forenses preliminares y declaraciones de testigos. La acusación insiste en recabar las grabaciones completas de cámaras de seguridad. La autopsia preliminar apunta a una muerte violenta por asfixia. La Fiscalía se ha sumado a la petición de calificar los hechos como homicidio doloso.",
      resolucion: "Actualmente, la causa se encuentra en fase de instrucción. La jueza mantiene al investigado en libertad provisional, con retirada de pasaporte y obligación de comparecer semanalmente. La acusación particular continúa impulsando diligencias y prepara recurso para que se revise la calificación y se acuerde prisión provisional.",
      marco_legal: "Se manejan los artículos 138 (homicidio) y 139 (asesinato) del Código Penal, así como el artículo 142 (homicidio imprudente). También se citan los artículos 503 y 504 de la LECrim sobre la prisión provisional y el principio de proporcionalidad en las medidas cautelares."
    }
  },
  // Caso 20 - OPERACIÓN BOP
  20: {
    nombre: "OPERACIÓN BOP",
    delito_principal: "Pertenencia a grupo criminal y robos con violencia",
    resultado: "Auto concediendo libertad provisional",
    contenido: {
      resumen: "La operación «BOP» es una investigación policial centrada en un presunto grupo organizado dedicado al tráfico de estupefacientes. Varios investigados fueron detenidos en 2025 y algunos permanecen en prisión provisional. Nuestro despacho asume la defensa de uno de ellos, sosteniendo que carece de vínculo con la organización y que su detención se debió a una mera relación de amistad con uno de los implicados. El procedimiento está en fase inicial y se están practicando diligencias.",
      hechos: "Según las investigaciones policiales, la organización adquiría grandes cantidades de sustancias estupefacientes para su posterior distribución. Se practicaron entradas y registros en varias localidades de Madrid en los que se intervinieron drogas y dinero en efectivo. Nuestro defendido fue detenido por su presencia en uno de los domicilios registrados, sin que se encontrase droga en su poder.",
      estrategia: "La defensa trabaja en demostrar que la mera presencia del acusado en el domicilio no implica pertenencia a la organización. Se solicitará la libertad provisional con la imposición de fianza, alegando arraigo y falta de antecedentes. Además se pedirá practicar pruebas periciales sobre la titularidad de los bienes incautados y la trazabilidad de las conversaciones intervenidas.",
      pruebas: "Aún se están analizando las diligencias policiales y los atestados. El procedimiento se basa en intervenciones telefónicas, informes de seguimiento y decomisos de droga. La defensa propondrá testigos de descargo y periciales informáticas.",
      resolucion: "Al cierre de este informe, la causa permanece en fase de instrucción. No se ha dictado resolución definitiva respecto de nuestro cliente.",
      marco_legal: "Resultan de aplicación los artículos 368 y siguientes del Código Penal sobre tráfico de drogas y el artículo 570 bis relativo a pertenencia a organización criminal. Se tendrán en cuenta las directrices jurisprudenciales sobre participación mínima y consumación."
    }
  }
};
