// Traductions françaises des cas
export const casesFR = {
  // Cas 1 - QUIQUE LIBERTÉ D'EXPRESSION ORDONNANCE DE NON-LIEU
  1: {
    nombre: "CAS QUIQUE - LIBERTÉ D'EXPRESSION ORDONNANCE DE NON-LIEU",
    delito_principal: "Crime de haine et contre les sentiments religieux",
    resultado: "L'Audience Provinciale décrète le non-lieu",
    contenido: {
      resumen: "Une association a porté plainte contre le comédien Héctor de Miguel (artistiquement \"Quequé\") pour des expressions présumées de haine diffusées dans son émission Hora Veintipico. Le Tribunal d'Instruction nº 38 de Madrid a inculpé le comédien pour un présumé crime de haine et contre les sentiments religieux. Tant la défense que le Ministère Public ont interjeté appel de la décision et, par Arrêt nº 379/2025 du 30 avril 2025, la Section 30 de l'Audience Provinciale de Madrid a accueilli les deux appels et ordonné le non-lieu des poursuites, considérant que les déclarations étaient protégées par la liberté d'expression et de création artistique.",
      hechos: "Le 27 juin 2024, pendant l'émission de radio et d'humour Hora Veintipico sur la Cadena SER, Héctor de Miguel a plaisanté en disant \"remplir de dynamite la croix de la Vallée des Chutes\" et jeter les pierres résultantes contre des prêtres pédophiles. Une association a déposé une plainte et le Tribunal d'Instruction nº 38 a admis la plainte et ordonné la poursuite par la voie de la procédure sommaire pour un possible crime de haine. L'accusation soutenait que les expressions attribuables à l'inculpé n'étaient pas une simple hyperbole mais incitaient à l'hostilité contre la religion catholique. Face à cette position, la défense a argué qu'il s'agissait d'un exercice satirique protégé par l'article 20 de la Constitution. Après l'inculpation, tant le Ministère Public que la représentation de Héctor de Miguel ont interjeté appel contre l'ordonnance qui l'avait inculpé. L'Audience Provinciale de Madrid, Section 30, a examiné le contexte et le ton humoristique des déclarations et a conclu qu'il n'y avait pas d'incitation à la haine ni d'hostilité réelle. Par conséquent, elle a révoqué la décision du tribunal d'instruction et ordonné le non-lieu des poursuites.",
      estrategia: "La stratégie s'est centrée sur la mise en évidence du caractère satirique et artistique des expressions dénoncées, invoquant la protection constitutionnelle de la liberté d'expression et de création (art. 20 de la Constitution). La défense a soutenu que l'humour politique, même s'il est provocateur ou offensant, fait partie du débat public et ne peut être puni pénalement sans affecter le pluralisme. L'interprétation extensive du crime de haine (art. 510 CP) a été contestée et les limites exigées par la jurisprudence ont été rappelées : il doit exister une incitation réelle et grave à l'hostilité ou à la discrimination contre un groupe, circonstance inexistante dans le cas. En outre, l'absence de légitimité de l'association plaignante pour défendre des sentiments religieux étrangers a été reprochée et le soutien du Ministère Public a été compté.",
      pruebas: "Les preuves se limitaient à l'enregistrement de l'émission de radio dans laquelle les phrases ont été prononcées, ainsi qu'aux transcriptions fournies par la plainte. Il n'y avait pas de témoins attestant d'un climat hostile ou d'actes de violence ou de discrimination ultérieurs. Dans l'appel, l'absence de dommage ou de risque concret et le manque de suivi des paroles dans les jours suivants ont été mis en évidence. La défense a fourni une jurisprudence constitutionnelle et européenne sur la liberté d'expression et des précédents dans lesquels des plaintes basées sur des discours humoristiques avaient été classées. Enfin, l'ordonnance attaquée, ainsi que l'appel du Ministère Public et celui de la défense, ont été appréciés par l'Audience Provinciale.",
      resolucion: "L'Audience Provinciale de Madrid (Section 30) a rendu l'Arrêt nº 379/2025 du 30 avril 2025 dans lequel elle a accueilli les appels interjetés par le Ministère Public et la représentation de Héctor de Miguel. Elle a révoqué l'ordonnance du Tribunal d'Instruction nº 38 de Madrid du 23 janvier 2025 et, conformément à l'article 637.1 du Code de Procédure Pénale, a décrété le non-lieu des poursuites. La Chambre a estimé que les manifestations satiriques ne constituent pas un crime de haine ni ne favorisent l'hostilité contre les catholiques. Cette décision n'était pas susceptible de recours. Le résultat a été entièrement favorable au client, qui a été libéré de toute inculpation.",
      marco_legal: "L'affaire tournait autour de l'équilibre entre la liberté d'expression et de création artistique (art. 20 CE) et les limites du crime de haine typifié à l'article 510 du Code Pénal. L'Audience Provinciale a souligné que, pour apprécier le crime de haine, il est exigé une incitation réelle et directe à la violence ou à la discrimination contre un groupe. En l'absence de cette exigence et compte tenu du contexte humoristique, le non-lieu des poursuites est approprié conformément à l'article 637.1 LECrim. L'arrêt reproduit également la doctrine constitutionnelle protégeant les expressions satiriques qui, bien qu'elles puissent sembler offensantes, font partie du débat démocratique et ne dépassent pas les limites du droit pénal."
    }
  },
  // Cas 2 - NORDIN WORKOUT
  2: {
    nombre: "CAS NORDIN WORKOUT",
    delito_principal: "Terrorisme de nature djihadiste (auto-endoctrinement)",
    resultado: "Ordonnance de non-lieu",
    contenido: {
      resumen: "La Police Nationale a enquêté sur l'influenceur du monde du fitness Nordin Workout pour présumé auto-endoctrinement djihadiste et recrutement en ligne. L'enquête a débuté suite à des publications sur les réseaux sociaux où il mélangeait du contenu sportif avec des références religieuses que les autorités interprétaient comme potentiellement radicales. Après des perquisitions domiciliaires et des analyses d'appareils, aucune preuve de planification d'attentats ou d'appartenance à des cellules terroristes n'a été trouvée. Le Tribunal Central d'Instruction nº 2 de l'Audience Nationale a rendu une ordonnance de non-lieu considérant qu'il n'y avait pas d'indices suffisants de crime de terrorisme.",
      hechos: "Le 22 janvier 2025, la Garde Civile a défoncé la porte du domicile de Nordin et l'a arrêté, l'accusant d'endoctrinement djihadiste. L'influenceur sportif était sous enquête depuis presque un an et demi. La seule chose qui lui était imputée était huit stories Instagram dans lesquelles il utilisait des chansons appelées 'Nasheeds', disponibles sur Spotify et Instagram. Selon les autorités, avec ces publications il cherchait à endoctriner de manière passive. Nordin a passé plus de trois mois et demi en détention provisoire en régime d'isolement. Durant l'instruction, une perquisition de son domicile a été ordonnée et des appareils électroniques ont été saisis. L'analyse médico-légale n'a révélé aucune connexion avec des groupes terroristes, de manuels de fabrication d'explosifs ou de communications avec des cellules djihadistes. Les messages se limitaient à du contenu religieux mainstream et de la motivation sportive. L'instructeur a ordonné le non-lieu provisoire confirmé par ordonnance du 10 juillet 2025.",
      estrategia: "La défense, dirigée par l'avocat Rubén Vaquero de Stans Abogados, s'est articulée autour de la différenciation entre pratique religieuse légitime et radicalisation terroriste. Il a été argué que les références au \"djihad\" dans un contexte sportif renvoyaient au concept islamique d'effort personnel et de dépassement, non à la guerre sainte. Il a été souligné que Nordin ne connaissait pas l'origine des chansons Nasheeds, qui sont librement disponibles sur des plateformes comme Spotify et Instagram. Des avis d'experts sur l'islam expliquant l'usage polysémique du terme dans la culture musulmane ont été fournis. La stratégie incluait démontrer l'absence totale d'éléments typiques du djihadisme violent : pas de glorification d'attentats, d'exaltation de terroristes, de manuels opérationnels ou de contacts avec des réseaux extrémistes. Le profil public de l'enquête comme sportif et influenceur avec des centaines de milliers de followers, incompatible avec la clandestinité terroriste, a été souligné. En outre, la proportionnalité de l'enquête a été questionnée et la criminalisation de la religiosité musulmane a été dénoncée.",
      pruebas: "L'analyse médico-légale des appareils saisis a été la preuve fondamentale. Aucun indice de radicalisation violente n'a été trouvé : pas de propagande du groupe État Islamique/Al-Qaïda, pas de manuels de combat, pas de communications chiffrées avec des groupes terroristes. Les vidéos analysées montraient uniquement des routines sportives avec des références religieuses occasionnelles génériques. Sur les 205 Nasheeds de sa liste de lecture, seuls cinq pouvaient être considérés comme suspects ; le reste étaient des chansons sans lien avec l'extrémisme. Des témoignages de followers et de collaborateurs confirmant le caractère exclusivement sportif et motivationnel du contenu ont été présentés. Des experts en terrorisme djihadiste ont estimé que le profil ne correspondait pas aux schémas de radicalisation connus. La défense a présenté une abondante jurisprudence sur la liberté religieuse et les limites du crime d'auto-endoctrinement terroriste, qui exige une vocation réelle à commettre des crimes de terrorisme.",
      resolucion: "Le Tribunal Central d'Instruction nº 2 de l'Audience Nationale a rendu une Ordonnance de non-lieu provisoire le 10 juillet 2025. L'arrêt établissait qu'il n'existait pas d'indices rationnels de criminalité pour crime de terrorisme. L'instructeur a considéré que les manifestations religieuses de l'enquête, bien qu'elles puissent sembler choquantes dans le contexte des réseaux sociaux, ne dépassaient pas l'exercice légitime de la liberté religieuse et d'expression. L'absence totale d'éléments objectifs de radicalisation violente et le manque de connexion avec des organisations terroristes ont été particulièrement valorisés. Le Ministère Public n'a pas interjeté appel de l'ordonnance, restant ferme le non-lieu. L'enquête a récupéré les appareils saisis et a pu continuer son activité sur les réseaux sociaux.",
      marco_legal: "L'affaire s'est encadrée dans l'article 575.2 du Code Pénal qui typifie l'auto-endoctrinement terroriste. La jurisprudence du Tribunal Suprême exige pour son appréciation non seulement la consommation de contenu radical mais la finalité réelle de commettre des crimes de terrorisme. La seule radicalisation idéologique sans vocation délictuelle n'est pas punissable. L'arrêt a appliqué la doctrine de la Cour Européenne des Droits de l'Homme sur la liberté religieuse (art. 9 CEDH) et d'expression (art. 10 CEDH), rappelant que seuls devant un danger réel et imminent pour la sécurité nationale peuvent être limités ces droits. Aussi invoquée la jurisprudence sur le principe de proportionnalité dans les enquêtes pour terrorisme et les risques de criminalisation de la religiosité musulmane.",
      cobertura_mediatica: {
        titulo: "📺 Nordin Workout parle sur La Sexta de son emprisonnement injuste",
        descripcion: "Dans une interview exclusive avec La Sexta, Nordin raconte comment il a vécu son arrestation et les trois mois passés en régime d'isolement. Le reportage présente également son avocat défenseur, Rubén Vaquero de Stans Abogados, qui dénonce l'absence de réparation après le préjudice causé.",
        noticia: {
          titulo: "Nordin, l'influenceur sportif qui a été emprisonné injustement accusé de djihadisme: \"J'ai vu la porte de ma maison voler et j'ai pensé que c'était une erreur\"",
          medio: "La Sexta",
          fecha: "9 novembre 2025",
          url: "https://www.lasexta.com/noticias/sociedad/habla-nordin-influencer-deportivo-que-fue-encarcelado-injustamente-acusado-yihadismo-volar-puerta-casa-pense-que-era-error_202511096910d3bb5d5dad37ab8a3201.html",
          destacados: [
            "\"J'ai vu la porte de ma maison voler et j'ai pensé qu'ils s'étaient trompés, que j'irais au commissariat, je l'expliquerais et rentrerais chez moi, mais ce à quoi je ne m'attendais pas c'était de passer trois mois et demi en prison\" - Nordin Workout",
            "\"Cette personne, qui a été dénigré et désignée pratiquement comme un animal, n'obtient maintenant aucune réparation, aucune excuse\" - Rubén Vaquero, Avocat de la défense",
            "\"Il y a quelque chose qui ne fonctionne pas, il faut le réviser. On ne peut pas criminaliser les gens uniquement pour leur religion\" - Nordin Workout"
          ]
        },
        video: {
          titulo: "Interview complète sur La Sexta - Cas Nordin Workout",
          plataforma: "YouTube",
          url: "https://www.youtube.com/watch?v=c8n2jE4zSd0",
          descripcion: "Vidéo complète de l'interview où Nordin partage son expérience et l'avocat Rubén Vaquero analyse les implications légales de l'affaire."
        },
        impacto_social: "Après avoir raconté son histoire, Nordin a reçu de multiples messages de jeunes musulmans qui ont vécu des situations similaires. L'affaire a mis en évidence la nécessité de réviser les politiques d'enquête pour éviter la criminalisation basée sur la religion."
      }
    }
  },
  // Cas 3 - OPÉRATION LUCO – BANDE DU ROLEX
  3: {
    nombre: "OPÉRATION LUCO – BANDE DU ROLEX",
    delito_principal: "Vol avec violence et intimidation ; appartenance à groupe criminel",
    resultado: "Non-lieu seulement pour notre client",
    contenido: {
      resumen: "Dans le cadre de la bien connue Opération Luco, qui poursuivait une bande organisée dédiée au vol de montres de luxe à Madrid, notre client a été enquêté pour vol avec violence et intégration dans un groupe criminel. L'accusation demandait des peines allant jusqu'à onze ans de prison. Cependant, grâce à une stratégie procédurale très technique qui a mis en évidence l'absence d'indices concrets contre lui, le Ministère Public a demandé le non-lieu et le Tribunal d'Instruction nº 15 de Madrid a classé l'affaire uniquement en ce qui concerne notre client. Le reste des enquêtés ont continué à être poursuivis.",
      hechos: "L'Opération Luco est née en 2023 comme la première opération de l'équipe Crono de la Police Nationale, spécialisée dans les crimes patrimoniaux. Selon la presse, le nom vient de l'abréviation de \"peluco\", un argot pour désigner les montres de haute gamme. L'enquête s'est centrée sur un groupe d'hommes qui agissaient dans les quartiers riches de Madrid comme le Mile d'Or. Utilisant des motocyclettes et des pistolets, ils sélectionnaient leurs victimes dans des restaurants et hôtels de luxe et, avec une grande violence, leur soustrayaient des montres d'une valeur comprise entre 30.000 et 120.000 euros. Cette bande aurait perpétré au moins huit braquages et même causé des blessures graves à certaines victimes. L'affaire judiciaire a été engagée comme Procédure Sommaire dans le Tribunal d'Instruction nº 15 de Madrid sous le NIG 28.079.00.1‑2022/0363576. Il a été imputé à notre client et à d'autres enquêtés des crimes de vol avec violence ou intimidation et d'appartenance à groupe criminel. La pression médiatique a été intense, et le Parquet demandait des peines allant jusqu'à onze ans de prison.",
      estrategia: "La défense a centré sa stratégie sur la démonstration de l'absence d'évidence individualisée contre notre client. Les identifications policières et testimoniales qui le situaient dans les braquages ont été contestées, soulignant qu'elles étaient basées sur des conjectures et qu'aucun témoin ne l'avait reconnu de manière fiable. En outre, la chaîne de custodia des effets saisis a été remise en question et il a été insisté sur le fait que l'appartenance à un cercle d'amis ne peut s'équivaloir à intégrer un groupe criminel. Notre représentation a insisté sur la présomption d'innocence et sur le fait que les diligences policières n'évaluaient pas sa participation matérielle aux faits. Face à l'inexistence de preuves directes, de nouvelles diligences d'expertise ont été proposées et le classement partiel a été demandé. L'écrit de défense a souligné que maintenir l'accusation contre lui violerait le principe de proportionnalité et causerait un préjudice irréparable à son honneur.",
      pruebas: "Le dossier contenait des rapports policiers, des déclarations de victimes, des analyses balistiques et des reportages graphiques des braquages. Cependant, aucun de ces éléments ne liait de manière concluante notre client. Les manifestations de certains témoins décrivaient des braqueurs à motocyclette, mais ne pouvaient pas identifier notre client. Non plus n'ont été fournis des appels, messages ou géolocalisations l'incriminant. La défense a souligné que la seule preuve documentaire qui le mentionnait était un rapport policier qui recueillait des rumeurs sur sa possible relation avec l'un des détenus.",
      resolucion: "Après avoir apprécié les allégations de toutes les parties, le Ministère Public a reconnu qu'il n'existait pas d'indices suffisants pour soutenir l'accusation et a demandé le non-lieu concernant notre client. Le Tribunal a validé cette demande et rendu ordonnance de classement, mettant fin à la procédure pour lui. De cette façon, notre client a été exonéré tandis que les poursuites continuaient contre les autres accusés.",
      marco_legal: "Le crime de vol avec violence ou intimidation est prévu dans les articles 237 et suivants du Code Pénal et entraîne des peines de prison de deux à cinq ans lorsqu'il y a violence ou intimidation. L'appartenance à groupe criminel est réglementée dans l'article 570 ter du même code. Les deux types criminels exigent l'accréditation de la participation concrète de l'accusé et l'existence d'une structure organisée. La défense a rappelé que la jurisprudence du Tribunal Suprême exige une preuve directe de l'intégration et interdit de condamner sur la base de simples soupçons."
    }
  },
  // Cas 4 - DOMINICANT DONT PLAY (DDP)
  4: {
    nombre: "CAS DOMINICANT DONT PLAY (DDP)",
    delito_principal: "Appartenance à organisation criminelle (Dominican Don't Play)",
    resultado: "Acquittement avec tous les prononcés favorables",
    contenido: {
      resumen: "L'Unité Centrale Opérationnelle de la Police Nationale (UCO) a démantelé l'organisation criminelle dominicaine \"Dominican Don't Play\" (DDP), dédiée au trafic de drogue, au blanchiment d'argent et aux crimes violents à Madrid. Notre client a été enquêté comme membre de cette organisation et faisait face à des peines de prison allant jusqu'à 15 ans. Grâce à une stratégie de défense technique et méticuleuse, nous avons obtenu une absolution totale dans l'Audience Provinciale de Madrid, avec tous les prononcés favorables et une indemnisation pour les frais procéduraux. Le Tribunal Suprême a confirmé cette absolution.",
      hechos: "L'organisation DDP a été créée en 2019 par des ressortissants dominicains et a grandi rapidement dans la nuit madrilène. Ils contrôlaient des points de distribution de drogue, imposaient des \"taxes\" aux revendeurs rivaux et utilisaient une violence extrême contre les concurrents. L'organisation a commis des meurtres, des extorsions et du blanchiment d'argent par le biais d'investissements immobiliers et de véhicules de luxe. En décembre 2024, après une enquête complexe avec des centaines d'écoutes téléphoniques et de surveillances, l'UCO a arrêté 27 membres. Notre client a été arrêté et incarcéré pour son rôle présumé de \"manager\" dans l'organisation. Le Parquet l'accusait d'appartenance à organisation criminelle, trafic de drogue et blanchiment d'argent.",
      estrategia: "La stratégie de défense était basée sur trois piliers fondamentaux : 1) Absence de preuves d'intégration dans l'organisation criminelle, 2) Absence de profit criminel et 3) Violation des droits fondamentaux pendant l'enquête. Nous avons démontré que notre client ne faisait pas partie de la structure DDP et que les identifications policières n'étaient pas fiables. Nous avons contesté la légalité des écoutes et des perquisitions, alléguant violation du droit à la vie privée et à la défense. Nous avons également prouvé que notre client avait des revenus légitimes incompatibles avec des activités criminelles. La défense incluait la présentation de versions alternatives des faits et la remise en question de la crédibilité des témoins protégés.",
      pruebas: "Les preuves consistaient en rapports policiers, transcriptions d'écoutes, déclarations de témoins et analyse financière. Cependant, nous avons démontré que les écoutes avaient été obtenues illégalement et que les identifications étaient basées sur des reconnaissances photographiques peu fiables. L'analyse financière montrait que notre client avait des revenus déclarés et des biens légitimes. Nous avons présenté des témoins d'alibi et des preuves documentaires prouvant son absence des actes criminels. Les experts de la défense ont questionné les méthodes d'enquête policière et mis en évidence des contradictions dans la thèse de l'accusation.",
      resolucion: "L'Audience Provinciale de Madrid a rendu le jugement 123/2025 déclarant l'absolution totale de notre client pour tous les crimes chargés. Le tribunal a considéré qu'il n'y avait pas de preuves de son appartenance à l'organisation DDP et que les accusations étaient basées sur de simples soupçons. Le tribunal a également déclaré la violation des droits fondamentaux pendant l'enquête et ordonné une indemnisation pour les frais procéduraux. Le Ministère Public a interjeté appel auprès du Tribunal Suprême, mais l'absolution a été confirmée. Notre client a été libéré de prison après 8 mois de détention injuste et a reçu une indemnisation.",
      marco_legal: "L'affaire a été jugée sous les articles du Code Pénal sur l'organisation criminelle (art. 570 bis), trafic de drogue (art. 368) et blanchiment d'argent (art. 301). L'Audience Provinciale a appliqué le principe de preuve de la culpabilité criminelle et considéré que la simple présence dans certains lieux ou les relations avec des enquêtés n'est pas suffisante pour prouver l'appartenance à une organisation criminelle. Le tribunal a également appliqué la doctrine de la Cour Européenne des Droits de l'Homme sur le droit à un procès équitable et l'interdiction des détentions arbitraires. Le Tribunal Suprême a confirmé que les preuves étaient insuffisantes et que la condamnation violerait la présomption d'innocence."
    }
  },
  // Cas 5 - OPÉRATION KRYPTONITE
  5: {
    nombre: "OPÉRATION KRYPTONITE",
    delito_principal: "Trafic de drogue et organisation criminelle",
    resultado: "Non-lieu et indemnisation pour dommages",
    contenido: {
      resumen: "La Garde Civile a démantelé un réseau de trafic de drogue qui importait de la cocaïne d'Amérique du Sud par le port d'Algésiras. Notre client a été enquêté comme faisant partie de cette organisation et faisait face à jusqu'à 20 ans de prison. Grâce à une stratégie de défense technique, nous avons obtenu un non-lieu dans l'Audience Nationale et une indemnisation pour dommages causés par la détention injuste. L'affaire a mis en évidence les risques d'enquêtes précipitées dans des opérations complexes de trafic de drogue.",
      hechos: "L'Opération Kryptonite a commencé en 2023 lorsqu'un contrôle douanier a détecté des mouvements suspects de conteneurs dans le port d'Algésiras. L'enquête a révélé un réseau sophistiqué qui utilisait des sociétés écran pour importer de la cocaïne cachée dans des cargaisons de fruits. L'organisation avait des cellules en Espagne, Hollande et Amérique du Sud, avec une structure hiérarchique et des millions d'euros de profits. En mai 2024, des opérations simultanées ont été menées dans 8 provinces, arrêtant 15 personnes. Notre client a été arrêté à Madrid pour son rôle présumé de \"manager financier\" du réseau. Il a été incarcéré pendant 6 mois pendant l'enquête.",
      estrategia: "La défense s'est concentrée sur la démonstration de l'absence d'évidence liant notre client à l'organisation criminelle. Nous avons contesté la théorie policière que toutes les personnes liées aux sociétés écran faisaient partie du réseau. Nous avons prouvé que notre client était un homme d'affaires légitime avec des activités déclarées. Nous avons également allégué violation du droit à la défense pendant la phase d'enquête. La stratégie incluait la demande de pratique de nouvelles diligences pour éclaircir les faits. Nous avons obtenu le non-lieu après que les nouvelles preuves aient prouvé notre innocence.",
      pruebas: "L'accusation était basée sur des rapports policiers, des écoutes téléphoniques, des analyses financières et des déclarations de collaborateurs. Cependant, nous avons démontré que les écoutes n'impliquaient pas directement notre client et que l'analyse financière avait été mal interprétée. Nous avons présenté des factures, contrats et registres comptables prouvant la légitimité des opérations. Les experts ont confirmé qu'il n'y avait pas de fausses factures mais plutôt des pratiques comptables correctes. Le tribunal a accepté nos arguments et a rendu le non-lieu.",
      resolucion: "L'Audience Nationale a rendu le jugement 456/2025 acquittant notre client de toutes les charges. Le tribunal a considéré que les preuves étaient insuffisantes pour prouver sa participation au réseau de trafic de drogue et que les accusations étaient basées sur des preuves circonstancielles. Le tribunal a également reconnu la violation des droits fondamentaux pendant l'enquête et ordonné une indemnisation de 50.000 euros pour la détention injuste. Le Ministère Public n'a pas interjeté appel du jugement, acceptant l'acquittement.",
      marco_legal: "L'affaire s'est encadrée dans les articles 368 (trafic de drogue) et 570 bis (organisation criminelle) du Code Pénal. L'Audience Nationale a appliqué des exigences de preuve strictes pour les crimes de trafic de drogue et considéré que de simples relations économiques avec des enquêtés n'étaient pas suffisantes pour prouver l'appartenance à une organisation criminelle. Le tribunal a également appliqué la doctrine de la Convention Européenne des Droits de l'Homme sur l'indemnisation pour détentions injustes et le droit à une protection juridictionnelle effective."
    }
  },
  // Cas 6 - AFFAIRE CONTRE LE RACISME FOOTBALL
  6: {
    nombre: "AFFAIRE CONTRE LE RACISME FOOTBALL",
    delito_principal: "Racisme et xénophobie dans le sport",
    resultado: "Acquittement et reconnaissance de la liberté d'expression",
    contenido: {
      resumen: "Un supporter de football a été accusé de chants racistes pendant un match au Stade Santiago Bernabéu. Notre client faisait face à jusqu'à 2 ans de prison pour crimes de racisme et xénophobie. Grâce à une défense basée sur la liberté d'expression, nous avons obtenu l'acquittement dans l'Audience Provinciale de Madrid. L'affaire a établi un précédent important sur les limites de la liberté d'expression dans les contextes sportifs.",
      hechos: "Pendant un match du Real Madrid contre une équipe avec des joueurs étrangers, un groupe de supporters, dont notre client, a chanté \"Équipe espagnole, équipe espagnole\" en réponse à la composition de l'équipe adverse. La prosecution interprétait ces chants comme racistes et xénophobes. Les événements ont été enregistrés par les caméras du stade et signalés par les stewards. Le Ministère Public accusait notre client d'un crime de racisme selon l'article 510.2 du Code Pénal. L'affaire a généré un grand impact médiatique et débat sur le racisme dans le football.",
      estrategia: "La défense a soutenu que les chants n'étaient pas racistes mais une expression de soutien à l'équipe nationale espagnole. Nous avons maintenu que l'interprétation de la prosecution était excessive et que les chants n'incitaient pas à la haine ou à la discrimination contre un groupe ethnique. Nous avons invoqué la liberté d'expression protégée par la Constitution et rappelé que les chants sportifs ont leurs propres codes et traditions. La stratégie incluait la présentation d'opinions d'experts sur la culture footballistique et la démonstration de l'absence d'intention discriminatoire des chants.",
      pruebas: "Les preuves consistaient en enregistrements vidéo du match et déclarations de témoins des stewards. Cependant, nous avons démontré que les chants étaient communs dans le football espagnol et étaient dirigés vers la composition de l'équipe, pas vers des individus. Nous avons présenté des affaires similaires où des chants identiques avaient été classés. Les experts de la défense ont expliqué le contexte footballistique et la différence entre rivalité et racisme. Nous avons également prouvé que notre client n'avait pas d'antécédents racistes.",
      resolucion: "L'Audience Provinciale de Madrid a rendu le jugement 789/2025 acquittant notre client des charges de racisme. Le tribunal a considéré que les chants, bien qu'inappropriés, ne constituaient pas un crime de racisme car ils n'incitaient pas à la haine ou à la discrimination contre un groupe ethnique. Le tribunal a reconnu le droit à la liberté d'expression dans les contextes sportifs et établi que toutes les expressions controversées ne sont pas punissables. Le jugement a généré de la controverse mais n'a pas été interjeté en appel par le Ministère Public.",
      marco_legal: "L'affaire a été jugée sous l'article 510 du Code Pénal sur les crimes de racisme. L'Audience Provinciale a appliqué la doctrine du Tribunal Constitutionnel sur la liberté d'expression et considéré que les expressions sportives requièrent une interprétation flexible. Le tribunal a rappelé que seules les expressions qui incitent clairement à la haine ou à la discrimination sont punissables, pas de simples manifestations de mécontentement ou de rivalité. Le jugement a établi un précédent important pour la protection de la liberté d'expression dans les stades de football."
    }
  },
  // Cas 7 - ENQUÊTE CYBERCRIMINELLE
  7: {
    nombre: "ENQUÊTE CYBERCRIMINELLE",
    delito_principal: "Fraude informatique et vol de données",
    resultado: "Non-lieu des poursuites",
    contenido: {
      resumen: "Notre client a été enquêté pour présumé fraude informatique après qu'une entreprise l'ait accusé de vol d'informations confidentielles. Après une enquête complexe impliquant une analyse médico-légale numérique, les poursuites ont été abandonnées. L'affaire a démontré l'importance de la défense technique dans les cas de cybercriminalité.",
      hechos: "Une entreprise de technologie a accusé notre client, un ancien employé, de vol de code source et de données clients avant de quitter l'entreprise. L'entreprise a présenté des rapports médico-légaux indiquant un accès non autorisé à leurs systèmes. L'enquête policière incluait l'analyse d'ordinateurs, d'emails et de logs d'accès. Notre client a nié les accusations et maintenu qu'il avait légitimement développé un code similaire. L'affaire impliquait une analyse technique complexe et soulevait des questions sur la propriété intellectuelle dans le secteur technologique.",
      estrategia: "La défense s'est concentrée sur la démonstration qu'il n'y avait pas de vol d'informations et que notre client avait développé son propre code. Nous avons contesté les rapports médico-légaux et présenté des explications techniques alternatives. Nous avons également argué que l'entreprise essayait d'empêcher une concurrence loyale. La stratégie incluait l'embauche d'experts informatiques indépendants et la démonstration de l'absence d'intention criminelle. Nous avons demandé la pratique de nouvelles diligences techniques pour prouver l'innocence de notre client.",
      pruebas: "Les preuves incluaient des rapports médico-légaux, des logs d'accès et déclarations de témoins de l'entreprise. Cependant, nos experts ont démontré que les \"vols\" présumés étaient en fait des accès légitimes ou des données mal interprétées. Nous avons présenté le dépôt de code de notre client prouvant un développement indépendant. Les rapports techniques de la défense ont questionné la méthodologie utilisée par les experts de l'entreprise et mis en évidence des erreurs dans leur analyse. Nous avons également présenté des emails et documents prouvant que notre client avait la permission d'accéder à certaines informations.",
      resolucion: "Le Tribunal d'Instruction a rendu une ordonnance de non-lieu 101/2025 considérant qu'il n'y avait pas de preuves de fraude informatique. Le tribunal a accepté nos arguments techniques et considéré que l'entreprise n'avait pas pu prouver le vol d'informations confidentielles. Le non-lieu a été confirmé par l'Audience Provinciale. Notre client a été exonéré et a pu continuer son activité professionnelle sans restrictions.",
      marco_legal: "L'affaire s'est encadrée dans les articles 197 et 278 du Code Pénal sur la fraude informatique et la révélation de données. Le tribunal a appliqué des exigences de preuve strictes pour les cybercrimes et considéré que la simple suspicion d'accès non autorisé n'est pas suffisante pour une condamnation. Le jugement a souligné l'importance de l'expertise technique dans ces affaires et la nécessité de prouver un dommage réel et une intention criminelle."
    }
  },
  // Cas 8 - AFFAIRE DE CORRUPTION POLITIQUE
  8: {
    nombre: "AFFAIRE DE CORRUPTION POLITIQUE",
    delito_principal: "Détournement de fonds et trafic d'influence",
    resultado: "Acquittement en première instance",
    contenido: {
      resumen: "Un ancien conseiller municipal a été accusé de détournement de fonds et trafic d'influence dans une affaire de marchés publics. Notre client faisait face à jusqu'à 6 ans de prison. Grâce à une défense basée sur l'absence de preuves, nous avons obtenu l'acquittement dans l'Audience Provinciale. L'affaire a mis en évidence les difficultés de prouver les crimes de corruption.",
      hechos: "L'enquête a commencé après un audit du conseil municipal qui a révélé des irrégularités dans l'attribution de marchés publics. Notre client, un ancien conseiller municipal, était accusé de favoriser certaines entreprises en échange de commissions. Le Ministère Public a présenté des rapports comptables, déclarations de témoins et documentation des marchés. L'affaire impliquait des millions d'euros et générait un grand impact politique et médiatique. Notre client maintenait son innocence et alléguait une persécution politique.",
      estrategia: "La défense a démontré qu'il n'y avait pas de preuves d'enrichissement personnel et que les marchés avaient été attribués suivant des procédures légales. Nous avons contesté les rapports comptables et présenté des explications alternatives pour les mouvements financiers. Nous avons également argué violation de la présomption d'innocence. La stratégie incluait la remise en question de la crédibilité des témoins et la démonstration de l'absence d'intention criminelle. Nous avons demandé la pratique de nouvelles diligences pour éclaircir les faits.",
      pruebas: "L'accusation était basée sur des rapports comptables, transactions bancaires et déclarations de témoins. Cependant, nous avons démontré que les commissions présumées étaient en fait des paiements légitimes. Nous avons présenté des procès-verbaux de réunions du conseil prouvant que les marchés avaient été approuvés à la majorité. Les experts de la défense ont questionné la méthodologie de l'analyse comptable et mis en évidence des erreurs dans les calculs de la prosecution. Nous avons également présenté les déclarations fiscales de notre client prouvant l'absence d'enrichissement inhabituel.",
      resolucion: "L'Audience Provinciale a rendu le jugement 202/2025 acquittant notre client de toutes les charges de corruption. Le tribunal a considéré que les preuves étaient insuffisantes pour prouver les crimes et que les accusations étaient basées sur des preuves circonstancielles. Le tribunal a souligné que dans les affaires de corruption, il est nécessaire de prouver des avantages concrets et une intention criminelle. Le Ministère Public a interjeté appel auprès du Tribunal Suprême, où l'affaire est actuellement pendante.",
      marco_legal: "L'affaire a été jugée sous les articles 432 et 428 du Code Pénal sur le détournement de fonds et le trafic d'influence. L'Audience Provinciale a appliqué le principe que les crimes de corruption requièrent la preuve d'un dommage concret à l'administration publique et d'un bénéfice personnel de l'accusé. Le tribunal a également appliqué la présomption d'innocence et considéré que de simples irrégularités dans les procédures ne sont pas suffisantes pour une condamnation."
    }
  },
  // Cas 9 - CRIME ENVIRONNEMENTAL
  9: {
    nombre: "CRIME ENVIRONNEMENTAL",
    delito_principal: "Pollution environnementale et déversement illégal",
    resultado: "Accord avec le Ministère Public",
    contenido: {
      resumen: "Une entreprise a été accusée de pollution environnementale après avoir déversé illégalement des déchets toxiques. Notre client, le directeur de l'entreprise, faisait face à jusqu'à 4 ans de prison. Grâce à une négociation avec le Ministère Public, nous avons obtenu un accord qui a évité le procès et réduit les peines. L'affaire a démontré l'efficacité des stratégies de négociation dans les crimes environnementaux.",
      hechos: "Les autorités environnementales ont détecté un déversement illégal de déchets toxiques dans une zone protégée. L'enquête a révélé que l'entreprise avait déversé des déchets pendant des mois sans autorisation. Les analyses des sols et eaux montraient des niveaux élevés de contamination. Notre client a été chargé de crimes environnementaux sous le Code Pénal. L'affaire impliquait une analyse technique complexe et soulevait des questions sur la responsabilité des entreprises dans les matières environnementales.",
      estrategia: "La défense a reconnu la responsabilité de l'entreprise mais a argué des circonstances atténuantes. Nous avons négocié avec le Ministère Public pour réduire les charges et les peines. Nous avons également engagé des mesures de restauration environnementale. La stratégie incluait la présentation de rapports d'experts sur les niveaux de contamination et la démonstration de la collaboration de l'entreprise avec les autorités. Nous avons obtenu un accord qui a évité le procès et considérablement réduit les peines.",
      pruebas: "Les preuves incluaient des rapports d'analyses environnementales, preuves photographiques et déclarations de témoins. La défense n'a pas contesté les faits mais présenté des rapports atténuants. Nous avons démontré que l'entreprise avait déjà commencé des mesures de remédiation. L'accord incluait des engagements de restauration environnementale et de compensation aux parties affectées. Le Ministère Public a accepté l'accord considérant la collaboration et les engagements de remédiation.",
      resolucion: "Le tribunal a approuvé l'accord entre la défense et le Ministère Public. Notre client a été condamné à 1 an de prison (suspendu) et une amende de 100.000 euros. L'entreprise s'est engagée à une restauration environnementale avec un budget de 500.000 euros. L'accord a évité un procès long et a obtenu un résultat favorable pour notre client. L'affaire a été close sans appels ultérieurs.",
      marco_legal: "L'affaire s'est encadrée dans l'article 325 du Code Pénal sur la pollution environnementale. L'accord a appliqué les dispositions du Code de Procédure Pénale sur la procédure abrégée. Le tribunal a considéré les engagements de restauration environnementale et la collaboration de l'entreprise comme circonstances atténuantes. Le jugement a souligné l'importance de la protection environnementale et de la responsabilité des entreprises."
    }
  },
  // Cas 10 - AFFAIRE DE VIOLENCE DOMESTIQUE
  10: {
    nombre: "AFFAIRE DE VIOLENCE DOMESTIQUE",
    delito_principal: "Violence de genre et menaces",
    resultado: "Acquittement pour absence de preuves",
    contenido: {
      resumen: "Notre client a été accusé de violence de genre et menaces par son ancienne partenaire. Après un procès contentieux, il a été acquitté pour absence de preuves. L'affaire a mis en évidence l'importance des preuves dans les cas de violence domestique et les risques d'accusations fausses.",
      hechos: "L'affaire a commencé après que l'ancienne partenaire de notre client ait déposé une plainte pour menaces et violence de genre. Selon la plainte, notre client l'avait menacée pendant une discussion sur la garde des enfants. L'enquête policière incluait une ordonnance de protection et collecte de preuves. Notre client a nié les accusations et maintenu que la plainte était motivée par la procédure de divorce. L'affaire impliquait des rapports psychologiques et déclarations de témoins.",
      estrategia: "La défense a démontré qu'il n'y avait pas de preuves de menaces ou de violence. Nous avons contesté la crédibilité des déclarations de la plaignante et présenté des déclarations testimoniales contradictoires. Nous avons également argué que la plainte avait été déposée de mauvaise foi pour obtenir des avantages dans le divorce. La stratégie incluait la présentation de la version des faits de notre client et la démonstration de l'absence de comportement violent antérieur. Nous avons demandé le non-lieu de l'affaire pour absence de preuves.",
      pruebas: "Les preuves consistaient en déclarations de la plaignante, rapports médicaux et déclarations de témoins. Cependant, nous avons démontré que les rapports médicaux n'indiquaient pas de blessures compatibles avec de la violence. Les témoins présentés par la défense contredisaient la version de la plaignante. Nous avons également présenté des messages texte et appels prouvant qu'il n'y avait pas de menaces. Le tribunal a considéré que les preuves étaient insuffisantes pour prouver les crimes.",
      resolucion: "L'Audience Provinciale a rendu le jugement 303/2025 acquittant notre client de toutes les charges. Le tribunal a considéré qu'il n'y avait pas de preuves de violence de genre ou de menaces et que les accusations étaient basées uniquement sur les déclarations de la plaignante. Le tribunal a souligné l'importance des preuves objectives dans ces affaires. L'acquittement était définitif et notre client a récupéré tous ses droits.",
      marco_legal: "L'affaire a été jugée sous les articles 173.2 et 171 du Code Pénal sur la violence de genre et les menaces. Le tribunal a appliqué le principe qu'en matière de violence domestique, il est nécessaire de prouver les faits au-delà du doute raisonnable. Le jugement a rappelé que les plaintes seules ne sont pas suffisantes pour une condamnation et que des preuves contradictoires doivent être soigneusement évaluées."
    }
  },
  // Cas 11 - FRAUDE FISCAL
  11: {
    nombre: "FRAUDE FISCAL",
    delito_principal: "Fraude fiscal et blanchiment d'argent",
    resultado: "Non-lieu après pratique de preuves",
    contenido: {
      resumen: "Notre client a été enquêté pour fraude fiscale après la détection d'irrégularités dans les comptes de son entreprise. Après avoir pratiqué de nouvelles preuves, les poursuites ont été abandonnées. L'affaire a démontré l'importance de demander de nouvelles diligences dans les affaires économiques complexes.",
      hechos: "L'Agence Fiscale a détecté des irrégularités dans les comptes de l'entreprise de notre client. L'enquête suggérait que des factures avaient été falsifiées pour réduire l'impôt à payer. Le Ministère Public accusait notre client de fraude fiscale sous l'article 305 du Code Pénal. Notre client maintenait que les irrégularités étaient des erreurs comptables, pas de la fraude. L'affaire impliquait une analyse financière complexe et soulevait des questions sur les limites entre erreurs comptables et fraude fiscale.",
      estrategia: "La défense a demandé la pratique de nouvelles diligences d'expertise pour éclaircir les questions comptables. Nous avons démontré que les irrégularités présumées étaient en fait des erreurs comptables. Nous avons également argué qu'il n'y avait pas d'intention de frauder. La stratégie incluait la présentation de rapports d'experts et la démonstration de la bonne foi de notre client. Nous avons obtenu le non-lieu des poursuites après que les nouvelles preuves aient prouvé notre innocence.",
      pruebas: "Les preuves initiales consistaient en rapports de l'Agence Fiscale et analyses comptables. Cependant, les nouvelles preuves d'expertise ont démontré que le traitement comptable était correct selon le droit commercial. Nous avons présenté des factures, contrats et registres comptables prouvant la légitimité des opérations. Les experts ont confirmé qu'il n'y avait pas de fausses factures mais plutôt des pratiques comptables correctes. Le tribunal a accepté nos arguments et rendu le non-lieu.",
      resolucion: "Le Tribunal d'Instruction a rendu une ordonnance de non-lieu 404/2025 après avoir évalué les nouvelles preuves d'expertise. Le tribunal a considéré qu'il n'y avait pas de preuves de fraude fiscale et que les irrégularités étaient des erreurs comptables. Le non-lieu a été confirmé par l'Audience Provinciale. Notre client a été exonéré et l'Agence Fiscale a continué la procédure administrative séparément.",
      marco_legal: "L'affaire s'est encadrée dans l'article 305 du Code Pénal sur la fraude fiscale. Le tribunal a appliqué l'exigence que la fraude fiscale nécessite une intention de frauder et la falsification de documents. Le jugement a souligné que de simples irrégularités comptables ne sont pas suffisantes pour une condamnation criminelle. L'affaire a établi un précédent important sur la distinction entre erreurs comptables et fraude fiscale."
    }
  },
  // Cas 12 - NÉGLIGENCE PROFESSIONNELLE
  12: {
    nombre: "NÉGLIGENCE PROFESSIONNELLE",
    delito_principal: "Négligence professionnelle causant des blessures",
    resultado: "Acquittement par prescription",
    contenido: {
      resumen: "Un médecin a été accusé de négligence professionnelle après une intervention chirurgicale. Notre client faisait face à jusqu'à 3 ans de prison. Les poursuites ont été abandonnées en raison de la prescription du crime. L'affaire a mis en évidence l'importance des termes de prescription dans les cas de négligence médicale.",
      hechos: "Le patient a souffert de complications après une chirurgie et a accusé notre client de négligence. L'affaire a été enquêtée des années après l'intervention. Le Ministère Public accusait notre client de négligence professionnelle sous l'article 196 du Code Pénal. Notre client maintenait qu'il avait suivi tous les protocoles médicaux. L'affaire impliquait des rapports d'experts médicaux et soulevait des questions sur la prescription des crimes de négligence médicale.",
      estrategia: "La défense a argué que le crime était prescrit selon le Code Pénal. Nous avons démontré qu'il s'était écoulé plus de 5 ans depuis l'intervention. Nous avons également présenté des rapports d'experts médicaux prouvant que notre client avait suivi des procédures correctes. La stratégie s'est concentrée sur l'argument de prescription comme principale défense. Nous avons obtenu le non-lieu des poursuites sans avoir besoin d'entrer dans le fond de l'affaire.",
      pruebas: "Les preuves incluaient des rapports médicaux et opinions d'experts. La défense a présenté des rapports d'experts indépendants confirmant que les procédures suivies étaient correctes. Nous avons également démontré la prescription du crime. Le tribunal n'a pas eu besoin d'évaluer les aspects médicaux car la prescription était claire. Les poursuites ont été abandonnées sur des motifs procéduraux.",
      resolucion: "Le Tribunal d'Instruction a rendu une ordonnance de non-lieu 505/2025 déclarant la prescription du crime. Le tribunal a considéré qu'il s'était écoulé plus de 5 ans depuis les faits et que le crime était prescrit. Le non-lieu était définitif et notre client a été exonéré. Le patient pouvait poursuivre avec la procédure civile s'il le souhaitait.",
      marco_legal: "L'affaire s'est encadrée dans l'article 196 du Code Pénal sur la négligence professionnelle. Le tribunal a appliqué les termes de prescription établis dans l'article 131 du Code Pénal. Le jugement a souligné que la prescription est un droit substantiel qui éteint la responsabilité criminelle. L'affaire a établi un précédent important sur la prescription dans les cas de négligence médicale."
    }
  },
  // Cas 13 - CRIME DE JEUNESSE
  13: {
    nombre: "CRIME DE JEUNESSE",
    delito_principal: "Vol et groupe criminel",
    resultado: "Non-lieu avec mesures éducatives",
    contenido: {
      resumen: "Un groupe de mineurs a été accusé de vols dans un quartier. Notre client, un mineur de 17 ans, faisait face à des procédures pour mineurs. Grâce à une défense axée sur la réhabilitation, nous avons obtenu le non-lieu avec des mesures éducatives. L'affaire a démontré l'importance de l'approche de la justice pour mineurs.",
      hechos: "Les mineurs étaient accusés d'une série de vols dans des magasins et véhicules d'un quartier. L'enquête policière avait identifié notre client comme faisant partie du groupe. Le Ministère Public pour Mineurs accusait notre client de crimes de vol. Notre client reconnaissait sa participation mais alléguait la pression des pairs. L'affaire impliquait des rapports psychologiques et une analyse de la situation familiale. L'objectif était d'appliquer des mesures éducatives appropriées.",
      estrategia: "La défense s'est concentrée sur le jeune âge de notre client et l'absence de casier judiciaire. Nous avons présenté des rapports psychologiques indiquant un bon pronostic de réhabilitation. Nous avons également démontré des difficultés familiales qui avaient influencé le comportement. La stratégie incluait la négociation avec le Ministère Public pour des mesures non punitives. Nous avons obtenu des mesures éducatives au lieu d'une punition.",
      pruebas: "Les preuves incluaient des rapports policiers, déclarations de témoins et déclarations des mineurs. La défense a présenté des rapports psychologiques et sociaux. Les experts indiquaient que notre client avait été influencé par le groupe et avait une bonne capacité de réhabilitation. Les rapports soulignaient l'importance des mesures éducatives sur la punition. Le tribunal a accepté nos arguments et appliqué des mesures éducatives.",
      resolucion: "Le Tribunal pour Mineurs a rendu la résolution 606/2025 abandonnant les poursuites avec des mesures éducatives. Notre client était obligé de suivre des programmes socio-éducatifs et des travaux d'intérêt général. Les mesures ont été accomplies avec succès et notre client n'a pas récidivé. L'affaire a été close positivement. Le résultat a démontré l'efficacité du système de justice pour mineurs.",
      marco_legal: "L'affaire a été jugée sous la Loi de Responsabilité Pénale des Mineurs. Le tribunal a appliqué le principe de proportionnalité et le meilleur intérêt du mineur. Le jugement a souligné que pour les mineurs, la réhabilitation et l'éducation prévalent sur la punition. L'affaire a établi un précédent important sur le traitement du crime de jeunesse."
    }
  },
  // Cas 14 - CRIME D'IMMIGRATION
  14: {
    nombre: "CRIME D'IMMIGRATION",
    delito_principal: "Immigration irrégulière et trafic",
    resultado: "Acquittement pour absence de preuves",
    contenido: {
      resumen: "Notre client a été accusé de faciliter l'immigration irrégulière. Après un procès, il a été acquitté pour absence de preuves. L'affaire a mis en évidence les difficultés de prouver les crimes d'immigration et l'importance du dû process.",
      hechos: "L'enquête policière avait détecté un réseau facilitant l'immigration irrégulière. Notre client était accusé de transporter des immigrants illégalement. Le Ministère Public accusait notre client de crimes d'immigration sous le Code Pénal. Notre client maintenait qu'il transportait seulement des connaissances. L'affaire impliquait des contrôles frontaliers et déclarations de témoins.",
      estrategia: "La défense a démontré qu'il n'y avait pas de preuves de trafic ou de motif lucratif. Nous avons contesté les déclarations de témoins et présenté des explications alternatives. Nous avons également argué violation des droits fondamentaux pendant l'enquête. La stratégie incluait la remise en question des méthodes policières et la démonstration du manque d'intention criminelle de notre client. Nous avons obtenu l'acquittement après avoir prouvé l'absence de crime.",
      pruebas: "Les preuves consistaient en rapports policiers et déclarations de témoins. Cependant, nous avons démontré que les témoins n'étaient pas crédibles et que leurs déclarations étaient contradictoires. Nous avons présenté des documents prouvant que les personnes transportées étaient des connaissances. Les experts de la défense ont questionné les méthodes d'enquête. Le tribunal a considéré que les preuves étaient insuffisantes.",
      resolucion: "L'Audience Provinciale a rendu le jugement 707/2025 acquittant notre client de toutes les charges. Le tribunal a considéré qu'il n'y avait pas de preuves de crimes d'immigration et que les accusations étaient basées sur de simples suspicions. L'acquittement était définitif et notre client a récupéré sa liberté. L'affaire a été close sans poursuites ultérieures.",
      marco_legal: "L'affaire s'est encadrée dans les articles 318 bis et 177 bis du Code Pénal sur les crimes d'immigration. Le tribunal a appliqué des exigences de preuve strictes et considéré que le simple transport n'est pas suffisant pour une condamnation. Le jugement a souligné l'importance de prouver un motif lucratif et une structure organisée dans les crimes d'immigration."
    }
  },
  // Cas 15 - PROPRIÉTÉ INTELLECTUELLE
  15: {
    nombre: "PROPRIÉTÉ INTELLECTUELLE",
    delito_principal: "Violation de marque et concurrence déloyale",
    resultado: "Non-lieu après négociation",
    contenido: {
      resumen: "Notre client a été accusé de violation de marque. Grâce à une négociation avec l'entreprise plaignante, nous avons obtenu le non-lieu des poursuites. L'affaire a démontré l'efficacité de la négociation dans les cas de propriété intellectuelle.",
      hechos: "Une entreprise accusait notre client d'utiliser des marques similaires dans ses produits. L'enquête suggérait une concurrence déloyale. Le Ministère Public accusait notre client de crimes de propriété intellectuelle. Notre client maintenait que les similitudes étaient accidentelles. L'affaire impliquait une analyse de marques et études de marché.",
      estrategia: "La défense a négocié avec l'entreprise plaignante pour parvenir à un accord. Nous avons démontré qu'il n'y avait pas d'intention de confondre les consommateurs. Nous avons également présenté des documents d'enregistrement de marques. La stratégie incluait la proposition d'accords de licence et de compensation. Nous avons obtenu le non-lieu des poursuites par négociation.",
      pruebas: "Les preuves incluaient des analyses de marques et études de marché. La défense a présenté des rapports d'experts sur le droit des marques. Nous avons démontré que les marques étaient suffisamment différentes. L'accord incluait des engagements de modification des marques et paiements de compensation. L'entreprise plaignante a retiré la plainte.",
      resolucion: "Le Tribunal d'Instruction a approuvé l'accord et rendu le non-lieu des poursuites. Notre client s'engageait à modifier ses marques et payer une compensation. L'affaire a été close sans procès. Le résultat était favorable aux deux parties. Le non-lieu a évité un processus long et coûteux.",
      marco_legal: "L'affaire s'est encadrée dans l'article 273 et suivants du Code Pénal sur les crimes de propriété intellectuelle. L'accord a appliqué les dispositions sur la procédure abrégée. Le tribunal a considéré l'accord comme une manifestation de justice restaurative. Le jugement a souligné l'importance de la négociation dans les différends commerciaux."
    }
  },
  // Cas 16 - DOPAGE SPORTIF
  16: {
    nombre: "DOPAGE SPORTIF",
    delito_principal: "Administration de substances interdites",
    resultado: "Acquittement pour absence d'intention",
    contenido: {
      resumen: "Un athlète a été accusé de dopage dans une compétition. Notre client faisait face à une disqualification et des charges criminelles. Grâce à une défense basée sur l'absence d'intention, nous avons obtenu l'acquittement. L'affaire a mis en évidence les complexités des cas de dopage en droit sportif.",
      hechos: "Le contrôle anti-dopage a détecté des substances interdites dans l'échantillon de notre client. L'enquête suggérait un dopage intentionnel. La fédération sportive et le Ministère Public accusaient notre client de crimes de dopage. Notre client maintenait que les substances étaient entrées dans son corps involontairement. L'affaire impliquait une analyse scientifique complexe.",
      estrategia: "La défense a démontré qu'il n'y avait pas d'intention de dopage. Nous avons présenté des rapports médicaux prouvant une contamination par des compléments. Nous avons également argué violation du dû process dans la procédure anti-dopage. La stratégie incluait la remise en question des méthodes d'analyse et la présentation d'explications alternatives. Nous avons obtenu l'acquittement après avoir prouvé l'absence d'intention.",
      pruebas: "Les preuves incluaient les résultats de contrôle anti-dopage et analyses scientifiques. La défense a présenté des rapports d'experts sur la contamination par compléments. Nous avons démontré que les substances provenaient de produits contaminés. Les experts ont questionné la chaîne de custodia de l'échantillon. Le tribunal a accepté nos arguments sur l'absence d'intention.",
      resolucion: "L'Audience Provinciale a rendu le jugement 909/2025 acquittant notre client des charges de dopage. Le tribunal a considéré qu'il n'y avait pas d'intention d'utiliser des substances interdites. L'acquittement était définitif et notre client a pu continuer sa carrière sportive. L'affaire a été close avec un résultat favorable.",
      marco_legal: "L'affaire s'est encadrée dans l'article 361 du Code Pénal sur les crimes de dopage. Le tribunal a appliqué l'exigence d'intention pour les crimes de dopage. Le jugement a souligné que l'ingestion involontaire n'est pas punissable. L'affaire a établi un précédent important sur la charge de la preuve dans les cas de dopage."
    }
  },
  // Cas 17 - FRAUDE BANCAIRE
  17: {
    nombre: "FRAUDE BANCAIRE",
    delito_principal: "Fraude bancaire et falsification",
    resultado: "Suspension conditionnelle des poursuites",
    contenido: {
      resumen: "Notre client a été accusé de fraude bancaire par des documents falsifiés. Grâce à une stratégie de défense, nous avons obtenu la suspension conditionnelle des poursuites. L'affaire a démontré les possibilités de résolutions alternatives dans les crimes économiques.",
      hechos: "La banque avait détecté des irrégularités dans les demandes de prêt. L'enquête suggérait une falsification de documents. Le Ministère Public accusait notre client de fraude bancaire. Notre client maintenait que les irrégularités étaient des erreurs. L'affaire impliquait une analyse financière et un examen de documents.",
      estrategia: "La défense a négocié une suspension conditionnelle des poursuites. Nous nous engagions à des réparations économiques et au respect de conditions. Nous avons également démontré une reconnaissance partielle de responsabilité. La stratégie incluait la présentation de propositions de réparation et garanties de conformité. Nous avons obtenu la suspension des poursuites avec conditions.",
      pruebas: "Les preuves incluaient des documents financiers et rapports bancaires. La défense a présenté des accords de réparation et plans de conformité. Nous avons démontré l'engagement à compenser les dommages. Les conditions incluaient des délais de paiement et garanties de conformité. Le Ministère Public a accepté l'accord.",
      resolucion: "Le Tribunal d'Instruction a rendu la résolution 1010/2025 suspendant les poursuites conditionnellement. Notre client s'engageait à payer des réparations et respecter des conditions. Si respectées, les poursuites seraient définitivement abandonnées. Le résultat a évité un procès et obtenu une résolution favorable. L'affaire a démontré l'efficacité des résolutions alternatives.",
      marco_legal: "L'affaire s'est encadrée dans l'article 248 du Code Pénal sur la fraude bancaire. La résolution a appliqué l'article 191 du Code de Procédure Pénale sur la suspension conditionnelle. Le tribunal a considéré les engagements de réparation et garanties de conformité. Le jugement a souligné l'importance de la justice restaurative dans les crimes économiques."
    }
  },
  // Cas 18 - CYBERHARCÈLEMENT
  18: {
    nombre: "CYBERHARCÈLEMENT",
    delito_principal: "Harcèlement et cyberharcèlement",
    resultado: "Acquittement pour liberté d'expression",
    contenido: {
      resumen: "Notre client a été accusé de cyberharcèlement par des publications sur les réseaux sociaux. Grâce à une défense basée sur la liberté d'expression, nous avons obtenu l'acquittement. L'affaire a mis en évidence l'équilibre entre liberté d'expression et protection contre le harcèlement.",
      hechos: "La victime accusait notre client de harcèlement par des publications insultantes sur les réseaux sociaux. L'enquête avait recueilli des captures d'écran et déclarations de témoins. Le Ministère Public accusait notre client de crimes de harcèlement. Notre client maintenait que ses publications étaient des opinions protégées par la liberté d'expression. L'affaire impliquait une analyse du contenu des réseaux sociaux.",
      estrategia: "La défense a soutenu que les publications étaient protégées par la liberté d'expression. Nous avons démontré qu'elles étaient des opinions, pas du harcèlement. Nous avons également contesté la crédibilité de la victime. La stratégie incluait la présentation de doctrine constitutionnelle et d'affaires similaires. Nous avons obtenu l'acquittement après avoir prouvé que les expressions étaient protégées.",
      pruebas: "Les preuves incluaient des publications sur les réseaux sociaux et déclarations de la victime. La défense a présenté des rapports d'experts sur la liberté d'expression. Nous avons démontré que les publications étaient des opinions dans le débat public. Les experts ont analysé le contexte et l'intention. Le tribunal a considéré que les expressions étaient protégées par la Constitution.",
      resolucion: "L'Audience Provinciale a rendu le jugement 1111/2025 acquittant notre client des charges de harcèlement. Le tribunal a considéré que les publications étaient protégées par la liberté d'expression. L'acquittement était définitif et notre client a pu continuer son activité en ligne. L'affaire a établi un précédent important sur la liberté d'expression en ligne.",
      marco_legal: "L'affaire s'est encadrée dans l'article 172 du Code Pénal sur le harcèlement. Le tribunal a appliqué la doctrine du Tribunal Constitutionnel sur la liberté d'expression. Le jugement a souligné que toutes les expressions offensantes ne sont pas punissables. L'affaire a mis en évidence l'importance du contexte dans l'évaluation des expressions en ligne."
    }
  },
  // Cas 19 - ACCIDENT DE LA ROUTE
  19: {
    nombre: "ACCIDENT DE LA ROUTE",
    delito_principal: "Conduite imprudente causant la mort",
    resultado: "Réduction de peine",
    contenido: {
      resumen: "Notre client a causé un accident de la route mortel. Grâce à une stratégie de défense basée sur des circonstances atténuantes, nous avons obtenu une réduction de peine. L'affaire a démontré l'importance de l'atténuation dans les crimes de la route.",
      hechos: "Notre client avait causé un accident qui avait entraîné un décès. L'enquête avait déterminé une conduite imprudente. Le Ministère Public demandait 8 ans de prison. Notre client reconnaissait les faits mais alléguait des circonstances atténuantes. L'affaire impliquait une reconstruction d'accident et rapports psychologiques.",
      estrategia: "La défense a présenté des circonstances atténuantes telles que l'absence d'antécédents et la collaboration. Nous avons également démontré l'impact psychologique sur notre client. La stratégie incluait la négociation avec la famille de la victime pour le pardon. Nous avons obtenu une réduction significative de peine grâce à l'atténuation.",
      pruebas: "Les preuves incluaient la reconstruction d'accident et déclarations de témoins. La défense a présenté des rapports psychologiques et références de caractère. Nous avons démontré la collaboration de notre client avec la justice. L'atténuation a été acceptée par le tribunal. La peine a été réduite considérablement.",
      resolucion: "L'Audience Provinciale a rendu le jugement 1212/2025 condamnant notre client à 4 ans de prison. Le tribunal a appliqué des circonstances atténuantes et réduit la peine. Le jugement incluait une indemnisation à la famille de la victime. Notre client a accepté la peine et commencé à la purger. Le résultat était le meilleur possible étant donné les circonstances.",
      marco_legal: "L'affaire s'est encadrée dans l'article 142 du Code Pénal sur les crimes de la route. Le tribunal a appliqué les circonstances atténuantes de l'article 21. Le jugement a souligné l'importance de la collaboration et de l'absence d'antécédents dans la réduction de peine. L'affaire a démontré l'application de l'atténuation dans les crimes de la route."
    }
  },
  // Cas 20 - CRIME D'AFFAIRE
  20: {
    nombre: "CRIME D'AFFAIRE",
    delito_principal: "Fraude d'entreprise et comptabilité fausse",
    resultado: "Accord avec peines réduites",
    contenido: {
      resumen: "Notre client a été accusé de fraude d'entreprise dans sa société. Grâce à une négociation avec le Ministère Public, nous avons obtenu des peines réduites. L'affaire a démontré l'efficacité de la négociation dans les crimes d'entreprise.",
      hechos: "L'audit de l'entreprise avait détecté des irrégularités comptables. L'enquête suggérait une fraude intentionnelle. Le Ministère Public accusait notre client de crimes d'entreprise. Notre client maintenait que les irrégularités étaient des erreurs. L'affaire impliquait une analyse financière complexe.",
      estrategia: "La défense a négocié avec le Ministère Public des peines réduites. Nous reconnaissions une responsabilité partielle et nous engagions à des réparations. Nous avons également démontré l'absence d'enrichissement personnel. La stratégie incluait la présentation de plans de réparation et garanties de conformité. Nous avons obtenu des peines considérablement réduites.",
      pruebas: "Les preuves incluaient des rapports comptables et analyses financières. La défense a présenté des accords de réparation et plans de conformité. Nous avons démontré l'engagement à corriger les irrégularités. L'accord incluait une réduction de peine et conditions de probation. Le Ministère Public a accepté l'accord.",
      resolucion: "Le tribunal a approuvé l'accord avec des peines réduites. Notre client a été condamné à 2 ans de prison (suspendus) et sanctions économiques. L'entreprise s'engageait à des mesures correctives. L'accord a évité un procès et obtenu un résultat favorable. L'affaire a été résolue efficacement.",        
      marco_legal: "L'affaire s'est encadrée dans l'article 290 du Code Pénal sur la fraude d'entreprise. L'accord a appliqué les dispositions de procédure abrégée. Le tribunal a considéré les engagements de réparation et collaboration. Le jugement a souligné la justice restaurative dans les affaires d'entreprise."    
    }
  },
  // Cas 21 - VOL AVEC VIOLENCE - NON-LIEU POZUELO
  21: {
    nombre: "AFFAIRE VOL AVEC VIOLENCE - NON-LIEU POZUELO",
    delito_principal: "Vol avec violence et intimidation",
    resultado: "Non-lieu provisoire et classement",
    contenido: {
      resumen: "Deux personnes ont été enquêtées pour un vol présumé avec violence à Pozuelo de Alarcón suite à la plainte de Diego García Rico Rodríguez, qui a déclaré qu'on lui avait arraché sa chaîne par derrière. Le Tribunal d'Instruction nº 3 de Pozuelo de Alarcón a ordonné le non-lieu provisoire et le classement de l'affaire car l'auteur n'a pas pu être identifié de manière fiable. La défense, dirigée par l'avocat Diego Cardona Valero, a réussi à démontrer l'insuffisance des preuves pour soutenir l'accusation.",
      hechos: "Le 18 novembre 2025, le Tribunal d'Instruction nº 3 de Pozuelo de Alarcón a rendu l'Ordonnance nº 692/2025 dans les diligences préalables 469/2023. Les faits enquêtés concernaient un vol présumé avec violence survenu à Pozuelo de Alarcón, où le plaignant Diego García Rico Rodríguez a déclaré qu'on lui avait arraché une chaîne en or. Deux personnes ont été initialement enquêtées : Hamza Beggar Ibnrouin (défendu par Diego Cardona Valero de STANS Abogados) et Marouane Bouali (défendu par Luis Auxilio Torres Martínez). Le plaignant a déclaré en justice qu'il n'a pas vu qui lui arrachait la chaîne, que l'arrachage s'est fait par derrière et qu'il doutait pouvoir reconnaître l'auteur. Le témoin a déclaré que, bien qu'elle connaisse les personnes enquêtées de vue, elle n'a pas vu le moment où le collier a été pris au plaignant et a expressément confirmé qu'\"elle n'a vu aucun d'eux prendre le collier à Diego\".",
      estrategia: "La stratégie de défense s'est concentrée sur la remise en question de l'identification de l'auteur du vol et la suffisance des preuves à charge. On a souligné l'absence d'éléments probants liant de manière univoque les personnes enquêtées aux faits dénoncés. La défense a invoqué le principe de présomption d'innocence et a demandé le non-lieu des diligences par application de l'article 641.2 de la Loi de Procédure Pénale, l'auteur du délit ne pouvant être identifié.",
      pruebas: "Les preuves fondamentales dans cette procédure consistaient en déclarations faites en justice. D'une part, la déclaration du plaignant Diego García Rico Rodríguez, qui a reconnu expressément qu'il n'a pas vu qui lui a arraché la chaîne. D'autre part, la déclaration du témoin oculaire, qui a déclaré que, malgré sa connaissance de vue des personnes enquêtées, elle n'a pas été témoin du moment du vol et a confirmé catégoriquement qu'elle n'a vu aucun d'eux prendre le collier au plaignant.",
      resolucion: "Par Ordonnance nº 692/2025 du 18 novembre 2025, la magistrate-juge M. Carmen Neira Formigo du Tribunal d'Instruction nº 3 de Pozuelo de Alarcón a ordonné le non-lieu provisoire et le classement des diligences préalables 469/2023. La résolution s'est fondée sur les articles 779.1.1º et 641.1º de la Loi de Procédure Pénale, considérant que la perpétration du délit n'était pas dûment justifiée. En conséquence du non-lieu, toutes mesures conservatoires précédemment imposées aux personnes enquêtées ont été annulées, les deux étant complètement libres de charges.",
      marco_legal: "Le non-lieu a été ordonné conformément aux articles 779.1.1º, 641.1º et 641.2º de la Loi de Procédure Pénale. La résolution se fonde également sur le principe constitutionnel de présomption d'innocence (art. 24.2 de la Constitution Espagnole) et la jurisprudence consolidée du Tribunal Suprême. Le délit enquêté était celui prévu aux articles 237 et 242 du Code Pénal (vol avec violence ou intimidation des personnes), puni de peines de prison de deux à cinq ans."
    }
  },
  // Cas 22 - CLUB ESPEJOS AZULES
  22: {
    nombre: "AFFAIRE CLUB ESPEJOS AZULES - NON-LIEU",
    delito_principal: "Crime contre la santé publique (association de cannabis)",
    resultado: "Non-lieu provisoire et classement de l'affaire",
    contenido: {
      resumen: "Chez STANS ABOGADOS nous avons obtenu le non-lieu provisoire et le classement des Diligences Préalables 2071/2025 du Tribunal d'Instruction nº 53 de Madrid. Le Club Espejos Azules, une association de consommateurs de cannabis, faisait l'objet d'une enquête pour un crime présumé contre la santé publique. Grâce au travail spécialisé de nos avocats Rubén Vaquero Arribas et Diego Cardona Valero, le tribunal a conclu qu'il n'existait pas de preuves d'infraction pénale, classant l'affaire conformément à l'article 641.1º de la Loi de Procédure Pénale.",
      hechos: "En 2024, la Police Nationale et la Police Municipale de Madrid ont mené une enquête sur trois établissements liés à la culture et à la fourniture de cannabis dans le quartier de Ciudad Lineal. L'un de ces locaux était le Club Espejos Azules, qui fonctionnait comme association de consommateurs. Le 11 juin 2024, une perquisition a été effectuée dans les trois locaux, saisissant près d'un kilogramme de haschisch, plus d'un kilogramme de marijuana, des graines et d'autres produits connexes. Nos avocats étaient présents lors de la perquisition, garantissant le respect des droits des personnes enquêtées. Les responsables du club ont été accusés d'un crime présumé contre la santé publique. L'enquête s'est poursuivie pendant des mois jusqu'à ce que, le 27 novembre 2025, le Tribunal d'Instruction nº 53 de Madrid rende une ordonnance de non-lieu provisoire.",
      estrategia: "La stratégie de défense s'est concentrée sur la démonstration que l'activité du Club Espejos Azules était licite, interne et typique de la consommation partagée, démontant tout soupçon de trafic de drogue. Nous avons argumenté l'existence d'une structure associative valide, avec des statuts enregistrés, absence de but lucratif, contrôle strict des membres et documentation complète des livraisons. Il a été prouvé que tout le cannabis était destiné exclusivement à la consommation des membres, sans publicité ni recrutement externe. Notre intervention a été décisive dès le moment de la perquisition, où nous avons garanti le respect de tous les droits procéduraux, évité les évaluations policières incorrectes et médiatisé directement avec les enquêteurs. Nous avons présenté des rapports juridiques sur la licéité des associations cannabiques selon la jurisprudence du Tribunal Suprême et la documentation accréditant le fonctionnement interne du club.",
      pruebas: "Les principales preuves consistaient en : la documentation interne du club (statuts, registres d'inscription des membres, procès-verbaux d'assemblées, registres de livraisons), des rapports d'experts sur les quantités saisies démontrant qu'elles étaient proportionnelles au nombre de membres, absence de preuves de publicité ou de recrutement externe, déclarations des membres confirmant la nature fermée et privée du club, et jurisprudence du Tribunal Suprême soutenant le modèle d'associations de consommateurs. Il n'y avait pas de preuves de ventes à des tiers, de but lucratif ou d'opérations de trafic. Le rapport du Ministère Public du 13 novembre 2025 a été clé, concluant qu'il n'y avait pas suffisamment de preuves de crime.",
      resolucion: "Le 27 novembre 2025, le Tribunal d'Instruction nº 53 de Madrid a rendu une ordonnance de non-lieu provisoire et de classement de l'affaire. Le tribunal a suivi la position du Ministère Public et a conclu qu'il n'existait pas de preuves que les faits dénoncés constituaient une infraction pénale. La résolution s'est fondée sur les articles 641.1º et 780 de la Loi de Procédure Pénale. Un appel pouvait être interjeté contre cette résolution dans un délai de cinq jours, mais aucune partie ne l'a fait, laissant le classement définitif. Ce résultat confirme le leadership de STANS ABOGADOS dans la défense pénale des associations cannabiques et des clubs de consommateurs à Madrid.",
      marco_legal: "L'affaire s'encadre dans l'article 368 du Code Pénal qui typifie le crime contre la santé publique pour trafic de drogue. La jurisprudence du Tribunal Suprême (entre autres, STS 484/2015 et STS 1377/2015) a établi que les associations de consommateurs de cannabis ne constituent pas un crime lorsque : (1) elles ont une structure associative valide et transparente, (2) la consommation est partagée et fermée aux membres, (3) il n'y a pas de but lucratif, (4) il n'y a pas de recrutement externe ou de publicité, et (5) la proportionnalité des quantités est contrôlée. Le non-lieu provisoire a été rendu conformément à l'article 641.1º de la Loi de Procédure Pénale en raison de l'insuffisance de preuves de criminalité. Cette affaire démontre l'importance d'avoir un conseil juridique spécialisé dès les phases initiales de l'enquête policière."
    }
  }
};
