// Traducciones de casos en español
export const casesES = {
  // Caso 1 - QUEQUE ABOGADOS CRISTIANOS SOBRESEIMIENTO
  1: {
    nombre: "CASO- QUEQUE ABOGADOS CRISTIANOS SOBRESEIMIENTO",
    delito_principal: "Delito de odio y contra los sentimientos religiosos",
    resultado: "La Audiencia Provincial decreta el Sobreseimiento",
    contenido: {
      resumen: "La asociación ultracatólica Abogados Cristianos interpuso querella contra el humorista Héctor de Miguel (artísticamente \"Quequé\") por supuestas expresiones de odio vertidas en su programa Hora Veintipico. El Juzgado de Instrucción nº 38 de Madrid procesó al cómico por un presunto delito de odio y contra los sentimientos religiosos. Tanto la defensa como el Ministerio Fiscal recurrieron la decisión y, mediante Auto nº 379/2025 de 30 de abril de 2025, la Sección 30 de la Audiencia Provincial de Madrid estimó ambos recursos y ordenó el sobreseimiento libre de las actuaciones al considerar que las manifestaciones se encontraban amparadas por la libertad de expresión y de creación artística.",
      hechos: "El 27 de junio de 2024, durante el programa radiofónico y de humor Hora Veintipico de la Cadena SER, Héctor de Miguel bromeó con \"llenar de dinamita la cruz del Valle de los Caídos\" y arrojar las piedras resultantes contra sacerdotes pederastas. La asociación Abogados Cristianos presentó una querella y el Juzgado de Instrucción nº 38 admitió a trámite la acusación y acordó la continuación por el trámite del procedimiento abreviado por un posible delito de odio. La acusación sostuvo que las expresiones atribuibles al investigado no eran una mera hipérbole sino que incitaban a la hostilidad contra la religión católica. Frente a esa postura, la defensa alegó que se trataba de un ejercicio satírico protegido por el artículo 20 de la Constitución. Tras la incoación, tanto el Ministerio Fiscal como la representación de Héctor de Miguel interpusieron recurso de apelación contra el auto que le había procesado. La Audiencia Provincial de Madrid, Sección 30, examinó el contexto y el tono humorístico de las manifestaciones y concluyó que no existía incitación al odio ni hostilidad real. Por ello revocó la decisión instructora y ordenó el sobreseimiento libre de la causa.",
      estrategia: "La estrategia se centró en resaltar el carácter satírico y artístico de las expresiones denunciadas, invocando la protección constitucional de la libertad de expresión y de creación (art. 20 de la Constitución Española). La defensa argumentó que el humor político, incluso cuando resulta provocador u ofensivo, forma parte del debate público y no puede castigarse penalmente sin afectar al pluralismo. Se impugnó la interpretación expansiva del delito de odio (art. 510 CP) y se recordaron los límites exigidos por la jurisprudencia: debe existir una incitación real y grave a la hostilidad o violencia contra un colectivo, circunstancia inexistente en el caso. Además se reprochó al querellante utilizar el proceso penal para coartar la crítica y se sostuvo la falta de legitimación de una asociación privada para defender sentimientos religiosos ajenos. La defensa contó con el respaldo del Ministerio Fiscal, que también recurrió el procesamiento.",
      pruebas: "Las pruebas se limitaron a la grabación del programa de radio en el que se pronunciaron las frases, así como a las transcripciones aportadas por la querellante. No existían testigos que acreditasen un clima hostil posterior ni actos de violencia o discriminación. En el recurso se destacó la inexistencia de daño o riesgo concreto y la ausencia de seguimiento de las palabras en los días posteriores. La defensa aportó jurisprudencia constitucional y europea sobre libertad de expresión y precedentes en los que se archivaron denuncias basadas en discursos humorísticos. Finalmente, el auto apelado, junto con el recurso del Ministerio Fiscal y el de la defensa, fueron valorados por la Audiencia Provincial.",
      resolucion: "La Audiencia Provincial de Madrid (Sección 30) dictó el Auto nº 379/2025 de 30 de abril de 2025 en el que estimó los recursos de apelación interpuestos por el Ministerio Fiscal y la representación de Héctor de Miguel. Revocó el auto del Juzgado de Instrucción nº 38 de Madrid de 23 de enero de 2025 y, conforme al artículo 637.1 de la Ley de Enjuiciamiento Criminal, decretó el sobreseimiento libre de la causa. La Sala entendió que las manifestaciones satíricas no constituyen delito de odio ni fomentan la hostilidad contra los católicos. Contra esta resolución no cabía recurso. El resultado fue plenamente favorable para el cliente, que quedó liberado de cualquier imputación.",
      marco_legal: "El caso giró en torno al equilibrio entre la libertad de expresión y creación artística (art. 20 CE) y los límites del delito de odio tipificado en el artículo 510 del Código Penal. La Audiencia Provincial subrayó que, para apreciar el delito de odio, se exige una incitación real y directa a la violencia o discriminación contra un colectivo. En ausencia de tal requisito y ante el contexto humorístico, procede el sobreseimiento libre con apoyo en el artículo 637.1 LECrim. La resolución también reproduce doctrina constitucional que protege expresiones satíricas que, aunque puedan resultar ofensivas, forman parte del debate democrático y no sobrepasan los límites del derecho penal."
    }
  },
  // Caso 2 - NORDIN WORKOUT
  2: {
    nombre: "CASO NORDIN WORKOUT",
    delito_principal: "Terrorismo de índole yihadista (autoadoctrinamiento)",
    resultado: "Auto de Sobreseimiento",
    contenido: {
      resumen: "La Policía Nacional investigó a un influencer del mundo del fitness conocido como Nordin Workout por supuesto autoadoctrinamiento yihadista y captación online. La investigación se inició por publicaciones en redes sociales donde mezclaba contenido deportivo con referencias religiosas que las autoridades interpretaron como potencialmente radicales. Tras registros domiciliarios y análisis de dispositivos, no se encontraron pruebas de planificación de atentados ni pertenencia a células terroristas. El Juzgado Central de Instrucción nº 2 de la Audiencia Nacional dictó auto de sobreseimiento al no apreciar indicios suficientes de delito de terrorismo.",
      hechos: "En marzo de 2025, la Comisaría General de Información de la Policía Nacional inició una investigación sobre el influencer conocido como Nordin Workout tras detectar publicaciones en Instagram y TikTok que combinaban rutinas de ejercicio con mensajes religiosos islámicos. Las autoridades interpretaron que algunos contenidos podrían constituir indicios de radicalización yihadista, especialmente vídeos donde hablaba de \"preparación física para la yihad\" que él defendía como referencias espirituales al esfuerzo personal. Se ordenó la entrada y registro en su domicilio donde se incautaron dispositivos electrónicos. El análisis forense no reveló conexiones con grupos terroristas, manuales de fabricación de explosivos ni comunicaciones con células yihadistas. Los mensajes se limitaban a contenido religioso mainstream y motivación deportiva. El instructor acordó el sobreseimiento provisional que fue confirmado por auto del 10 de julio de 2025.",
      estrategia: "La defensa se articuló en torno a la diferenciación entre práctica religiosa legítima y radicalización terrorista. Se argumentó que las referencias a la \"yihad\" en el contexto deportivo aludían al concepto islámico de esfuerzo personal y superación, no a la guerra santa. Se aportaron dictámenes de expertos en islam que explicaban el uso polisémico del término en la cultura musulmana. La estrategia incluyó demostrar la ausencia total de elementos típicos del yihadismo violento: no había exaltación de atentados, glorificación de terroristas, manuales operativos ni contactos con redes extremistas. Se enfatizó el perfil público del investigado como deportista e influencer con miles de seguidores, incompatible con la clandestinidad terrorista. Además, se cuestionó la proporcionalidad de la investigación y se denunció la criminalización de la religiosidad musulmana.",
      pruebas: "El análisis pericial de los dispositivos incautados fue la prueba fundamental. No se encontraron indicios de radicalización violenta: ni propaganda del ISIS/Al Qaeda, ni manuales de combate, ni comunicaciones cifradas con grupos terroristas. Los vídeos analizados mostraban únicamente rutinas deportivas con ocasionales referencias religiosas genéricas. Se aportaron testimonios de seguidores y colaboradores que confirmaban el carácter exclusivamente deportivo y motivacional del contenido. Peritos en terrorismo yihadista dictaminaron que el perfil no correspondía con los patrones de radicalización conocidos. La defensa presentó abundante jurisprudencia sobre libertad religiosa y los límites del delito de autoadoctrinamiento terrorista, que exige una vocación real de cometer atentados.",
      resolucion: "El Juzgado Central de Instrucción nº 2 de la Audiencia Nacional dictó Auto de sobreseimiento provisional el 10 de julio de 2025. La resolución estableció que no existían indicios racionales de criminalidad por delito de terrorismo. El instructor consideró que las manifestaciones religiosas del investigado, aunque pudieran resultar llamativas en el contexto de las redes sociales, no sobrepasaban el ejercicio legítimo de la libertad religiosa y de expresión. Se valoró especialmente la ausencia total de elementos objetivos de radicalización violenta y la falta de conexión con organizaciones terroristas. El Ministerio Fiscal no recurrió el auto, quedando firme el sobreseimiento. El investigado recuperó los dispositivos incautados y pudo continuar con su actividad en redes sociales.",
      marco_legal: "El caso se enmarcó en el artículo 575.2 del Código Penal que tipifica el autoadoctrinamiento terrorista. La jurisprudencia del Tribunal Supremo exige para su apreciación no solo el consumo de contenido radical sino la finalidad real de cometer delitos de terrorismo. La mera radicalización ideológica sin vocación delictiva no es punible. La resolución aplicó doctrina del TEDH sobre libertad religiosa (art. 9 CEDH) y expresión (art. 10 CEDH), recordando que solo cabe limitar estos derechos ante un peligro real e inminente para la seguridad nacional. También se invocó jurisprudencia sobre el principio de proporcionalidad en las investigaciones por terrorismo y los riesgos de criminalizar la religiosidad musulmana."
    }
  }
};
